### ISSUE TITLE
input type="range" doesn't update value in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#241] opened 2015-11-09 23:12 UTC
If you use the slider in the 'Another section' form in http://www.grommet.io/docs/hpe/develop/form on IE11 it doesn't update the value as it does on chrome and firefox.

I believe IE does things different for the range value...

**Comment by bryanjacquot** [comment] 2016-08-01 22:33
Reproduced in IE11 here: http://grommet.github.io/docs/form at the bottom of the Edit First Section form.

**Comment by jwijay** [comment] 2016-08-10 00:20
It looks like React v15 has a known issue with updating range inputs in IE11 using the React onChange event.

* See here for demo (vanilla JS onchange event firing correctly vs. React onChange event not firing when attached to a range input in IE11): https://jsfiddle.net/m78g29m5/
* Relevant Github issue: https://github.com/facebook/react/issues/3096#issuecomment-237354102
* Proposed workaround (using onMouseUp in addition to onChange): https://github.com/facebook/react/issues/554#issuecomment-188288228

Attaching the _onChangeRange function to the range input's onMouseUp event (in addition to the onChange event) appears to fix the issue for IE11. See PR: https://github.com/grommet/grommet-docs/pull/75

**Comment by jwijay** [comment] 2016-08-11 00:09
Closing this issue, as the relevant PRs have been merged:
https://github.com/grommet/grommet/pull/760
https://github.com/grommet/grommet-docs/pull/75

**Closed by jwijay** 2016-08-11 00:09 UTC
Labels: help wanted, in progress
