### ISSUE TITLE
In the Select Component dropdown the search text is not persisting after selecting some option and again if we open the dropdown we are not seeing the search text

### ISSUE THREAD

**Issue by deepakkatari** [grommet/grommet#5830] opened 2021-12-02 06:24 UTC
### Expected Behavior : 
If I search some text and select some option and again if I open dropdown the search text needs to be persisted in the search input. I didn't find any prop to persist the last searched text in search input.

### Actual Behavior
If I search some text and select some option and again if I open dropdown the search text is not persisting in the search input. But the dropdown options are displayed based on the previous search filter.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-x7uld?file=/index.js
<img width="315" alt="image" src="https://user-images.githubusercontent.com/46515664/144369006-266c6520-3b63-4afc-9235-c624f4d6dd7c.png">

<img width="376" alt="image" src="https://user-images.githubusercontent.com/46515664/144368781-1e649e80-e779-4a40-ae71-c1f5ff71eca9.png">

<img width="375" alt="image" src="https://user-images.githubusercontent.com/46515664/144368849-e9da6364-71d7-41cc-8b03-317b3dc9fe58.png">
<img width="254" alt="image" src="https://user-images.githubusercontent.com/46515664/144369152-bb63d891-b5f3-45a2-a51a-199680d79cbf.png">

### Steps to Reproduce
1. Open dropdown and search for 'tw' and select two from dropdown.
2. Now again open dropdown I see only the filtered list with previous search text (i.e 'tw') and the search text is not persisting in the search input. (I dont see any prop to place the previously searched text (i.e 'tw') in search input)

### Your Environment

- Grommet version:2.16.3
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): desktop

**Comment by karunakarareddyp** [comment] 2021-12-07 03:54
Even we are facing the same issue. Is there any way to set the persisted text to search the input box?

**Comment by matheushahnn** [comment] 2021-12-09 19:33
I think in this case you missed using the onClose method to clean the filtered options. 
I made some changes in your example https://codesandbox.io/s/grommet-v2-template-forked-wgs3l?file=/index.js hope it helps.

I see a different error when search and clicking out of the option, the search keeps the text but the filter doesn't work.

**Steps to reproduce**

Search by "option 3"

<img src="https://user-images.githubusercontent.com/7703431/145461561-368adb0e-793a-41ce-9e8e-72a8c5a3bbc2.png" alt="image" width="200">

Click out of option and again open dropdown

<img src="https://user-images.githubusercontent.com/7703431/145461721-a2879cfe-90a7-4a8c-b4c0-25d649d20e40.png" alt="image" width="200">

It happens in storybook

**Comment by jcfilben** [comment] 2021-12-15 21:41
@matheushahnn Thanks for sharing the codesandbox! I agree it looks like the original issue is just caused from not cleaning up in the `onClose()`.

I think the other issue you are seeing, where the search text is persisting after close but the options are not filtered, is a bug. The Select should either clear the search text when the drop closes or we should let the text persist and filter results.

**Comment by jcfilben** [comment] 2021-12-22 18:12
Closing since the issue discussed above is being tracked in #5865.

**Closed by jcfilben** 2021-12-22 18:12 UTC
