### ISSUE TITLE
Indside the grommet header menu alignment is not working.

### ISSUE THREAD

**Issue by sudesh-gama** [grommet/grommet#130] opened 2015-08-07 10:56 UTC
![errormenu](https://cloud.githubusercontent.com/assets/13653637/9134338/d668253e-3d20-11e5-8489-cd34a26c25c2.png)

![jscript](https://cloud.githubusercontent.com/assets/13653637/9134428/acdd21aa-3d21-11e5-8c48-da85ec9e5862.png)

**Comment by bryanjacquot** [comment] 2016-07-27 21:18
@sudesh-gama: it's been a while since you submitted this issue.  If you're still having issues, can you please create a CodePen to illustrate?  You can start with this Hello World pen: http://codepen.io/grommet/pen/gaEGPY

**Comment by alansouzati** [comment] 2016-08-03 17:20
Closing as we cannot reproduce this issue and it is one week that we asked for follow-up

**Closed by alansouzati** 2016-08-03 17:20 UTC
