### ISSUE TITLE
DateInput cannot be controlled by state

### ISSUE THREAD

**Issue by benwainwright** [grommet/grommet#4758] opened 2020-11-17 16:38 UTC
The `<DateInput />` field doesn't appear to allow itself to be controlled with `React.useState()`. See below:

# Expected Behavior

Clear button should result in `<DateInput />` clearing its value

### Actual Behavior

Nothing happens

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-716yv?file=/index.js:0-595

### Steps to Reproduce

1. Load above codesandbox
2. Click on date input and select a date
3. Click clear button

### Your Environment

- Grommet version: 2:15.2
- Browser Name and version: Chrome 86.0.4240.198 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): MacOS 10.14.6 (18G6032)

**Comment by jcfilben** [comment] 2020-11-18 22:39
I was able to reproduce the issue with your codesandbox that you provided, but I couldn't reproduce the issue using an example story in storybook. I think this may have something to do with how codesandbox is rendering. Here is a gif showing the code working as well as the sample code I used for the example:
![Nov-18-2020 15-37-25](https://user-images.githubusercontent.com/54560994/99596723-0afae900-29b4-11eb-88ce-5234cf83fecb.gif)

```javascript
import React from 'react';

import { Box, Button, Grommet, DateInput } from "grommet";

import { grommet } from 'grommet/themes';

export const TEST = () => {
  const [date, setDate] = React.useState();
  return (
    <Grommet theme={grommet}>
      <Box pad="small" gap="small">
        <DateInput
          format="dd/mm/yyyy"
          value={date}
          onChange={(event) => {
            setDate(event.value);
          }}
        />
        <Button onClick={() => setDate(undefined)} label="clear" />
      </Box>
    </Grommet>
  );
};
```
Let me know if you were able to reproduce the issue within a grommet project or using this example with storybook.

**Comment by benwainwright** [comment] 2020-11-18 23:20
> Let me know if you were able to reproduce the issue within a grommet project

I mean... the reason I raised this bug is that I'm hitting it within my own personal Grommet project, persistently. Is Storybook using the latest version of Grommet?

**Comment by jcfilben** [comment] 2020-11-18 23:36
Storybook is using the latest version of grommet, so the issue isn't there. Are you able to reproduce the issue with the code above?

**Comment by jcfilben** [comment] 2020-11-18 23:42
Try pointing to the stable branch instead of 2.15.2 https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F

**Comment by benwainwright** [comment] 2020-11-19 09:54
> Try pointing to the stable branch instead of 2.15.2 

Ok, I'll give that a go.

**Comment by benwainwright** [comment] 2020-11-19 10:27
Ok, that makes no difference. I'll try to create you a minimal repo that replicates the bug.

**Comment by benwainwright** [comment] 2020-11-19 10:49
@jcfilben Ok, a miminal repo based on the latest version of CRA (https://github.com/benwainwright/minimal-repo-dateinput-problem) does not reproduce the problem. I'm absolutely mystified...

**Comment by benwainwright** [comment] 2020-11-19 10:53
@jcfilben ok scratch that. Using latest stable does work - I must have not done it properly the first time.

**Comment by ShimiSun** [comment] 2020-11-20 19:20
Hi @benwainwright, thanks for reporting. 
I think the issue is already fixed on the master branch as @jcfilben suggested. you can deploy it by using 'stable' and let us know if you still see the issue https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F
I'll be closing the issue, feel free to reopen or inform us it the upgrade didn't do the trick. We'll be officially releasing soon.

**Closed by ShimiSun** 2020-11-20 19:20 UTC

**Comment by benwainwright** [comment] 2020-11-23 10:01
@ShimiSun Using stable does work, unfortunately using stable also breaks my CI for unknown reasons (some kind of integrity mismatch with Yarn install - think its clashing with my cache, which I can't seem to clear). This is not a huge issue *just* yet as the project has not been publicly released but it will become an issue soon.

**Comment by ShimiSun** [comment] 2020-11-23 16:18
@benwainwright the hash mismatch only means you'll need to update your dependencies, so if you are using yarn:
```
rm -rf yarn.lock
yarn cache clean
yarn install
```

That should fix it.
