### ISSUE TITLE
background property does not support linear-gradient anymore

### ISSUE THREAD

**Issue by bytewoopy** [grommet/grommet#4750] opened 2020-11-13 20:10 UTC
The background property for <Box> no longer supports css gradients as strings

### Expected Behavior

In previous versions it has worked, i rolled back to 2.10.0 and I get my gradients back, but in 2.15.2 they have stopped working. It seems 2.13 was the last working version for this (see code pen link)

### URL, screen shot, or Codepen exhibiting the issue

Try rolling back to 2.13 or older, gradient comes back.

https://codesandbox.io/s/thirsty-elgamal-8n0md?file=/src/App.js

### Steps to Reproduce

add this background property to Box component
`background="linear-gradient(rgba(0,0,0,1), rgba(34,26,62,1))"`

### Your Environment

- Grommet version: 2.15.2
- Browser Name and version: Chrome 
- Operating System and version (desktop or mobile): desktop, windows

**Comment by jcfilben** [comment] 2020-11-13 20:34
Hi @bytewoopy, I took a look at your codesandbox but it just looks like it is a blank starter sandbox, it doesn't have grommet and it doesn't show the behavior you are talking about in this issue. I created a codesandbox showing the gradient working in version 2.15.2 https://codesandbox.io/s/grommet-v2-template-forked-h6tyh?file=/index.js

**Comment by ShimiSun** [comment] 2020-11-19 18:22
Hi buddy, I'll be closing this issue, feel free to reopen if needed when provided more information.

**Comment by fuzing** [comment] 2020-11-27 21:19
I can also confirm that the background color property applied from a theme to Buttons no longer seems to support linear-gradients either - this used to work.

**Comment by ShimiSun** [comment] 2020-11-27 21:25
@fuzing are you using grommet v2.16.0? The problem is supposed to be solved on this release. Please send us reproducible code in case it doesn't.

**Comment by fuzing** [comment] 2020-11-27 22:29
Hi -

I was literally just about to say that after upgrading to 2.16.0 it appears fixed.......

Sorry!

**Closed** 2020-11-28 15:24 UTC
Labels: waiting
