### ISSUE TITLE
Notification component gets stacked and distorted in IE [IE specific]

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1396] opened 2017-06-20 14:59 UTC
When notification component is used in layers, its gets stacked, and takes improper width due to which the message gets stacked in different lines which makes UI loose its aesthetic value.
### Expected Behavior

Ideally it should take the message width and it shouldn't gets stacked and distorted
### Actual Behavior

When notification component is used in layers, its gets stacked, and takes improper width due to which the message gets stacked in different lines which makes UI loose its aesthetic value.
### URL, screen shot, or Codepen exhibiting the issue
Below is the codepen for the same:
https://codepen.io/nikitam/details/ZyKYEW/

### Steps to Reproduce
 1. just use the codepen
 2. 
 3. 

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: IE (11.0.9600.18665IS)
* Operating System and version (desktop or mobile): Windows & linux (Desktop)

**Comment by alansouzati** [comment] 2017-06-27 21:01
I was able to reproduce this in IE11. Not on Edge. I'm working on adding a fix for this. Thanks for reporting it.

**Comment by alansouzati** [comment] 2017-06-27 21:33
Yeah after my investigation I realized that the issue is because the width of the Notification is driven from its parent width. Layer does not have predefined width so we recommend adding a Box element as the immediate child of a Layer. In your case I would recommend adding a Sidebar. Check out this codepen:

https://codepen.io/alansouzati/pen/jwadRb?editors=0010

I'm closing this issue because it seems that there is nothing to be changed at Grommet core.

**Closed** 2017-06-27 21:33 UTC

**Comment by agrawalPratik** [comment] 2017-07-10 05:12
ok Thanks @alansouzati I have posted this to my dev team last week, hope this will solve our issue.
