### ISSUE TITLE
DataTable InfiniteScroll has stops intermittently

### ISSUE THREAD

**Issue by chrisstpierre** [grommet/grommet#3106] opened 2019-05-15 19:43 UTC
### Expected Behavior
When the bottom line of a DataTable with many rows of data is reached, the subsequent rows are supposed to load, and this is supposed to happen continuously until the end of the table.

### Actual Behavior

The scrolling works until some line of data is reached ( like line 150 - 300), and then scrolling stops. This seems to occur only when some row contains multi-line data.

### URL, screen shot, or Codepen exhibiting the issue

-- Here is a Codesandbox that shows the issue: https://codesandbox.io/s/datatable-scrolling-o87f1
-- If you change the data for url & bio to something that is short (ie single line only), then the DataTable will scroll as expected.

If you  

- Grommet version: 2.7.0

**Comment by mrebb** [comment] 2019-05-16 11:33
As discussed on Slack, Improving InfiniteScroll feature and fixing some of possible bugs is in progress. Will reference PR soon.

**Comment by ericsoderberghp** [comment] 2019-05-21 21:21
I have tried to reproduce this independently using grommet's storybook. While I could not get the scrolling to stop, it did get slower and slower, due to re-rendering so many rows. I think what is needed is to include the `replace` property from InfiniteScroll in DataTable as well. That would allow the caller to control that aspect of the InfiniteScroll within DataTable. Also, the DataTable `step` property is available but is not showing up in https://v2.grommet.io/datatable.

**Comment by chrisstpierre** [comment] 2019-05-22 07:35
I managed to fix the issue myself. I'm going to submit a pull request but I'm still thinking about what code to submit. 

The problem is the way it is being determined when rendering should start. Right now its based on current scroll position and page height, but isn't necessarily right if the page has varying content. I changed it to use scrollParent.scrollHeight and keep track of pages based on the different scroll rendering values. So a new render happens when get close to the end of the current scroll height. Which IMO is how it should work. Thoughts?

**Comment by ShimiSun** [comment] 2019-07-17 18:47
@chrisstpierre thanks for sharing your thoughts, I think that filing your fix with a PR and choosing the way you thought best of solving the problem will be a great way to continue the conversation. will you be able to file a PR?

**Comment by markjackson02** [comment] 2020-02-19 20:41
@chrisstpierre do you plan on opening a PR for this? @ShimiSun i am experiencing similar issue on Android Chrome, i am infinite loading images (1 per row), and only my first 3 images show up and scrolling down does not trigger new items. However it works on Windows Chrome.

**Comment by ShimiSun** [comment] 2020-02-19 23:53
@markjackson02 can you share a codesandbox that will reproduce the issue reliably without app side effects?

**Comment by ShimiSun** [comment] 2020-04-04 13:56
@chrisstpierre any progress with a PR? needs any help or guidance from us?

**Comment by mrnguuyen** [comment] 2020-05-26 23:32
@ShimiSun , I am also encountering the same issue but with InfiniteScroll by itself rather than just DataTable. This is an intermittent issue.

Reproducible Issue: https://codesandbox.io/s/gifted-surf-ispcb?file=/src/App.js

It seems like whenever the Licensing column has about or more than 5 lines of data, I am unable to scroll for more data. 

@chrisstpierre , do you have any plans of possiblely submitting that PR? Would love to know your solution/workaround.

**Comment by chrisstpierre** [comment] 2020-05-26 23:47
unfortunately I don't have the time to help with this issue. sorry

**Comment by halocline** [comment] 2020-11-24 16:03
I believe this issue has been resolved by https://github.com/grommet/grommet/pull/4642

**Comment by ShimiSun** [comment] 2020-11-24 20:38
Fix will be available on grommet 2.16.0 upcoming release

**Closed by ShimiSun** 2020-11-24 20:38 UTC
Labels: DataTable, in progress, waiting
