### ISSUE TITLE
Menu "Drop" box is not the correct width on first load.

### ISSUE THREAD

**Issue by dipunm** [grommet/grommet#4066] opened 2020-05-09 19:28 UTC
### Expected Behavior
When opening menu, the dropdown is perfectly sized

### Actual Behavior
This seems to happen only when developer tools is open in Firefox (currently using v76.0 on Ubuntu)
Edit: I can reproduce on Android (chrome) every now and then. There is no scrollbar, but the text is cut off.
On first load only, the menu is too small (width calculation seems to fall short) and there is a scroll bar at the bottom.

One interesting thing is that if the menu is open by default, it looks fine until closed and opened again.

Closing and re-opening the menu fixes this until the next page refresh.

### URL, screen shot, or Codepen exhibiting the issue
Sandbox:
Be sure to open devtools and use Firefox. ( I managed to reproduce once only in chrome, now I can't anymore)
https://codesandbox.io/s/polished-frost-tek9b?file=/src/App.js

### Steps to Reproduce

1. open preview in a new window (open in new window button)
2. open developer tools
3. click the menu button on the top right

![image](https://user-images.githubusercontent.com/5099980/81483197-44e47900-9234-11ea-9c95-6f2563ed5a47.png)

![Screenshot_20200509_204715_com android chrome](https://user-images.githubusercontent.com/5099980/81483504-ab6a9680-9236-11ea-88e1-046ba99fce8c.jpg)

### Your Environment

- Grommet version:  2.13.0
- Browser Name and version: Firefox 76.0
- Operating System and version (desktop or mobile): Ubuntu 19.04 LTS

**Comment by IanKBovard** [comment] 2020-05-13 19:24
@dipunm I'm having a hard time reproducing it in firefox. I was able to briefly see a scrollbar in chrome, but after that have not been able to replicate it. Are there any other conditions i must meet?

Just to clarify here's what i've done to test. 
  open the preview in a new window
  open dev tools
  change widths
  click the menu button
  go into responsive design mode
  change to various sizes
  click the menu button

**Comment by IanKBovard** [comment] 2020-05-13 19:27
Are you able to reproduce it consistently?

**Comment by dipunm** [comment] 2020-05-13 19:42
I have been trying to reproduce again. I can't do it. I did manage to reproduce once like you said, and then I tried things like throttling network, throttling cpu (only possible in chrome) and I can't reproduce this anymore :(.

The annoying thing is that I was able to reproduce on android once too and it was consistent before.

Oh well, I guess we could close this and I can re-open if/when I can gather more information.

Thanks for looking into it :)

**Comment by IanKBovard** [comment] 2020-05-13 20:01
Thanks for the response! I say lets keep this open for a little while longer. I'll do some more digging to see if i can replicate it consistently.

**Comment by YarynaBukovynskaHPE** [comment] 2020-06-22 14:44
Hi! This issue is still reproducible. In Chrome also. Time to time the dropdown isn't opened full-sized and gets proper width on hovering. Please, take a look at this.

**Comment by chesleyratliff** [comment] 2020-06-26 14:42
Is there an update here? We see this continuously in Greenlake Compliance

**Comment by ShimiSun** [comment] 2020-06-26 15:39
@chesleyratliff If you could share reproducible code for how your team is encountering the issue, it will help @IanKBovard with the investigation and solution proposal.

**Comment by IanKBovard** [comment] 2020-06-29 15:06
@chesleyratliff could you give me an example in codesandbox that reproduces the issue. I'm having trouble replicating it.

**Comment by jesseolsen** [comment] 2020-07-09 23:44
@IanKBovard I had this issue, too, but by pulling the <Drop> outside of a <Button> and <DropButton> (had it in two spots of the code), I was able to avoid this, so now we no longer have the issue.  Something like this: https://codesandbox.io/s/strange-williams-f7vmd?file=/src/App.js:1111-1196

**Comment by IanKBovard** [comment] 2020-07-10 13:55
This issue can be closed, It was a problem with implementation. Thank you @jesseolsen for working with me to find a solution.

**Comment by ShimiSun** [comment] 2020-07-10 17:12
Thanks @IanKBovard , can you please suggest a fix for the codesandbox attached to the issue, so the user can understand how to solve it before closing it.

**Comment by IanKBovard** [comment] 2020-07-10 17:20
This codesandbox that jesse posted is a fix, and the correct implementation.
https://codesandbox.io/s/strange-williams-f7vmd?file=/src/App.js

This initial codesandbox posted does not reproduce the issue, and I have not been able to reproduce it myself.

@dipunm is unable to reproduce it himself, as well. This is a response from earlier in the conversation.
> I have been trying to reproduce again. I can't do it. I did manage to reproduce once like you said, and then I tried things like throttling network, throttling cpu (only possible in chrome) and I can't reproduce this anymore :(.
> 
> The annoying thing is that I was able to reproduce on android once too and it was consistent before.
> 
> Oh well, I guess we could close this and I can re-open if/when I can gather more information.
> 
> Thanks for looking into it :)

**Comment by ShimiSun** [comment] 2020-07-10 17:24
Thank you for working on it @IanKBovard & @jesseolsen !

**Closed** 2020-07-10 17:24 UTC
