### ISSUE TITLE
Click on CheckBox label and label right margin

### ISSUE THREAD

**Issue by dioklecijan** [grommet/grommet#1293] opened 2017-04-07 09:28 UTC
Minor correction required:

a) Click on the input part of the checkbox toggles checkbox state. It is expected.
b) Click on the checkbox label does not toggle the state.
c ) Click on checkbox label right margin toggles the state.

===> b and c should behave in the same way or opposite of the currant behavior.

**Comment by dgennetten** [comment] 2017-04-25 20:28
@dioklecijan, can you provide environment details? Seems to be working fine in chrome, safari, edge, and IE.

**Comment by dioklecijan** [comment] 2017-04-26 09:30
Hi @dgennetten,

1. Point your browser to https://grommet.github.io/docs/check-box/examples
2. Click on the text "Sample label" => state is not toggled (note that mouse pointer is an arrow)
3. Move the mouse pointer right of the text, (mouse pointer is changed from arrow to the hand) 
4. Click ==> state is changed

I tried this with Google Chrome (Version 57.0.2987.133 (64-bit)) and Firefox (53.0 (64-bit)), both on MacOS.

I marked "state triggering" area in an attached picture:

![chboxtriggerarea](https://cloud.githubusercontent.com/assets/4146161/25427635/7f9b84b6-2a73-11e7-9770-0b81960efcd6.png)

**Comment by SuhairZain** [comment] 2017-04-26 10:24
I can confirm that this issue exists. It's because the rendered label depends on a [**for**](https://github.com/grommet/grommet/blob/master/src/js/components/CheckBox.js#L29) to handle the clicks on it. A workaround would be to simply set an id to the checkbox.
```jsx
<CheckBox
  label="Check Me"
  id="check_me" />
```

**Comment by dgennetten** [comment] 2017-04-26 14:23
Ah. I was looking at this instance, where it is working fine: https://grommet.github.io/docs/check-box

**Comment by alansouzati** [comment] 2017-06-07 22:26
Fixed in the PR

**Closed by alansouzati** 2017-06-07 22:26 UTC
Labels: in progress
