### ISSUE TITLE
v2 Video multiple warnings on non-bool props

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2221] opened 2018-08-28 05:28 UTC
Videos passes wrong props to several components: assumes the and Menu (dropBackground)

1. Box - background
![screenshot733](https://user-images.githubusercontent.com/6075606/44702339-fa6f9880-aa60-11e8-92a6-4f5a1568c3f3.jpg)

2. Icon - color
![screenshot734](https://user-images.githubusercontent.com/6075606/44702423-69e58800-aa61-11e8-9dab-556a05f12ee1.jpg)

3. Meter - background
![screenshot735](https://user-images.githubusercontent.com/6075606/44702442-7ff34880-aa61-11e8-8ec8-5babb5f831ea.jpg)

4. Menu - dropBackground
![screenshot736](https://user-images.githubusercontent.com/6075606/44702473-9f8a7100-aa61-11e8-88b3-25e050bc0cc0.jpg)

**Comment by ericsoderberghp** [comment] 2018-08-29 23:29
I believe these were fixed in https://github.com/grommet/grommet/pull/2231. I cannot reproduce them with the latest grommet storybook. https://storybook.grommet.io/?selectedKind=Video&selectedStory=Simple%20Video&full=0&addons=0&stories=1&panelRight=0

**Closed by ericsoderberghp** 2018-08-29 23:29 UTC
