### ISSUE TITLE
Select component ref is not compatible with typescript.

### ISSUE THREAD

**Issue by B-Esmaili** [grommet/grommet#5151] opened 2021-04-08 08:30 UTC
### Expected Behavior

Typescript should not show an error for ref passed to `Select` component.

### Actual Behavior

When i pass a ref to `Select` component it gives me ` Property 'ref' does not exist on type 'IntrinsicAttributes & SelectProps & { children?: ReactNode; }`

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/fervent-hoover-9o8ue?file=/src/App.tsx

**Comment by ShimiSun** [comment] 2021-04-08 22:24
Thank you, the issue is fixed by @jasnross and will be available on grommet v2.17.2

**Closed by ShimiSun** 2021-04-08 22:24 UTC
