### ISSUE TITLE
Accordion, Drop broken on storybook

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#2710] opened 2019-01-31 00:44 UTC
When I click on Accordion > Rich I'm getting this error in [Storybook](https://storybook.grommet.io):

`Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:480
    at t (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:583)
    at af (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:41529)
    at r (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:51477)
    at B (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:52750)
    at https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:54726
    at Q (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:55966)
    at Ag (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:63993)
    at lh (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:78923)
    at mh (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:79288)`

Similar issue for Drop > All not stretch.

**Comment by oorestisime** [comment] 2019-01-31 07:49
I ve started storybook locally and didn't reproduce this. maybe it was broken before but seems to work now at least on current master.

**Comment by ShimiSun** [comment] 2019-01-31 16:16
@oorestisime you can run `yarn build-storybook` and then run the `index.html` created in the local static folder created.
The problem reproduces on https://storybook.grommet.io/?selectedKind=Drop&selectedStory=All%20not%20stretch&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
as well. It caused by the deep merged theme, I'm looking at it

**Comment by ShimiSun** [comment] 2019-02-07 19:20
@markjackson02 thank you for reporting!

**Closed** 2019-02-07 19:20 UTC
Labels: Bug :bug:
