### ISSUE TITLE
Default data on third click of the sort

### ISSUE THREAD

**Issue by dileepthomas** [grommet/grommet#4324] opened 2020-07-18 08:57 UTC
I am using the data table component for learning react, the one feature i was looking at the default sort.

**UseCase With Explanation**

I render a table, which has three columns **name, age and location**. So here the name column is able to sort, but when i render the table the icon of the column shows is descending, i need to show default icon like descending and ascending like a vertical icon.

So the user knows the table is not sorted and he can click on the icon, now from there it will start to desc -> asc -> default

Assume the data flow  initial render default -> click desc -> click asc -> again click back to default
**Default**      **desc**        **asc**      **Default**
D                              S                  A                  D
A                              D                  D                  A
S                              A                  S                   S

Is this possible, Can i tweak some code and do the changes, new to this one, only this one was the missing

**Comment by ShimiSun** [comment] 2020-07-20 17:32
Hi there, you didn't specify which grommet version you are using. It will be helpful for us if you can fill in the template we suggest for filing an issue.
We solved the icon problem you described a couple of releases ago, make sure you are using the latest grommet version.

**Comment by jcfilben** [comment] 2020-09-11 21:28
Hi @dileepthomas did upgrading to the latest version of grommet (2.15) solve this issue? Let us know, and if so we should be able to close the issue.

**Comment by ShimiSun** [comment] 2020-09-13 16:45
I'll be closing the issue, feel free to reopen with the missing version information if the issue is still relevant.

**Closed by ShimiSun** 2020-09-13 16:45 UTC
Labels: waiting
