### ISSUE TITLE
Select drop-down missing clear button FF

### ISSUE THREAD

**Issue by ypinnek1** [grommet/grommet#3084] opened 2019-05-03 22:49 UTC
Select drop-down missing clear button FF (close button in the input)

This issue exists only in FF. Other browser does have the clear button. We need to make this consistent across all browser.

**Comment by oorestisime** [comment] 2019-05-04 07:23
I think this is a duplicate of #2973

**Comment by ShimiSun** [comment] 2019-05-06 20:36
Spot on @oorestisime.
@ypinnek1 feel free to add any more info if you feel like anything is missing from issue #2973

**Closed by ShimiSun** 2019-05-06 20:36 UTC
