### ISSUE TITLE
Select component does not set value to selected option

### ISSUE THREAD

**Issue by rohit8** [grommet/grommet#3851] opened 2020-03-16 04:10 UTC
### Expected Behavior
An option selected should set the Select value on first click.

### Actual Behavior
If you scroll down the list of options and select an option, the Select component doesn't set the value, and scrolls up the list instead. However, selecting the same value the second time works.

### URL, screen shot, or Codepen exhibiting the issue

https://storybook.grommet.io/?path=/story/form--select

### Steps to Reproduce
1. Click the dropdown
2. Scroll down the list of options.
3. Select an option

### Your Environment
- Grommet version: 2.11.2
- Browser Name and version: Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): MacOS Mojave 10.14.6 (Desktop)

![captured](https://user-images.githubusercontent.com/2968479/76722539-689aaf80-671a-11ea-9b95-058ecaa0574b.gif)

**Comment by ShimiSun** [comment] 2020-03-16 15:29
Thanks for reporting buddy!

**Comment by bcliffor** [comment] 2020-06-19 20:45
Thanks for working on Grommet all. Just wanted to bump this issue since it's been causing a lot of annoyance for my team too.

**Comment by ShimiSun** [comment] 2020-06-19 21:07
@bcliffor thanks for the bump, few released a new version last week that seems to have fixed the issue as you can see https://codesandbox.io/s/form-select-many-options-h1r9e?file=/index.js
On the codesandbox, if you'll change the version of grommet to 2.11.2 you'll see the issue reproduces, but on the recent release of 2.14.0 the issue is already fixed. Please confirm.

**Comment by bcliffor** [comment] 2020-06-19 21:14
Definitely fixed!

Thanks for the very quick response @ShimiSun !

**Comment by ShimiSun** [comment] 2020-06-19 21:24
Woohoo, I'll be closing the issue, thank you all for the collaboration.

**Closed by ShimiSun** 2020-06-19 21:24 UTC
Labels: Bug :bug:, waiting
