### ISSUE TITLE
Type definitions DropButton do not contain label prop

### ISSUE THREAD

**Issue by jhlabs** [grommet/grommet#3052] opened 2019-04-25 17:45 UTC
The type definitions for the DropButton do not contain the label prop.

### Expected Behavior

Label should be part of the type definitions.

### Actual Behavior

Label is not defined in the type definition.

### Steps to Reproduce

Check the definitions file.

### Your Environment

- Grommet version: 2.6.5

**Comment by erick2014** [comment] 2019-05-02 22:31
I want to work on this issue, but I have a question, what do u mean with type definitions? do you expect to this component to receive a label prop or something?

Regards

**Comment by ShimiSun** [comment] 2019-05-03 03:48
@erick2014 I think he means that the index.d.ts file isn't supporting the acceptance of label prop.
So if a typescript user is consuming a label within DropButton, he'll get a TS error.
This is a sandbox template of Grommet with typescript if you'd like to reproduce the problem https://codesandbox.io/s/olxj16ox66
and this is the file
https://github.com/grommet/grommet/blob/master/src/js/components/DropButton/index.d.ts

**Comment by a-peltier** [comment] 2019-05-11 09:50
I wanted to contribute and fix that issue, but I found that consuming a label within DropButton does not give a TS error, as shown in this sandbox : https://codesandbox.io/embed/q9nvqqmwx6

That is because the the DropButton component is typed to accept both DropButtonProps and the ButtonProps interfaces (and ButtonProps does contain the "label" prop):

`declare const DropButton: React.ComponentClass<DropButtonProps & ButtonProps>;`
see file : https://github.com/grommet/grommet/blob/master/src/js/components/DropButton/index.d.ts

@jhlabs if you need to import the DropButton props to extend them, using `DropButtonProps & ButtonProps` should do the job :)

**Comment by oorestisime** [comment] 2019-06-26 21:48
Closing this since the codesandbox seems to be working fine! don't hesitate to reopen if something is wrong!

**Closed by oorestisime** 2019-06-26 21:48 UTC
Labels: Bug :bug:, good first issue
