### ISSUE TITLE
No gaps when using React.Fragment in Box

### ISSUE THREAD

**Issue by partynikko** [grommet/grommet#3381] opened 2019-09-27 12:52 UTC
Hi there! 👋 

If children to a `<Box />` are wrapped in a `React.Fragment` those children will not get gap elements injected in between - there will be no gaps.

### Expected Behavior
I expect mentioned above to work.

### Actual Behavior
No gap elements are injected.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-ohyqb?fontsize=14

### Steps to Reproduce
```javascript
<Box gap="medium">
  <React.Fragment>
    <span>1</span>
    <span>2</span>
    <span>3</span>
  </React.Fragment>
</Box>
```

### Your Environment

- Grommet version: **2.7.8**
- Browser Name and version: **Google Chrome 77.0.3865.90**
- Operating System and version (desktop or mobile): **macOS desktop**
______________________________
I guess this happens because gaps are created by iterating the children but since the fragment is "the only child" this happens, even if when rendered to the DOM there is no fragment.

Is this expected behaviour due to the nature of `React.Fragment` or should it be solved?

**Comment by partynikko** [comment] 2019-09-27 13:04
I found this in React documentation regarding `React.Children` which is used to iterate the children in the `<Box />` component:

> If children is a Fragment it will be treated as a single child and not traversed.
https://reactjs.org/docs/react-api.html#reactchildrenmap

**Comment by oorestisime** [comment] 2019-09-29 06:49
I am inclined to say this is the normal behaviour and this is not a bug.

**Comment by ericsoderberghp** [comment] 2019-09-29 06:50
agreed

**Comment by oorestisime** [comment] 2019-09-29 16:47
I ll be closing this. feel free to contribute more in the discussion if you feel there is something for us to do here.

**Closed by oorestisime** 2019-09-29 16:47 UTC
