### ISSUE TITLE
Calendar gives one day earlier date instead of the selected date

### ISSUE THREAD

**Issue by eminx** [grommet/grommet#4769] opened 2020-11-20 11:29 UTC
When used with a single and uncontrolled, `Calendar` component prop `onSelect` function gives one day earlier than the seemingly selected date. 

### Expected Behavior

The date that is given by the `onSelect` prop should give the date that is selected by the user.

### Actual Behavior

Given date by `onSelect` is one day earlier than the selected date

### URL, screen shot, or Codepen exhibiting the issue

https://gbjtf.csb.app

https://codesandbox.io/s/great-bird-gbjtf?file=/src/App.js

### Steps to Reproduce

Just visit the above links

### Your Environment

Agnostic to env as it can be reproduced both in my env as well as CodeSandBox

- Grommet version: 2.15.2
- Browser Name and version: Opera
- Operating System and version (desktop or mobile): Mac OSx

**Comment by oskari** [comment] 2020-11-20 12:23
Internally the Calender seems to use `toISOString` and thus returns the value as such on `onSelect`, so it ends to be UTC time, which if you happen to live in a positive timezone, falls to an date earlier than selected.

You could use something like date-fns (easy) or vanilla js methods (bit more complex) to parse and format the date to something in your timezone.

Not sure what the calender should return, giving a date with timezone notation is technically correct but might be confusing for the use. Would `toLocaleDateString(locale)` be a good choice?

**Comment by msalehy** [comment] 2020-11-20 12:29
<Calendar
        onSelect={(nextDate) =>
          alert(
            `this is your local time converted from UTC:  ${new Date(nextDate)}`
          )
        }
      />

**Comment by msalehy** [comment] 2020-11-20 12:29
`      <Calendar
        onSelect={(nextDate) =>
          alert(
            `this is your local time converted from UTC:  ${new Date(nextDate)}`
          )
        }
      />`

**Comment by eminx** [comment] 2020-11-20 13:10
@msalehy @oskari 

I think that parsing the given date to something that works is just a workaround and does not eliminate the core problem.

First of all, it's not a timezone issue - can't be. Because it's about the semantic problem of what you click and what you get, regardless of where you are on earth. Besides, I may be 2-3 hours away from UTC but I'm in the same day as almost all parts of the world atm, and it doesn't make sense that I get one day earlier...

So, I'm not convinced that this workaround addresses the core problem. At least for me 😄

**Comment by uris77** [comment] 2020-11-21 17:57
I agree, this is annoying and unexpected behavior. Especially since it isn't documented. Maybe provide an option to specify the timezone or to not use a timezone in some cases.

**Comment by DanielBaird** [comment] 2020-11-22 23:36
I'm in a positive timezone (+10 -- when it's 9am here, it's 3pm the previous day in Seattle) and the codesandbox in the initial comment gives me the day before I select. So this seems like a plain ol' bug, rather than a timezone issue.

**Comment by oskari** [comment] 2020-11-23 06:45
> First of all, it's not a timezone issue - can't be. Because it's about the semantic problem of what you click and what you get, regardless of where you are on earth. Besides, I may be 2-3 hours away from UTC but I'm in the same day as almost all parts of the world atm, and it doesn't make sense that I get one day earlier...
> 
> So, I'm not convinced that this workaround addresses the core problem. At least for me 😄


> I agree, this is annoying and unexpected behavior. Especially since it isn't documented. Maybe provide an option to specify the timezone or to not use a timezone in some cases.

> I'm in a positive timezone (+10 -- when it's 9am here, it's 3pm the previous day in Seattle) and the codesandbox in the initial comment gives me the day before I select. So this seems like a plain ol' bug, rather than a timezone issue.

_How it works currently and why it isn't "wrong":_
When you click a date, it selects the first moment of that date (in your local time) which is midnight and creates the date object from that, but when when it's returned it's converted to ISO 8601 date which is UTC+0 by default. This is in the documentation and in the example of `onSelect` (See the 'Z' after the date, which is timezone indicator for UTC).  I don't see how this is wrong. It just isn't in the same timezone as you are, but it's still the same datetime you selected. If you add/remove your UTC offset to this date, you get it in your timezone. 

I don't think having to do timezone conversions is hacky, annoying or somehow wrong but I understand the frustration when you expect to only use the date part. 

I don't see much options on changing this behavior without making breaking changes, except to introduce a prop `timezone` which would affect the output of the component by using [Date.toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)

[See this SO answer for more information about Date and timezones](https://stackoverflow.com/questions/15141762/how-to-initialize-a-javascript-date-to-a-particular-time-zone)

**Comment by eminx** [comment] 2020-11-23 10:40
@oskari  thanks for your comment.
Technically speaking, to my capacity of digging in so far and as you noted, the core reason that clicked date is one day before the current day for positive time zone users is that the date registered with ISO format registers the `time` as `00:00:00` - beginning of the day. Which in any positive time zone returns as the day before... 

So this means that instead of making such assumption of registering the clicked date with the time that is the beginning of the day; it could instead register it with the middle of the day. (However, I don't know if it's a convention to register it as the beginning of the day..) Then I believe this could be overcome.

Semantically speaking, it's natural user behavior to expect that if you click something you get an appropriation of that... Of course it's relative to state that this is a bug or feature or what-not; but I would propose that within the scope of Grommet, user behavior and expectations (user referring both to developers as well as end users) should be prioritised over technical reasons. Technology, at the end, serves humans; not the other way around. 

Lastly, I do think that having to convert should not be a necessity, if it's not a hack. One of the main reasons we use such tools as this wonderful Grommet library is to not have to learn every bit of technical knowledge like this date parsing in Javascript that you sent us to learn. It could do it for us instead. Of course it's nice to learn this knowledge just as any other, but then we would like to choose what we want to learn over what we have to...

**Comment by oskari** [comment] 2020-11-23 11:24
I understand your point and I agree that semantically it should always return the day that was selected in the UI. I'm just not sure what kind of solution would satisfy everybody here.

What do you suggest that should be returned? Just date ignoring the whole time part? Automatically convert the date to users timezone, instead of the current UTC time?

Would using a prop that I mentioned in my previous comment to control the output be sufficient?

**Comment by eminx** [comment] 2020-11-23 11:41
I think whatever the solution is, it should be in line with Grommet conventions as well as general date programming conventions...

The first thing I can think of is to initially set the time in UTC format not the beginning of the day but perhaps the middle of the day? Like `T12:00:00.000Z`

**Comment by eminx** [comment] 2020-11-23 11:43
Or another, probably better, option would be to check the local time on the browser and accordingly set the UTC time...

**Comment by taysea** [comment] 2020-11-23 17:10
Hey @eminx I see that you are on grommet 2.15.2, but I recently submitted a fix that aimed to remove this issue (https://github.com/grommet/grommet/pull/4742) -- could you try pointing your application to grommet stable (https://github.com/grommet/grommet/tarball/stable) and see if this issue goes away?

**Comment by nefario7** [comment] 2020-12-04 13:13
What's the update on this issue? I too am facing this issue on my website.

**Comment by halocline** [comment] 2020-12-04 16:31
@nefario7 I believe the timezone issue was [fixed and released in v2.16.0](https://github.com/grommet/grommet/releases/tag/v2.16.0). Can you try using the latest version and report back as to whether your issue has been resolved?

**Closed** 2020-12-04 16:58 UTC
Labels: Bug :bug:, waiting
