### ISSUE TITLE
Overwriting breakpoints in theme leads to malfunctions

### ISSUE THREAD

**Issue by mihai-ro** [grommet/grommet#4196] opened 2020-06-16 07:48 UTC
WHEN adding custom breakpoints in `theme.global.breakpoints`,
THEN the two objects should be merged, with the custom ones overwriting the default values;
INSTEAD the `medium` breakpoint is NOT being overwritten
AND is still being resolved as the default, instead of the overwritten value.

### Expected Behavior
Custom breakpoints are resolved with both the provided value and the configuration, and the default values are being overwritten;

### Actual Behavior
`ResponsiveContext` resolves to `medium` on screen sizes that should provide custom breakpoint values; 

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-breakpoints-14zbx

### Steps to Reproduce
1. Provide Grommet a theme with `global.breakpoints` that creates new breakpoints and overwrites existing ones (e.g.: `xsmall`, `small`, `medium`, `large`, `xlarge`)
2. Wrap your component in ResponsiveContext and log its result
3. Start resizing the window and see the logs

### Your Environment
- Grommet version: 2.14.0
- Browser Name and version: Chrome 83.0.4103.97
- Operating System and version (desktop or mobile): OSX Catalina 10.15.5, desktop

**Comment by ShimiSun** [comment] 2020-06-19 16:12
Hi buddy! thanks for reporting this issue!
I've filed a PR to fix it. 
In the meanwhile, until the PR will be merged and released, modify the last breakpoint value to a high window size value (e.g. 5000) so you won't see the issue reproducing on your client.
Thanks again!

**Closed** 2020-06-25 14:11 UTC
Labels: Bug :bug:

**Comment by ShimiSun** [comment] 2020-06-25 17:56
The issue is fixed and will be available on our next release (release later than 2.14.0). Thanks for reporting.
