### ISSUE TITLE
Double border for TextInput inside of a FormField

### ISSUE THREAD

**Issue by arabold** [grommet/grommet#1531] opened 2017-08-01 21:14 UTC
Upgrading from Grommet 1.5.0 to 1.6.0 changes the way form fields are rendered.

### Expected Behavior
In Grommet 1.5.0 a `<TextInput />` wrapped in a `<FormField />` used to render with just a single outline like this:

![image](https://user-images.githubusercontent.com/1548229/28847228-5290d5e2-76c3-11e7-98a3-11ab5820f655.png)

### Actual Behavior
After upgrading to Grommet 1.6.0 the look changed and now we see a double border:

![image](https://user-images.githubusercontent.com/1548229/28847289-886df3d4-76c3-11e7-9f71-c65d2953cc43.png)

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/anon/pen/wqWzGN?&editors=0010
```jsx
class HelloWorldApp extends React.Component {
  render () {
    return (
      <App>
        <FormField>
          <TextInput value="Test" />
        </FormField>
      </App>
    );
  }
};

var element = document.getElementById('content');
ReactDOM.render(<HelloWorldApp />, element);
```

### Your Environment
* Grommet version: 1.6.0
* Browser Name and version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): MacOSX

**Comment by alansouzati** [comment] 2017-08-01 21:37
yeah I noticed that after releasing 1.6.0. let me investigate what is going on and release 1.6.1 sometime later today. sorry about that.

**Comment by cherih** [comment] 2017-08-05 00:17
Was able to reproduce this in my sandbox today and will work on debugging  and fixing it.

**Comment by oswaldoacauan** [comment] 2017-08-11 17:13
This happens because the input is missing the `[type="text"]`.

The same problem happens when you have inputs of type 'tel' or 'url'.

**Comment by cherih** [comment] 2017-08-11 20:26
@oswaldoacauan - thank you for suggesting a solution for this. Yes, we would love to have a PR for it, if you can do that.

**Comment by sourcepirate** [comment] 2017-08-19 10:20
+1

**Comment by cherih** [comment] 2017-08-25 22:18
This issue has been fixed and will be included in a soon to be released new version of grommet.

Thanks to Alan and Eric for figuring this out.

**Comment by oswaldoacauan** [comment] 2017-08-28 11:04
The issue remain with inputs type `tel` and `url`.

**Comment by cherih** [comment] 2017-08-30 22:57
Fixed the issue for input types tel and url.

**Closed by cherih** 2017-08-30 22:57 UTC
Labels: in progress

**Comment by waltercruz** [comment] 2019-06-14 17:03
Hi! Sorry for the noise on this ticket 2 years after, but with grommet 2, TextInput still seems not to include type="text". Is this by design?
