### ISSUE TITLE
Calendar is one day off for all interfaces

### ISSUE THREAD

**Issue by maryjufang** [grommet/grommet#4352] opened 2020-07-28 18:04 UTC
When pass in range (dates), onSelect, dates are off one day, including dates range, and onSelect call back.

### Expected Behavior
Date should be same the the one clicked.
Located in RTP time zone (EST)

### Actual Behavior
all dates are 1 day off

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/9951106/88703789-2f684800-d0db-11ea-88ef-738a15d97faa.png)

**Comment by cscognamiglio** [comment] 2020-10-05 15:35
I have a very similar issue when using the DateInput in a FormField, if the date is selected with the dropdown it seems ok, if it is entered by hand the date results in the day before at 23 hours. In the pictures below the field date has the wrong timestamp as soon as the Form gets updated.

![Screenshot 2020-10-05 at 17 34 46](https://user-images.githubusercontent.com/11227537/95100155-18745080-0731-11eb-88b0-bc624f123be8.png)
![Screenshot 2020-10-05 at 17 32 20](https://user-images.githubusercontent.com/11227537/95100176-1ca06e00-0731-11eb-812d-6abaf685e68b.png)

**Comment by ShimiSun** [comment] 2020-10-05 16:26
@taysea is this related at all to the issue you are working on?

**Comment by taysea** [comment] 2020-10-05 17:17
@ShimiSun This is related in the sense that it has to do with Calendar date selection, but it is not exactly related when it comes to behavior. The issue I am working on is more around the logic of selecting start and end dates for DateInput with range

**Comment by ShimiSun** [comment] 2020-10-05 17:26
Thanks for the update @taysea , I just merged a fix that is also related to the Calendar date selection https://github.com/grommet/grommet/pull/4541 might be worth to take a look at whether it helps to the overall solution.

**Comment by husseyexplores** [comment] 2020-10-06 15:46
I think it is not a bug but just the timezone difference.

If the user timezone is ahead (+1, +2, +3.. etc) then essentially, it means that the next day will start `+timzone offset` early.
And since grommet returns the UTC timezone, the time it is set to a previous day to accommodate the timezone difference. The returning time will be the user's local time with 00 hours.

For example, if I'm in +5 and select `October 6, 2020` from the calendar, I'll get `October 6, 2020, 00:00:00 +5GMT` which translates into `October 5, 2020: 19:00:00 UTC`.

We can make the date object from the UTC date and get the local date again.

[Example here](https://v2.grommet.io/calendar?c=DwYQhgNgpgdgJmATgKAASoM4EsBeUC8ARBgLaQSFqoD2MAylNAMYAu+A3gBQItQCUqfAD5U7Kuia0M1aADoI1AOacA5AB0YAWm06dKvuNSSY0uQuUqAqgBUQqHlABcqFQBp7YXgfQSpMqPJKqgAy1EyQHrzObugwUADuqAAinlDcqXyyLNR0LIhYMMp83qgAvqXIAPRCQA).
(Set your computer timezone to positive timezone to see the difference in dates. You may have to refresh the page after changing the timezone.)

If we show the selected date in an absolute UTC date (00 hours), then again it will create the same problem for the users which are behind in the timezone.

**Comment by cscognamiglio** [comment] 2020-10-06 16:55
So, first of all my mistake, the bug I am seeing is for the DateInput and not the Calendar component, so maybe I should open a new issue?

The problem is between picking a date and inputting a date manually, there is a discrepancy and you can easily verify it with the link below.
The date parameter passed to the onChange is in the first case a date (correct one) in the second case an event object and here the date is wrong, the value is actually a timestamp and in my case 2 hours behind, so yes it must be a timezone issue.

https://v2.grommet.io/dateinput?c=DwEQhgLgpgkgdgBwK4QFAAJ0DMD2AnAW0gF4AiAE3IHoCCqBPR+0jdANzABskpiBvABRwoAd3ThoAgJRSAdBBwwAygHklEPAEs4Ac2kBfVjjgBhABZhdvQeUhQp6YgD50fVpgDGxgM45OUWU4cPQByAB04AFpomJiQqXd0Lzhff0DggVtoBMx9QyonIA

**Comment by goodmorninggoaway** [comment] 2020-11-05 19:56
@taysea @ShimiSun are you accepting PRs to fix this, or are you working on it?

**Comment by taysea** [comment] 2020-11-05 20:37
@cscognamiglio, thanks for clarifying your issue. Because DateInput is built using Calendar, I believe this is still and timezone issue rooted in Calendar.

Thanks for reaching out @goodmorninggoaway. I have been working on this, but I do not have a finalized PR. I am hoping to publish a proposed fix by end of next week.

**Comment by maryjufang** [comment] 2021-03-18 01:18
Issue is not fully fixed.
Clicked Feb 1st, still returns Feb 2nd. (User in EST timezone)
![dateOffOneDay](https://user-images.githubusercontent.com/9951106/111558991-25787f80-8766-11eb-814f-1d81a89a5c97.png)

**Comment by goodmorninggoaway** [comment] 2021-03-18 14:26
@taysea I think the problem may be that the user selects a date (not a date+time) in local time, but the value is internally handled and returned as ISO 8601 UTC date+time. The extra precision seems to be what causes the inaccuracy. If it returned simply an ISO-8601 Date (no time, just date), then the consumer can easily choose how they want to interpret it. That change may not be backward-compatible though.

**Comment by taysea** [comment] 2021-03-18 19:00
Thanks @goodmorninggoaway for explaining that. I'm going to take a look into it.

**Comment by taysea** [comment] 2021-03-19 21:52
Hi all @goodmorninggoaway @maryjufang. It appears that Grommet is behaving as it is documented it should (date is returned in ISO 8601 UTC date+time). Given that, in your application you can take the current return value in UTC and convert it back to the user's local timezone. Let me know if all is working correctly with that.

In the future, I imagine a valid enhancement to Calendar would be to allow the caller to specify what timezone format they want the value to be returned in (UTC or local).

**Comment by goodmorninggoaway** [comment] 2021-03-22 14:55
@taysea thanks, it looks correct in storybook - we _may_ be using 2.15.x and it appears this fix went into 2.16.0. Webpack and multiple versions installed, etc.

**Comment by taysea** [comment] 2021-03-22 18:28
Perfect thanks for the update there. I'm going to close this issue for now then.

**Closed by taysea** 2021-03-22 18:28 UTC
Labels: Bug :bug:, hacktoberfest
