### ISSUE TITLE
Clicking on button inside Menu component doesn't work sometime

### ISSUE THREAD

**Issue by nprizal** [grommet/grommet#3556] opened 2019-11-18 22:05 UTC
I'm writing a test for my app using puppeteer, and noticed that sometime it cannot click the button inside `Menu` component. The problem is because when grommet render the menu, sometime it doesn't correctly calculated the width of container, and clicking on the button resize that container instead of trigger the click handler.

### Expected Behavior

Clicking on button inside `Menu` component should trigger the click handler

### Actual Behavior

Clicking on button inside `Menu` component resize the container.

### URL, screen shot, or Codepen exhibiting the issue

https://drive.google.com/file/d/1-tX3MsM41yJMWtJFRY2V6YhVQ94fML4s/view

### Steps to Reproduce
1. Pass `true` to `open` props on `Menu` component
2. Click on button inside the menu

### Your Environment

- Grommet version: 2.7.8
- Browser Name and version: Chrome 78
- Operating System and version (desktop or mobile): macOS Mojave

**Comment by ShimiSun** [comment] 2019-11-19 00:50
It will help us solve/reproduce the problem if you can provide a reliable codepen or codesandbox that reproduces the problem.

**Comment by taysea** [comment] 2019-12-10 22:49
@nprizal I'd love to look into this issue. Can you share a codesandbox link with the code you are using for the Menu?

**Comment by IanKBovard** [comment] 2020-04-17 18:46
@nprizal Can you give us an example of your implementation for us to test before we close this issue? I'm unable to reproduce this bug.

**Comment by ShimiSun** [comment] 2020-05-28 17:40
I'll be closing this issue, feel free to reopen if you have more details to share with us for further investigation.

**Closed by ShimiSun** 2020-05-28 17:40 UTC
Labels: waiting
