### ISSUE TITLE
Resizing a window's width displaying a Layer set to display on the right side causes it to show up on the left

### ISSUE THREAD

**Issue by jesseolsen** [grommet/grommet#4516] opened 2020-09-11 18:23 UTC
When resizing a window's width displaying a Layer set to display on the right side, when the window width is small enough, the form on the right shows up on the left.

### Expected Behavior

Expected behavior is that if the prop says it should be on the right, it would stay on the right, regardless of the width of the window.

### Actual Behavior

It jumps from the right to the left.

### URL, screen shot, or Codepen exhibiting the issue

https://storybook.grommet.io/?path=/story/layer--form

Large width, ok:
![image](https://user-images.githubusercontent.com/6043493/92959557-45329200-f429-11ea-8ee9-dd3d20e459d9.png)

Make the window width smaller, it jumps to the left:
![image](https://user-images.githubusercontent.com/6043493/92959601-5a0f2580-f429-11ea-835e-983b588f8aec.png)

### Steps to Reproduce

1. Navigate to https://storybook.grommet.io/?path=/story/layer--form
2. Click "Add"
3. Note the fly-out form.  It should be on the right side.  If not, make the window bigger until it is.
4. Resize the width of the screen smaller until the form jumps from the right to the left.

### Your Environment

- Grommet version:
v2.15.0

- Browser Name and version:
Chrome latest (Version 85.0.4183.83 (Official Build) (64-bit))

- Operating System and version (desktop or mobile):
Mac laptop

**Comment by halocline** [comment] 2020-09-11 19:07
Documenting for others to follow. In Slack, suggested the following:
- Layer is behaving by design when `responsive={true}` and at 'small' breakpoint. `true` is the default value and causes the Layer to fill the screen (https://v2.grommet.io/layer#responsive)

2 options:
- If the responsive behavior is not desired, set `responsive={false}` in the `<Layer />` which will maintain the right alignment
- If the responsive behavior is desired, then the child contents of the Layer need to have their layouts tweaked via alignment, justification, width, etc. depending on the design.

**Comment by ShimiSun** [comment] 2020-09-14 00:15
@jesseolsen Can we please close this issue if @halocline suggested options worked for you?

**Comment by IanKBovard** [comment] 2020-09-23 16:38
@jesseolsen just checking in to see where you are with this issue.

**Comment by halocline** [comment] 2020-10-06 23:36
I am pretty sure this can be closed per this thread: https://grommet.slack.com/archives/G0170FR7CJU/p1599848695095600

**Comment by IanKBovard** [comment] 2020-10-16 19:31
I agree, it looks like this issue has been resolved.

**Comment by ShimiSun** [comment] 2020-10-20 16:44
Thank you @halocline & @IanKBovard ! Issue closed. Feel free to reopen if still relevant.

**Closed** 2020-10-20 16:44 UTC
Labels: waiting
