### ISSUE TITLE
Grommet fails to run with snowpack

### ISSUE THREAD

**Issue by jeferson-sb** [grommet/grommet#4895] opened 2021-01-24 01:46 UTC
I have a pretty simple application with Grommet, Styled Components and Snowpack installed
But when I start the app I'm getting the following message:

![image](https://user-images.githubusercontent.com/30840709/105618861-d0a23380-5dca-11eb-9298-f7523513a892.png)

I tried to install a different version of styled-components (above 5.1) but it also doesn't work.
Snowpack with styled-components alone seems to work fine though. 

### Expected Behavior

The application should launch without any issues.

### Actual Behavior

I get a `Uncaught TypeError: (0 , _styledComponents.default) is not a function` error message

### URL, screen shot, or Codepen exhibiting the issue

Codesandbox: https://codesandbox.io/s/grommet-snowpack-repro-o3zks

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Microsoft Edge 87
- Operating System and version (desktop or mobile): Desktop Windows 10

**Comment by ShimiSun** [comment] 2021-01-25 20:08
Were you able to make it work with only snowpack & styled-components, to make sure this issue is caused by using grommet?

**Comment by jeferson-sb** [comment] 2021-01-25 22:15
@ShimiSun Yes, it does work with only snowpack & styled-components
I have a example [here](https://codesandbox.io/s/snowpack-styled-components-react-jdx3w?file=/src/components/Button/styles.js)

**Comment by garrettlr** [comment] 2021-01-25 22:34
@ShimiSun @jeferson-sb can also confirm this issue, and that importing styled-components directly works fine.

**Comment by ShimiSun** [comment] 2021-01-26 17:44
> The root cause of the issue is likely that grommet mixes require and import statements improperly:

@garrettlr thanks for the inputs! Do you have any resources to learn about the issue? why did you get the impression it causes the problem?

**Comment by garrettlr** [comment] 2021-01-29 16:46
@ShimiSun give me an hour or two and I'll find a few github posts that helped, but here's my process: 

1. Start up any, react + snowpack app - a simple "hello world" is enough. 
2. Bring in Grommet + dependencies, then import that into your app. 
3. At this point, you should see the above error. 
4. (the magic) pick any random Grommet component, Comment out the 'if' statement from the above snippet, directly import only that file, and it will import properly.

**Comment by wiltsu** [comment] 2021-01-30 17:10
`Uncaught TypeError: (0 , _styledComponents.css) is not a function`
I'm having almost the same issue...

**Comment by rabaut** [comment] 2021-02-05 18:46
Thank you for doing that @garrettlr ! I'll be using your fork until this is fixed.

**Comment by woss** [comment] 2021-04-10 22:46
i'm facing the same thing with snowpack. any update on this?

**Comment by woss** [comment] 2021-04-12 08:05
I also noticed that snowpack bundles the snowpack differently  when i use grommet and when i dont. here is the [gist](https://gist.github.com/woss/aa8c42b795efd010fefd0179aa7a2682) that shows this in action. notice the LAST lines in both files, the issue is that when bundles with grommet it doesn't  have `default` export. i'd say it has to do with the way grommet-icons are built using babel, it's work investigating. 

Note, snowpack runs rollup under the hood

**Comment by jcfilben** [comment] 2021-04-14 22:53
I am looking into this issue, just making a post of my findings so far. 

As @garrettlr pointed out, the require statements for to docs are causing a problem because ESM syntax only uses import and export. Import should be used instead of require and mixing both import and require is generally a bad idea. More info in this article: https://kentcdodds.com/blog/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution. However, using import would mean that the docs are always being loaded even when they are not being used. I am looking into how much of an impact this causes and if there are other solutions.

In addition I think there needs to be changes to the grommet-icons library as well. ESM requires there to be a default export and the way styled components is bundled only uses named exports as @woss pointed out. I am looking at the the .babelrc and webpack.confi.babel.js files in the grommet-icons repo to try and find what needs to be changes so that the styled components will have a default export after it is bundled.

**Comment by ericsoderberghp** [comment] 2021-04-14 23:02
Good notes. Just in case it helps, our longer term direction is to remove the `react-desc` way of documenting within the code and just putting the documentation directly in `grommet-site`. So, if that approach would also address this issue, more reason to head that way sooner. I think we could get there with a day or two's worth of work if we put our minds to it.

**Comment by jcfilben** [comment] 2021-04-14 23:15
Yes, moving the docs to be contained within the grommet-site instead of grommet repo would solve at least the first part of this issue. From what I can tell, the docs are the only thing using `require` statements.

**Comment by jcfilben** [comment] 2021-05-26 20:10
Update:
I tested a grommet component in snowpack with the `require` statement removed and was still getting the same error. The issue is with grommet's dependency grommet-icons which uses styled-components. Styled-components works fine when it is imported directly into a snowpack project but when another package uses it and that package is used with Snowpack it gives an error. This is shown in the following issues: 
https://github.com/snowpackjs/snowpack/issues/2908
https://github.com/snowpackjs/snowpack/discussions/1669#discussioncomment-245508
https://github.com/snowpackjs/snowpack/discussions/2652
https://github.com/snowpackjs/snowpack/discussions/2150

Within the discussion and issue links above a few workarounds were suggested but I was unable to get any of them to work for this case.

If you have a snowpack project with grommet as a dependency, the error is coming from this file:`http://localhost:8080/_snowpack/pkg/grommet-icons.v4.5.0/common/StyledIcon-ca656fb2.js`

This is the line of code that causes the error: `var StyledIcon = (0, _styledComponents["default"])(IconInner).withConfig({`

When grommet-icons is used without grommet, the line of code in the bundled file is: `var StyledIcon = styled__default(IconInner).withConfig({`
^ This does not cause an error

I am not sure what is changing the styledIcon code when it is used within grommet vs when it is just used in grommet-icons

**Comment by woss** [comment] 2021-05-27 08:02
maybe you should rewrite the icons in typescript :)

**Comment by ShimiSun** [comment] 2021-05-28 18:44
@jcfilben Does the combination of snowpack + grommet-icons without grommet works as expected? Testing this use case might help with pinpointing that the issue has indeed resulted from the usage of grommet-icons.

**Comment by jcfilben** [comment] 2021-05-28 19:57
Yes, grommet-icons with snowpack is working as expected. When you use grommet with snowpack the file for grommet-icons changes (changes shown above) and I think that this change is causing the issue

**Comment by jsejcksn** [comment] 2021-06-11 17:51
Hi all: I recently used Grommet and experienced some issues related to ES modules in CodeSandbox. Exploring the stack trace of the errors led me to finding the mixed `import` and `require` statements (as [noted](https://github.com/grommet/grommet/issues/4895#issuecomment-767157892) earlier by Garrett).

I haven't explored Grommet much yet—so I don't have a lot of context for the history of the project—but I'm wondering if this is really more an issue of conforming to the ES module spec. Following that idea, **is there a plan in the works to publish this library in modules that conform to the spec?** It seems important not just to fix the issue with Snowpack, but for any other bundlers which rely exclusively on ES modules. Some bundlers might not even use Node.js (e.g. [Deno](https://deno.land/)).

Assuming a context of Node.js for now, I can think of a couple of ways to provide conditional exports using pure ESM:

- Dynamic import using top-level await:

    Using the Accordion component as an example:
    https://github.com/grommet/grommet/blob/11c3963dc74825f45680919098f6e1aa97d24b2c/src/js/components/Accordion/Accordion.js#L73-L76

    would be replaced with:
    ```ts
    if (process.env.NODE_ENV !== 'production') { 
      AccordionDoc = (await import('./doc.js')).doc(Accordion); 
    }
    ```

    However, even though top-level await is supported by Node [>=14.8](https://nodejs.org/en/blog/release/v14.8.0/), I don't think this pattern is currently supported by React. 😖 Which leads to an alternate idea:

- Conditional exports in `package.json`:

    Node.js endorses the `"development"` and `"production"` [user condition definitions](https://nodejs.org/api/packages.html#packages_conditions_definitions). These can be [nested](https://nodejs.org/api/packages.html#packages_nested_conditions) under `exports.node.import` to declare that there are exclusive entrypoints for each environment, rather than using environment-checking runtime code as branching logic. (Instead, they rely on the bundler to appropriately read and use these export conditions.) This improves both performance and static analysis of the module graph.

    This doesn't prevent including a fallback entrypoint for users of older versions of Node.js which don't support conditional exports. (But it might mean making a choice to only provide the "production" modules in those environments. I'm not positive about this part—I haven't researched that far yet.)

**Comment by jcfilben** [comment] 2021-06-14 22:47
Hi @jsejcksn great comment! I think the issue with snowpack is caused by a combination of using require statements and the way the styled-components dependency in grommet-icons is bundled within grommet. As part of this issue I think that both of these problems need to be fixed. I updated the issue description to include both things as action items.

**Comment by BrianMcBrayer** [comment] 2021-11-19 15:06
Hello. We are also evaluating grommet for a large suite of apps, and this is a blocking issue for us. I don't know if I have the bandwidth to fix it, but are there any suggestions for how I can help move this along?

**Comment by jcfilben** [comment] 2021-12-02 22:31
I have published a sample repository that shows a workaround to use Grommet with Snowpack. The [readme.md](https://github.com/jcfilben/grommet-with-snowpack/blob/master/README.md) file includes more details about the workaround and what it is accomplishing.
https://github.com/jcfilben/grommet-with-snowpack

**Comment by jcfilben** [comment] 2021-12-03 18:20
Hi everyone, I am going to go ahead and close this issue since we have a workaround. Feel free to reach out if there are any more issues or questions about using the workaround.

**Closed by jcfilben** 2021-12-03 18:20 UTC
Labels: bug
