### ISSUE TITLE
DataChart may break randomly when axis.x.granularity is medium

### ISSUE THREAD

**Issue by b1f6c1c4** [grommet/grommet#4602] opened 2020-10-13 00:56 UTC
### Expected Behavior

When `axis={{ x: { granularity: "medium" } }}` is given, the `DataChart` shall pick some X values and label them no matter how many data points are given.

### Actual Behavior

However if the number of elements equals to some weird number (I can't see any pattern here) the following error ococurs:
(Suppose `dt` contains property of X value.)
```
Cannot read property 'dt' of undefined
```

### URL, screen shot, or Codepen exhibiting the issue

Please kindly give it a look at https://codesandbox.io/s/grommet-v2-template-forked-wyw03?file=/index.js
**and try to modify the `NUM_DATA`.**

### Steps to Reproduce

You just write the same code as the codesandbox link.

### Your Environment

- Grommet version: 2.15.1
- Browser Name and version: Version 86.0.4240.75 (Official Build) Arch Linux (64-bit)
- Operating System and version (desktop or mobile): Linux 5.8.14 x86_64 GNU/Linux

**Comment by ShimiSun** [comment] 2020-10-20 20:33
The issue is fixed on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) and will be released on our next official release. Thank you for reporting!

**Closed by ShimiSun** 2020-10-20 20:33 UTC
Labels: in progress
