### ISSUE TITLE
Add `disabled` prop to <Button /> Component

### ISSUE THREAD

**Issue by Sitch** [grommet/grommet#1681] opened 2017-10-16 15:36 UTC
### Expected Behavior

`<Button disabled={true} />` should disable the component regardless of onClick/path

### Actual Behavior

nothing

* Grommet version: 1.7
* Browser Name and version: any
* Operating System and version (desktop or mobile): osx/linux

**Comment by milanvdmria** [comment] 2017-10-17 13:01
https://github.com/grommet/grommet/issues/1558

**Comment by drewlustro** [comment] 2017-10-24 03:06
This is unfortunately by design of Grommet 1.x; apparently it will be fixed in 2.0

**Comment by L0ZZI** [comment] 2018-01-30 15:57
Correct!

**Closed** 2018-01-30 15:58 UTC
