### ISSUE TITLE
[TS] Text Input Prop is missing type prop

### ISSUE THREAD

**Issue by babbarankit** [grommet/grommet#4522] opened 2020-09-15 11:15 UTC
### Expected Behavior

Text Input Prop must have type prop

**Comment by ShimiSun** [comment] 2020-09-15 18:06
As I commented on the PR, we try not to document props that are not part of the grommet API and keep the default of the HTML documentation and types. type isn't part of the grommet API hence we do not document it or add typing to it. Any reason you think this addition is useful? Is it currently not working?

**Comment by babbarankit** [comment] 2020-09-15 18:58
Hi @ShimiSun 
Thanks for reaching out so quickly. The use case is very  simple, I have constructed new Form Components using the TextInput, extended as PasswordInput or EmailInput. 
Unless I pass the prop to TextInput for type, how will it behave as HTML5 element. HTML5 prop must be passed to TextInput.
Currently I am using Patch Package otherwise Typescript complaints on passing extra type prop to TextInput.

**Comment by ShimiSun** [comment] 2020-09-15 20:12
@babbarankit I've built a quick markup that uses TypeScript+Grommet+TextInput with the `type` prop and it doesn't reproduce the issue, https://codesandbox.io/s/grommet-ts-textinput-type-nez6b?file=/src/index.tsx.
Feel free to tweak the example as you see fit to reproduce the problem so we can reproduce it reliably on the grommet side before attempting to fix it.

**Comment by ShimiSun** [comment] 2020-10-02 15:59
Interesting discussion on the PR #4523

**Comment by jcfilben** [comment] 2021-09-16 18:45
Closing since we were unable to reproduce the issue. Feel free to reopen with a code example.

**Closed by jcfilben** 2021-09-16 18:45 UTC
Labels: waiting
