### ISSUE TITLE
The select items are keep shaking

### ISSUE THREAD

**Issue by withpublic** [grommet/grommet#6455] opened 2022-10-26 12:35 UTC
### Expected Behavior
I select an item and this item is selected

### Actual Behavior
Instead the values are keep shaking not allowing to select

### URL, screen shot, or Codepen exhibiting the issue
I shall add a video

### Steps to Reproduce
Open a Select component and try to select an item

### Your Environment

- Grommet ver

https://user-images.githubusercontent.com/99742304/198027445-a02b8270-7e44-44a0-a920-a5681db4ca91.mp4

sion: 2.27.0
- Browser Name and version: Edge, Chrome, latest version
- Operating System and version (desktop or mobile): Server is Ubuntu OS

**Comment by jcfilben** [comment] 2022-11-09 19:40
Closing since we have not been able to reproduce this issue. Feel free to re-open the issue with a codesandbox that demonstrates the behavior.

**Closed by jcfilben** 2022-11-09 19:40 UTC
Labels: waiting
