### ISSUE TITLE
X overlay on search input in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#143] opened 2015-08-10 19:45 UTC
in IE11 there is a x overlay to clear (from the browser) that is unclickable, and overlaps the search icon.

![ie11 - x overlay on search](https://cloud.githubusercontent.com/assets/13527666/9182066/bcdac1ac-3f65-11e5-8de9-fbc07ede6af2.png)

**Comment by kylebyerly-hp** [comment] 2015-11-10 23:44
I believe this is fixed

**Comment by ericsoderberghp** [comment] 2016-02-25 05:48
Cannot reproduce anymore.

**Comment by kylebyerly-hp** [comment] 2016-02-25 17:24
Not quite in all cases.
http://www.grommet.io/docs/develop/searchinput
![image](https://cloud.githubusercontent.com/assets/13527666/13328064/e9920b34-dba9-11e5-9b91-38d26064f07d.png)

Click into the SearchInput and you'll see the x appear.

Also 
http://www.grommet.io/docs/develop/search
![image](https://cloud.githubusercontent.com/assets/13527666/13328078/f9c3fe36-dba9-11e5-8b91-bbcf93ec8d40.png)

clicking into the search field and entering data reveals the x.

**Comment by ericsoderberghp** [comment] 2016-02-25 23:56
This is only an issue with IE11. Cannot reproduce on Edge 13.

**Comment by ericsoderberghp** [comment] 2016-02-26 00:49
Fixed in c1b7afd01e5405496c86a4da41102f9e4ecf510c.

**Closed by ericsoderberghp** 2016-02-26 00:49 UTC
Labels: in progress
