### ISSUE TITLE
Default button is causing issues on components that use Button 

### ISSUE THREAD

**Issue by britt6612** [grommet/grommet#4077] opened 2020-05-13 19:26 UTC
With the new changes that were done to `Button` and default this is now effecting other components in which use `Button` under the hood to made up that component
### Expected Behavior
I would expect that if I had certain properties defined in theme for `default button` these would not effect the components that are should be using plain button under the hood.

### Actual Behavior
When you have in your theme 

```
  button: {
    default: {
      color: 'text',
      border: undefined,
      padding: {
        horizontal: '12px',
        vertical: '6px',
      },
    },
```
This will also effect the padding in `accordion` and `select` since these components are using `button` there is unnecessary pad now in which the user would want the plain button to still be used in `accordion`

### Steps to Reproduce

Currently there is a theme story for accordion if you make sure you have the latest master changes and `grommet-theme-hpe-next` changes you will see the hover behavior and the extra padding of 12px horizontal and 6px vertical. 

In `accordionpanel.js` `Button` is being used on line 90 and so if you set that `button` prop plain then that will fix the issue.

I would assume that we would want to ignore these default props given to button if they are being used inside other components. 

### Your Environment

- Grommet version: [Shimi] stable branch
- Browser Name and version: [Shimi] any
- Operating System and version (desktop or mobile): [Shimi] any

**Comment by britt6612** [comment] 2020-05-13 19:27
adding @halocline comment from Slack thread 

Basically, any components that use Button in their implementations are receiving excess padding (as defined by default in the theme), and also receiving the wrong hover background color (switching light/dark styling).

Menu is another example: https://design-system.hpe.design/components/menu

**Comment by britt6612** [comment] 2020-05-18 21:35
After some exploration: 

After looking at menu and accordion in the design system I found that with adding the plain prop now to these when default button is in the theme the text color in dark is not correct. 

https://design-system.hpe.design/components/accordion
![Screen Shot 2020-05-18 at 3 34 28 PM](https://user-images.githubusercontent.com/42451602/82261881-14c86480-991d-11ea-9928-c034fe824684.png)

https://design-system.hpe.design/components/menu

![Screen Shot 2020-05-18 at 3 34 50 PM](https://user-images.githubusercontent.com/42451602/82261904-2447ad80-991d-11ea-9d91-e4bddf2fd505.png)

* The text color on these should be white in dark mode

**Comment by halocline** [comment] 2020-05-26 23:45
Additional related issues: https://github.com/hpe-design/design-system/issues/770, https://github.com/hpe-design/design-system/issues/771

**Comment by ShimiSun** [comment] 2020-05-27 00:07
@halocline are you linking the issue because you think the fix should be applied on the grommet side rather than the design-system?

**Comment by halocline** [comment] 2020-05-27 15:21
> @halocline are you linking the issue because you think the fix should be applied on the grommet side rather than the design-system?

Yes, sorry for the confusion. In #770 above, the text color of the selected value is displaying `text.light` instead of `text.dark`. This is similar to the accordion and menu screenshots above where the background color seems to be misinterpreted.

In #771 above, each option box is receiving the Default Button styling including padding and rounding (undesired in this case). The theme interface for modifying Select option box allows for styling the inner content, but not the padding, border, and border-radius. This is most easily seen in the issue's screen shot with the drop open and a value selected.

**Comment by britt6612** [comment] 2020-05-27 17:42
Text color in #770 should be fixed with this current PR thats open 
https://github.com/grommet/grommet/pull/4099

**Comment by ShimiSun** [comment] 2020-06-01 16:24
A fix for this issue is now available on the stable branch, let us know if you need us to address anything else in this area.

**Comment by britt6612** [comment] 2020-06-01 16:28
@ShimiSun thank you do you want me to close my PR ?

**Comment by ShimiSun** [comment] 2020-06-01 16:57
@britt6612, UI think that if the problem is fixed on the stable than the PR could be closed.

**Comment by britt6612** [comment] 2020-06-25 21:33
@ShimiSun this can be close

**Closed** 2020-06-25 22:28 UTC
Labels: in progress, waiting
