### ISSUE TITLE
Showing Layer causes content to jitter as scrollbar disappears/re-appears

### ISSUE THREAD

**Issue by adamazing** [grommet/grommet#3444] opened 2019-10-08 20:43 UTC
When showing a Layer component, it sets `overflow: hidden` style on the body which causes the scrollbar (if any) to disappear and content on the page moves. 

### Expected Behavior

Content on the page should not jitter back and forth as the scrollbar disappears/reappears. 

### Actual Behavior

When the scrollbar disappears, content on the page shifts right.
When the scrollbar re-appears (when Layer closes), content shifts back

### URL, screen shot, or Codepen exhibiting the issue

Issue can be seen here: 
 https://v2.grommet.io/layer

And on this codesandbox example: 
 https://csr49.csb.app/

Video: 
https://www.youtube.com/watch?v=ynXL6STkol8

### Steps to Reproduce

1. Go to either of the above links on any desktop browser 
2. Ensure the content has forced a scrollbar to appear 
3. Show the modal/layer by clicking the button
4. See the page content shift right.
5. Hide the modal/layer
6. See the page content shift back

### Your Environment

- Grommet version: 2.7.9
- Browser Name and version: Safari (latest), Chrome (latest), Firefox (latest)
- Operating System and version (desktop or mobile): macOS Mojave

### Possible fix?
Add padding equal to the scrollbar (if any) to the body along with overflow: hidden?

```Javascript
const bodyPadding = window.innerWidth - document.documentElement.clientWidth;
```

**Comment by ShimiSun** [comment] 2019-10-08 20:52
Interesting I'm not able to reproduce it on my Mac, Chrome, can you please record a quick video so I'll see the behavior?
More important, on your codesandbox, can you change your grommet version to 2.7.1 and let me know if it reproduces there? I want to eliminate the option that this issue is a regression.

**Comment by adamazing** [comment] 2019-10-08 21:11
Not sure if this is why you're having trouble reproducing, but the content has to be scrollable to see the effect and it's subtle:
https://www.youtube.com/watch?v=ynXL6STkol8

Adding `full={true}` to the Grommet container leaves the scrollbar intact, mitigating the issue:
https://h0klz.csb.app/
https://youtu.be/8Nt3FqwBvS8

v2.7.1: 
https://vwmql.csb.app/
https://youtu.be/ZmcmGUyMkKY

**Comment by adamazing** [comment] 2019-10-10 08:48
> Interesting I'm not able to reproduce it on my Mac, Chrome

Dang it! I've just been looking at this at home @ShimiSun, without a mouse plugged in (as I usually have at work) and realised that the scroll-bars disappear when not actively scrolling! It's possible to force them to always show in `System Preferences > General > Show scroll bars > Always`. Hope this helps!

<img width="668" alt="Screen Shot 2019-10-10 at 9 43 32 PM" src="https://user-images.githubusercontent.com/2782959/66553304-58006f00-eba7-11e9-9291-6e4b9196878c.png">

**Comment by oorestisime** [comment] 2019-11-15 18:27
Agreed on this. been hit by this as well. maybe the solution is to add `overlfow: auto`  what do you think @adamazing

**Comment by adamazing** [comment] 2019-11-24 23:58
@oorestisime I think it depends on your use-case. For a lot of people, the expectation of a modal (which is what we're using Layer for) is that it takes over the whole screen and prohibits scrolling of the background content (which I think `overflow: auto` would permit)?

**Comment by stephanis1494** [comment] 2020-05-28 18:05
Any update on this issue? I am unable to have a modal on top of another modal due to this bug, haven't really been able to find a viable work around for it either :/

**Comment by IanKBovard** [comment] 2020-09-29 16:06
I no longer see this issue in the current version of grommet. The scrollbar remains. checked safari and chrome.

**Comment by ShimiSun** [comment] 2020-10-02 03:09
Verified that the issue is no longer reproducible on grommet version 2.15.0 as @IanKBovard noted.
I'll be closing this issue, feel free to reopen if still relevant.

**Closed by ShimiSun** 2020-10-02 03:09 UTC
