### ISSUE TITLE
Select in Form not working properly in 2.11.0

### ISSUE THREAD

**Issue by mlonn** [grommet/grommet#3772] opened 2020-02-21 12:07 UTC
The Selected value does not get selected

### Expected Behavior

The selected value should be selected
### Actual Behavior

The Selected value does not get selected

### Steps to Reproduce

1. https://codesandbox.io/s/form-issue-mzb5r 
1. Select a value, it doesn't save
1.  Change the version of grommet to 2.10.0
1. Select a value. now it does save.

### Your Environment

- Grommet version:
    2.11.0
- Browser Name and version:
    Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Operating System and version (desktop or mobile):
    macOS catalina  10.15.3

**Comment by ShimiSun** [comment] 2020-02-21 16:22
Thanks for reporting!

**Comment by copperwall** [comment] 2020-02-21 20:07
I took a shot at fixing this, but it looks like the `setValue` functionality was removed a week or two ago so I'm happy to change the fix if it's not quite right. I left a little more context on the PR #3773

**Comment by ShimiSun** [comment] 2020-02-21 20:51
Hi buddy, thanks again for the prompt report of the issue, I'll release a hotfix 2.11.1 to include this fix.
In the meanwhile the issue is fixed on the stable branch, so you can point your grommet package.json to "https://github.com/grommet/grommet/tarball/stable" instead of 2.11.0 and it should work.

**Comment by ShimiSun** [comment] 2020-02-22 14:37
Released officially on grommet v2.11.1, let us know if we can help with anything else. https://github.com/grommet/grommet/releases/tag/v2.11.1

**Closed by ShimiSun** 2020-02-22 14:37 UTC
Labels: Bug :bug:

**Comment by mlonn** [comment] 2020-02-24 06:31
Thanks for the quick response 😊
