### ISSUE TITLE
remove x on Search and SearchInput in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#251] opened 2015-11-10 23:43 UTC
Need to add the following to get rid of the clear x in IE. This was already done for form-field inputs.

```
<clazz>::-ms-clear {
    display: none;
}
```

May be worth abstracting out so all input types get this

**Comment by ericsoderberghp** [comment] 2016-02-25 23:55
This is only an issue with IE11. Cannot reproduce on Edge 13.

**Comment by ericsoderberghp** [comment] 2016-02-26 00:45
Duplicate of issues #143

**Closed by ericsoderberghp** 2016-02-26 00:45 UTC
Labels: in progress
