### ISSUE TITLE
Theme's `formField.border.size: "all"` and `formField.error.background.opacity: "weak"` are not supported by TypeScript

### ISSUE THREAD

**Issue by mcorrig4** [grommet/grommet#5401] opened 2021-06-29 19:22 UTC
I am using grommet in a TypeScript project. When I follow the storybook [Form - Custom](https://storybook.grommet.io/?path=/story/input-form-custom--custom) I get type errors.

### Expected Behavior

Project will build.

### Actual Behavior

`border.side` error
```node
TypeScript error in X:/win10/repos/pharmdx-app/src/App.tsx(59,29):
Type 'DeepReadonly<{ menu: { icons: { down: Icon; up: Icon; }; }; global: { colors: { brand: string; "accent-1": string; text: { light: string; focus: string; }; }; breakpoints: { xsmall: { value: number; }; small: { value: number; }; medium: undefined; middle: { ...; }; }; ... 4 more ...; input: { 
...; }; }; formField: {...' is not assignable to type 'ThemeType'.
  The types of 'formField.border' are incompatible between these types.
    Type 'DeepReadonly<{ position: string; side: string; }>' is not assignable to type '(BorderType & { error?: { color?: ColorType; } | undefined; }) | undefined'.
      Type 'DeepReadonly<{ position: string; side: string; }>' is not assignable to type '{ color?: ColorType; error?: { color?: ColorType; } | undefined; position?: string | undefined; side?: BoxSideType | undefined; size?: string | undefined; style?: BoxStyleType | undefined; } & { ...; }'.       
        Type 'DeepReadonly<{ position: string; side: string; }>' is not assignable to type '{ color?: ColorType; error?: { color?: ColorType; } | undefined; position?: string | undefined; side?: BoxSideType | undefined; size?: string | undefined; style?: BoxStyleType | undefined; }'.
          Types of property 'side' are incompatible.
            Type 'string' is not assignable to type 'BoxSideType | undefined'.  TS2322
```

`error.background.opacity` error
```node
Type 'DeepReadonly<{ menu: { icons: { down: Icon; up: Icon; }; }; global: { colors: { brand: string; "accent-1": string; text: { light: string; focus: string; }; }; breakpoints: { xsmall: { value: number; }; small: { value: number; }; medium: undefined; middle: { ...; }; }; ... 4 more ...; input: { 
...; }; }; formField: {...' is not assignable to type 'ThemeType'.
  The types of 'formField.error.background' are incompatible between these types.
    Type 'DeepReadonly<{ color: string; opacity: string; }>' is not assignable to type 'BackgroundType | undefined'.
      Type 'DeepReadonly<{ color: string; opacity: string; }>' is not assignable to type '{ color?: ColorType; dark?: string | boolean | undefined; image?: string | undefined; position?: string | undefined; opacity?: number | boolean | "weak" | "medium" | "strong" | undefined; repeat?: string | undefined; size?: string | undefined; light?: string | undefined; }'.
        Types of property 'opacity' are incompatible.
          Type 'string' is not assignable to type 'number | boolean | "weak" | "medium" | "strong" | undefined'.  TS2322
```
It is very strange because it says 'string' not compatible with ... |"weak"|...
I've also checked BoxSideType and "all" is a valid part of the union type.

### Steps to Reproduce

Add the following to the theme:
```typescript
  formField: {
    border: {
      side: "all",
    },
    error: {
      background: {
        opacity: "weak",
      },
    },
```

### Your Environment

- Grommet version: 2.17.3
- Typescript 4.3.2

**Comment by britt6612** [comment] 2021-07-01 21:24
@mcorrig4 I was playing around with this in a codesandbox and was not able to recreate the issue can you look at what I made and see if there was something else you had ? 

https://codesandbox.io/s/grommet-ts-textinput-type-forked-pslg2?file=/src/index.tsx

Let me know if you were doing it another way and I can look more into the issue once I'm able to recreate the bug 👍

**Comment by jcfilben** [comment] 2021-07-07 19:56
I was unable to reproduce this as well. I used the code from the Form/Custom story and didn't see any typescript errors: [codesandbox](https://codesandbox.io/s/grommet-ts-textinput-type-forked-s286r?file=/src/index.tsx). @mcorrig4 can you check that you are using the latest version of grommet? If you are using the latest version can you share a codesandbox that reproduces the error?

**Comment by jcfilben** [comment] 2021-09-16 18:15
Closing since we were unable to reproduce the issue. Feel free to reopen and share a code sandbox demonstrating the issue.

**Closed by jcfilben** 2021-09-16 18:15 UTC
Labels: waiting, bug
