### ISSUE TITLE
App content scrolling to top when displaying Layer

### ISSUE THREAD

**Issue by snaemi** [grommet/grommet#1315] opened 2017-04-18 19:38 UTC
I attempted to search the issue list, but did not find anything specific to what I'm experiencing.

When displaying a Layer, the App content scrolls to the top. I'm not sure if this is expected behavior, but a user can lose some details that were otherwise visible through the overlay. I'd like to know if there is a way to prevent this from happening.

### Expected Behavior
Content does not scroll to top and instead stays at the scroll position prior to displaying the Layer. In my given situation, I am aligning the Layer to the right so that most of the content is still visible to the user. It would be nice to keep the scroll position at where it is so I don't have to fill the Layer with details of that particular section.

### Actual Behavior
Content scrolls to the top when the Layer is displayed.

### URL, screen shot, or Codepen exhibiting the issue
Here is a Codepen with a brief sample of the issue: https://codepen.io/snaemi/pen/rmOomo?&editors=0010

### Steps to Reproduce
 1. Click the Codepen and scroll down to the middle of the Accordion
 2. Expand one of the AccordionPanels, then scroll down to the 'Show Layer' button and click it.
 3. A Layer will be displayed and the content behind the Layer will scroll to the top of the page.
 4. Closing the Layer will move the scroll position back to its original location.

### Your Environment
* Grommet version: 1.2.1
* Browser Name and version: Chrome 57.0.2987.133
* Operating System and version (desktop or mobile): Windows 10, 64-bit

**Comment by alansouzati** [comment] 2017-06-07 20:53
This is the expect behavior. We scroll to the top because we set the focus inside the layer for accessibility reasons. When you close the layer the focus should return to the original element.

Users that have low visibility will not be able to see what is behind the layer, so relying on that is dangerous. If you need to show some information when a "Layer" is opened, I would recommend using a "Sidebar" where the content will be pushed to left instead of floating on top of the content.

Hopefully it makes sense.

I'm closing this issue since I believe this is the expected behavior. let me know if you need help converting a layer to a sidebar.

I'm pretty much available on Slack: http://slackin.grommet.io

**Closed by alansouzati** 2017-06-07 20:53 UTC
Labels: needs attention
