### ISSUE TITLE
<Menu/> throws error when opened and window is resized

### ISSUE THREAD

**Issue by linde12** [grommet/grommet#1284] opened 2017-04-03 09:13 UTC
The `<Menu/>` component throws exceptions when the menu is opened and the user resizes the window.

### Side effects
Sometimes(seems to somehow be related to how many exceptions are thrown) the popup becomes "unclickable"(when clicking the popup it disappears but the content isn't clicked)
E.g. if i have an `<Anchor/>` inside the popup and click it, it won't fire it's `onClick` callback

### Expected Behavior
When resizing the browser window, `<Menu/>` component should work as usual, without throwing exceptions or causing the unwanted side effects described above.

### Actual Behavior
When resizing the browser window, `<Menu/>` throws errors and sometimes makes content "unclickable".

### URL, screen shot, or Codepen exhibiting the issue

The exceptions are not shown in the demo below, but the side effects are still there:
http://codepen.io/anon/pen/zZeXXG?editors=0010

### Steps to Reproduce
 1. Create a Menu containing an `<Anchor/>` with a `onClick` callback that just does an `alert()` as per the codepen demo
 2. Click the dropdown below
 3. Resize the browser window and/or chrome devtools window
 4. Click the "Click me" anchor within the dropdown.
 5. Observe that nothing happens, and if you repeat the steps but skip step 2 you will see an alert

### Your Environment
I'm using awesome WM which is a tiling window manager so i can't really resize as you would normally in e.g. Gnome/KDE or how you would do in Windows, but the errors are thrown when i tile-resize it and when i resize the devtools window. I doubt this should have anything to do with the issue however.

* Grommet version: 1.2.1
* Browser Name and version: Google Chrome	54.0.2840.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Debian GNU/Linux 8.2 (jessie)

**Comment by linde12** [comment] 2017-04-03 10:59
By the way, if you can't reproduce it, the console error i'm getting is:
```
DOM.js line 45: Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at findScrollParents (eval at <anonymous> (http://localhost:8000/main.js:6373:2), <anonymous>:45:23)
    at Drop._onResize (eval at <anonymous> (http://localhost:8000/main.js:6535:2), <anonymous>:281:58)findScrollParents @ DOM.js?fa49:45_onResize @ Drop.js?315c:281
```

**Comment by alansouzati** [comment] 2017-07-08 00:17
I believe this is fixed. I remember pushing a fix for this. I've tested and I cannot reproduce it. I'm closing it for now. feel free to reopen if you can still reproduce it. If I'm not mistaken this is already present in Grommet 1.5.0

**Closed by alansouzati** 2017-07-08 00:17 UTC
Labels: needs attention
