### ISSUE TITLE
Cannot set target prop on Anchor

### ISSUE THREAD

**Issue by arvind0598** [grommet/grommet#3975] opened 2020-04-18 14:08 UTC
### Expected Behavior

`
<Anchor
            href="/hello"
            target="_blank"
            label="here"
          />
`

This should set the link to open in a new tab, with the target prop.

### Actual Behavior

`<a href="/hello" class="StyledAnchor-sc-1rp7lwl-0 gzrmWK">here</a>`

This is the generated HTML. It creates the HTML without the target prop.

### Steps to Reproduce

Use the code in the first section.

### Your Environment

- Grommet version: 2.11.2
- Browser Name and version: Firefox 75.0
- Operating System and version (desktop or mobile): Ubuntu 18.04.3

**Comment by IanKBovard** [comment] 2020-04-20 18:11
@arvind0598 Have you tried testing if the anchor opens in a new window? Although, you might not see it, with the current version of grommet im able to set target="_blank" effectively.

**Comment by arvind0598** [comment] 2020-04-21 05:40
> @arvind0598 Have you tried testing if the anchor opens in a new window? Although, you might not see it, with the current version of grommet im able to set target="_blank" effectively.

Yeah I have. It wasn’t working for me. After that I checked the HTML and saw there was no prop for it. 

I’m not sure if it’s more buggy or less buggy if it’s opening a link in a new tab without having a target prop in the HTML, haha.

**Comment by ShimiSun** [comment] 2020-04-21 16:53
@arvind0598 I think the thought was to keep the DOM lean, wondering why you think it should be shown on the DOM.

**Comment by IanKBovard** [comment] 2020-04-21 20:23
@arvind0598 are you still having issues? I can set target="_blank" on an Anchor component successfully. I've tested this multiple times.

**Comment by ShimiSun** [comment] 2020-04-21 21:01
after discussion, we should allow target on the DOM element, and we'll need to investigate why it is not showing now. @IanKBovard would you like to take a look at it?

**Comment by IanKBovard** [comment] 2020-04-21 22:15
@ShimiSun can do

**Comment by IanKBovard** [comment] 2020-04-23 17:43
have a pr up for this in review

**Comment by IanKBovard** [comment] 2020-07-07 14:26
target prop is visible in latest version of grommet. 
![Screen Shot 2020-07-07 at 9 26 31 AM](https://user-images.githubusercontent.com/21990914/86796207-f84ecb80-c033-11ea-8d63-84708db6d971.png)

issue can be closed

**Comment by ShimiSun** [comment] 2020-07-07 14:41
@arvind0598 can you please confirm the issue is fixed on grommet v2.14.0?

**Comment by IanKBovard** [comment] 2020-07-07 15:30
im able to see the target in the dom in the latest version of grommet

**Comment by ShimiSun** [comment] 2020-07-07 22:26
I'll be closing this issue then. Feel free to reopen or file a new issue if needed. Thanks for reporting!

**Closed** 2020-07-07 22:26 UTC
