### ISSUE TITLE
[Select] Remove border radius on both drop and button on the side where the drop is open

### ISSUE THREAD

**Issue by sradevski** [grommet/grommet#3156] opened 2019-06-13 08:44 UTC
If both the Select button and the drop have a border radius, when the drop is open it looks better if the border radius on both the button and drop are removed so the button and drop appear as one piece.

### Expected Behavior
![Screen Shot 2019-06-13 at 10 41 50 AM](https://user-images.githubusercontent.com/4820812/59417754-195cd280-8dc8-11e9-91c7-469cc0c240c7.png)

### Actual Behavior
![Screen Shot 2019-06-13 at 10 40 51 AM](https://user-images.githubusercontent.com/4820812/59417764-1cf05980-8dc8-11e9-9089-41cc58f2f26f.png)

It can be controlled through a prop if it is not desired by everyone, with opt-out being the default.

**Comment by oorestisime** [comment] 2019-06-14 18:55
@L0ZZI @JetLim would love your input here!

**Comment by L0ZZI** [comment] 2019-06-26 17:15
I would suggest removing the radius all together or just ensure there is more space between the drop and the button. Customizing the radius on interaction could cause a little hiccup on the interactions transition. Thoughts?

**Comment by ShimiSun** [comment] 2019-07-22 23:33
@L0ZZI , by
>...or just ensure there is more space between the drop and the button

Do you mean like a pixel or two?

**Comment by ShimiSun** [comment] 2019-07-24 18:48
Sharing our discussion resolutions:
1. The suggested `Expected Behavior` might look better on the corners, but the fact the drop isn't using the stroke on the drop while the drop looks like the extension of the Select, also doesn't look well.
2. If we will apply customized borders we should think of a few use cases:
 a. The drop can open from the top or button (depends on resolution and position), so the selection of the corners may vary.
 b. The logic should apply on/off opening the select box.
3. Following @lozzi comment, we may allow a customized margin space between the Select & Drop using select.control.open theme instead of applying the corners solution, but the margin should apply on the Drop and not on the Select, since the layout near the margin may bounce as you open the Drop. also, we should consider 2.a. for the margin position (top/bottom).

This is our suggestions in case there are volunteers for picking the issue, or in case you'd like to continue brainstorming with us :)

**Comment by sradevski** [comment] 2019-07-25 07:54
Thanks all for looking into this, I appreciate it! As you mentioned, the drop not having a stroke doesn't look as good. Actually, in our designs, the drop also has a stroke, which makes it look much better. 

I think one of the main challenges is also making it look good with the animation of the drop (since it animates diagonally), so that should be considered as well. I will check it out this weekend and see if we can get a reliably good styling while covering all of the situations you have mentioned.

**Comment by ShimiSun** [comment] 2019-07-29 15:45
@sradevski can you share with me your design, also with the animation part you mentioned? I'm curious to see how we could help your team. 
Feel free to send me a direct message on slack if the design is restricted.

**Comment by sradevski** [comment] 2019-08-12 07:37
@ShimiSun missed the ping, sorry about that. The animation I was referring to is the one currently grommet uses, as shown [here](https://v2.grommet.io/select). If we were to make the corners lose their radius when the Select is open, while animating it might require animation on the border radius as well for it to look smooth. Anyhow, the animation is not an issue at all, as we can also simply disable it.

The Select from our designs looks like this when opened:
![Screen Shot 2019-08-12 at 9 32 02 AM](https://user-images.githubusercontent.com/4820812/62850790-5a983280-bce4-11e9-9ee4-41313534e55e.png)

I just opened this issue cause I think Grommet can benefit from it as well, but it is by no means a blocker for us. If you feel like this is not a change you want to make in Grommet, feel free to close the issue.

**Comment by ShimiSun** [comment] 2019-08-13 05:45
@sradevski thank you for bringing it up to us buddy! 
we are always interested in feedback and ideas to make sure we are considering all options for the grommet components. we'll definitely discuss it.

**Comment by jcfilben** [comment] 2021-12-17 00:03
Hi @sradevski I'm going to go ahead and close this since there hasn't been any recent interest/activity on it. If you are still interested in seeing this added feel free to reopen.

**Closed by jcfilben** 2021-12-17 00:03 UTC
Labels: enhancement, discussion
