### ISSUE TITLE
Tile data gets overlapped/hidden 

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1554] opened 2017-08-10 05:31 UTC
When we use tile, data gets overlapped/hidden
### Expected Behavior

Based on the data tile height should be calculated
### Actual Behavior

Data gets hidden/overlapped
### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/nikitam/pen/jLmowQ?editors=0110

### Steps to Reproduce
 1. Use codepen
 2. 
 3. 

### Your Environment

* Grommet version:1.5.0
* Browser Name and version: IE 11
* Operating System and version (desktop or mobile): Windows, desktop

**Comment by dgennetten** [comment] 2017-08-10 16:13
Identical overlapped/hidden results also occur in Safari

**Comment by karatechops** [comment] 2017-09-01 19:28
@dgennetten @agrawalPratik This is a pretty classic Flexbox bug and actually not so much a Grommet issue but more of a browser CSS interpolation issue. IE11 and Safari require some Grommet Boxes to be wrapped in a row to process their height. I've provided a [code pen](https://codepen.io/karatechops/pen/gxqeRM?editors=0010) here which fixes the issue just by using Grommet Box composition - notice the Boxes whose height was not being calculated correctly are now wrapped in rows. 

This would be a really tough issue to fix within Grommet. If you check out this [code pen](https://codepen.io/karatechops/pen/VzgXOa?editors=0110) I fixed the issue using the style prop on the Boxes whose height is not being calculated properly. The issue is the Box requires the css property `flex: 1 0 auto;`.

As the row nesting codepen provides a fix I'm going to close this for now. Feel free to reopen if this does not solve your problem.

**Closed by karatechops** 2017-09-01 19:28 UTC
