### ISSUE TITLE
Tiles 'onMore' event not triggered in small display

### ISSUE THREAD

**Issue by EJShim** [grommet/grommet#1559] opened 2017-08-16 06:04 UTC
I implemented a list of tiles using Tiles and Tile components provided here.
 I added "onMore" property to the  Tiles component, and it works fine in bigger display in desktop, but it is not triggered in a small display (mobile display). 

below link is the example I implemented
[http://ejblog.azurewebsites.net/video](http://ejblog.azurewebsites.net/video)
In a large display, when I scroll down and reach the bottom of the page, "onMore" event is triggered, and more contents are generated, but if I reduce the screen size to mobile, the event is not triggered. 

### Environment
* Grommet version: Newest
* Browser Name and version: Chrome(Desktop), Safari, Chrome(Mobile)
* Operating System and version (desktop or mobile): Both

**Comment by karatechops** [comment] 2017-09-01 20:06
Hey @EJShim, would you mind providing a [codepen](http://codepen.io/pen?template=gaEGPY&editors=001) for this? I'm not able to reproduce this as the [grommet docs tiles on more](https://grommet.github.io/docs/tiles/examples/?onMore=func) work well on mobile.

**Comment by karatechops** [comment] 2017-09-12 15:59
As a Codepen has not been submitted for this issue and I can not replicate it in my sandbox I'll be closing this issue. @EJShim feel free to reopen this once a Codepen is created so I can further investigate the issue.

**Closed by karatechops** 2017-09-12 15:59 UTC
