### ISSUE TITLE
V2 Select-Unable to add ids to the options

### ISSUE THREAD

**Issue by tharunhpe** [grommet/grommet#3254] opened 2019-08-06 10:19 UTC
### Expected Behavior

After i pass object like: {[ id: '123', label: 'abc', value: 'abc' ]}
When i inspect on the dropdown on click on Select, the rendered buttons should have the ID.

### Actual Behavior

When i inspect on the dropdown on click on Select, the rendered buttons dont have the ID.

Code Error:

All the props are not being passed from objects from parent of button: https://github.com/grommet/grommet/blob/master/src/js/components/Select/SelectContainer.js#L411  

Buttons are passing all the props: https://github.com/grommet/grommet/blob/master/src/js/components/Select/SelectOption.js#L28

### Steps to Reproduce

1. Render Select with the objects: {[ id: '123', label: 'abc', value: 'abc' ]}
2. Inspect on select drop down buttons.
3. Id's are not being passed on.

### Your Environment

- Grommet version: 2.7.3
- Browser Name and version: Chrome 73
- Operating System and version (desktop or mobile): Windows

**Comment by ShimiSun** [comment] 2019-08-08 15:56
Thanks for filing an issue. 
A couple of things, it will help us if you can provide some context on what you are trying to achieve and why you find it necessary for your use case, and so we could provide the most suitable solution.
I started a code sandbox to reproduce what you are experiencing, but I need you to fill in the render method you are using to render the options object https://codesandbox.io/s/select-issue-3254-u15sr. please provide all the missing info so we can continue taking a look. let us know if you need any help.

**Comment by tharunhpe** [comment] 2019-08-19 06:41
@ShimiSun 
![grommetSelectIssue](https://user-images.githubusercontent.com/24956142/63244134-373c2d00-c27a-11e9-814d-a485f8cc340a.JPG)

Have updated the codesandbox, Look in the image for the issue. 

USE CASE: Unable to write automation tests using ids to select an item from drop down.

**Comment by ShimiSun** [comment] 2019-08-19 21:43
@tharunhpe can you send the codesanbox link? After you apply changes to it, it forks to a new instance with a new link.

**Comment by ShimiSun** [comment] 2020-04-04 13:54
@tharunhpe any updates on this one?

**Comment by IanKBovard** [comment] 2020-09-29 16:49
Passing ID in options like this will not give your list individual id's. Here is a way of accomplishing that.
https://codesandbox.io/s/select-issue-3254-forked-pc122?file=/index.js

Since this isn't a valid use of options as far as I am aware of, I believe we can close this issue.

**Comment by ShimiSun** [comment] 2020-10-02 14:13
Thank you @IanKBovard. I'm closing the issue, feel free to post any updates if still relevant.

**Closed by ShimiSun** 2020-10-02 14:13 UTC
Labels: waiting
