### ISSUE TITLE
Select options vanish when the page has been scrolled down

### ISSUE THREAD

**Issue by ryanjchr** [grommet/grommet#3579] opened 2019-12-03 06:56 UTC
### Expected Behavior
A Select dropdown that is open should show its options in the dropdown no matter the user's Y-Scroll position on the page.

### Actual Behavior
As of Grommet 2.8.1, when the user has scrolled a page down a certain amount and opens a Select dropdown there will be no options in the dropdown. Likewise, if a user opens a Select while not scrolled too far down the page, the options will appear, but if the user scrolls down while the options are visible they will disappear once the page scrolls past a certain threshold.

### URL, screen shot, or Codepen exhibiting the issue
This CodeSandbox requires this accompanying GIF demonstrating the issue.

![grommet-select-bug](https://user-images.githubusercontent.com/8773259/70026243-6725fb00-15f3-11ea-83d2-4558b3d6a4fa.gif)

https://codesandbox.io/s/select-long-page-grommet-generic-xkouw

### Steps to Reproduce
1. Create any Select component on a page that can scroll on the Y axis.
2. Open the React app in any browser and shrink the window on the Y axis somewhat (see the gif in the section above)
3. Open the Select dropdown to view the options
4. Scroll the page up and down and notice that the options disappear/reappear from the Select dropdown when scrolling the page down and up

### Your Environment
- Grommet version: 2.8.1
- Browser Name and version: Firefox 70.0.1 and Chrome 78
- Operating System and version (desktop or mobile): macOS

**Comment by felipebrunetti94** [comment] 2019-12-18 14:20
is this one up for grab ?

**Comment by emmerich** [comment] 2019-12-20 10:28
If it helps, I believe this was introduced in 2.8.1. Rolling back to 2.8.0 fixes the problem.

**Comment by ShimiSun** [comment] 2019-12-22 20:04
Thanks @emmerich , can you confirm if this is the commit https://github.com/grommet/grommet/commit/9d1b60527db18af6de090b0312d61201851f7a19?

**Comment by litewarp** [comment] 2019-12-28 00:05
I think the issue is with the use of React.memo to wrap the SelectOption. It looks like the commit moved the old props comparison from shouldComponentUpdate to the second argument for React.Memo. But those are not equivalent functions. As the React Docs note, [memo shouldn't be used to prevent a render](https://reactjs.org/docs/react-api.html#reactmemo)

Specifically though, I think what is happening is that because the option only updates when the dependency array has changed, and in this case, the dependency array is one boolean value, the options are not updating correctly. 

Don't have time to play around with this until later this weekend, but I think removing the optional areEqual argument would solve the issue. React.memo already performs a shallow comparison, so no need to pass in that second argument. By avoiding it, the SelectOption should re-render when any single one of its props changes rather than when the value of the computation changes. 

Hope this all makes sense. Thanks for the awesome framework! 


```

**Comment by skoshy** [comment] 2020-01-07 14:08
It seems like it has something to do with the behavior from the `replace` prop on `Select`. If I set `replace={false}`, it works as it properly should.

**Comment by IanKBovard** [comment] 2020-04-17 20:49
This issue can be closed. I'm unable to reproduce is as it was fixed by this pr 
https://github.com/grommet/grommet/pull/3784

**Comment by ShimiSun** [comment] 2020-04-20 16:36
Thanks @IanKBovard for solving the issue, I'll be closing it.

**Closed by ShimiSun** 2020-04-20 16:36 UTC
