### ISSUE TITLE
Button - DeepMerge of active is not working properly when target is string

### ISSUE THREAD

**Issue by Zodiase** [grommet/grommet#3202] opened 2019-07-17 02:16 UTC
Maybe DeepMerge is not called properly, but I don't have more time to dig deeper into how everything works so forgive me if my descriptions here are not exactly correct.

### Expected Behavior

I specified something like this in the theme:

```JS
{
    global: {
        active: {
            color: {
                dark: {
                    color: 'red',
                    opacity: '0.1'
                },
                light: {
                    color: 'red',
                    opacity: '0.1'
                }
            }
        }
    }
}
```

the actual values don't matter and the issue is not directly related to these values.

I expect the active button to have `color: red; opacity: 0.1;`, with other sensible rules.

### Actual Behavior

Well, this:

![image](https://user-images.githubusercontent.com/1815174/61342069-b5319200-a7fd-11e9-8cc3-a975c0f5144f.png)

After spending an hour digging and tracing, I found this:

![image](https://user-images.githubusercontent.com/1815174/61341880-14db6d80-a7fd-11e9-8d04-ced4ae47d768.png)

Either `DeepMerge` is not working properly, or it is not called properly.

https://github.com/grommet/grommet/blob/c22ab48cc72aba391bbcfd19b16cf7f4b4cfe1f6/src/js/utils/object.js#L16

this line above, is turning the string (the target) into an object.

### Steps to Reproduce

Perhaps all you need is my custom theme above.

### Your Environment

- Grommet version: 2.7.3
- Browser Name and version: Chrome 75.0.3770.100
- Operating System and version (desktop or mobile): macOS Mojave 10.14.5

**Comment by ShimiSun** [comment] 2019-07-17 15:11
Hi buddy, thanks for taking the time to share your findings.
>I expect the active button to have color: red; opacity: 0.1;
It seems like the actual behavior screenshot you attached is applying the color red, can you elaborate what is missing in your opinion? the screenshot is cropped and some context is missing.

Also, it will be helpful if you can share how you are calling the deepMerge function, maybe it wasn't called properly.

**Comment by Zodiase** [comment] 2019-07-17 17:35
@ShimiSun I'm not calling `deepMerge`, I just added the theme I've shown above.

It is applying color red, which is not the problem. The problem is the crazy stuff above the `color: red`. You can see it in both the style inspector and the debugger. The output has: 

```JS
{
    0: "w",
    1: "h",
    2: "i",
    3: "t",
    4: "e",
    color: "red",
    opacity: "0.1"
}
```

Again, I'm not calling `deepMerge` myself. I only added the theme and then I see this crazy stuff in my "active" buttons.

**Comment by ShimiSun** [comment] 2019-07-17 18:05
Thanks. 
I started a sandbox to try and reproduce the problem, but I suspect I'm still missing some details to complete the full markup. https://codesandbox.io/s/deepmerge-3202-cyuvo
Please fill in the gaps and reproduce the problem reliably outside the app.
I'm interested to see how you are applying the theme, and how `active` is being used, it will help us continue with inspecting the issue.

**Comment by Zodiase** [comment] 2019-07-17 20:48
@ShimiSun 

https://codesandbox.io/s/deepmerge-3202-vsuo7

Changes I made:
1. Change Grommet version to 2.7.3, which is the one I reported.
2. Change `Text` to `Button`, which uses `active`.
3. Add a dark `Box` outside of it for good measures. Probably not needed.

See the styles inspector.

![image](https://user-images.githubusercontent.com/1815174/61410621-73562980-a899-11e9-8fc5-ec6ef4bc89a4.png)

**Comment by ShimiSun** [comment] 2019-07-17 21:01
@Zodiase thanks for your prompt communication

**Comment by oorestisime** [comment] 2019-07-23 08:58
The active color prop only takes a string as parameter and not 
```
{
  color: 'red',
  opacity: '0.1'
},
```
if you have like `dark: "red"` it works in your codesandbox.

I am assuming deepmerge is expecting the same types and depth on the object to merge with the initial

**Comment by Zodiase** [comment] 2019-07-23 18:58
> I am assuming deepmerge is expecting the same types and depth on the object to merge with the initial

I'm pretty sure this (merging text into object) works even though it's not the same types or depth:

```JS
{
  global: {
    active: {
      color: "red"
    }
  }
}
```

The default being (from https://github.com/grommet/grommet/blob/master/src/js/themes/base.js#L108):

```JS
{
  global: {
    active: {
      color: {
        dark: 'white',
        light: 'black',
      }
    }
  }
}
```

That's why it's odd to me the opposite (merging object into text) yields such silly output.

**Comment by ShimiSun** [comment] 2019-07-29 19:49
@Zodiase, grommet's `color` prop is supporting both types of String & Object, but the Object type has a constraint of the following structure`{ dark: string, light: string }`. see https://v2.grommet.io/button#button.color (so it doesn't accept `opacity` styling)

I agree our documentation wasn't very helpful for the active behavior on Button, and I've filed https://github.com/grommet/grommet/pull/3230 to solve the confusion and the unclarity. 
The docs on the above PR specifies the expected input type for the active color styling, so I agree with @oorestisime that the reason you are getting strange behavior is due to using `opacity` which is unexpected input type for `global.active.color`. 

If you are attempting to use the `opacity` style, please use it within the `global.active.background` and not under `global.active.color`, the merge will not behave well when its input is unexpected.

Please feel free to share with us why you were under the impression that `global.active.color` should accept the opacity styling? I'm trying to see if there is any confusion with our docs that needs further attention.

**Comment by ShimiSun** [comment] 2019-08-08 20:49
hi @Zodiase, unless you got further comments or questions for us that are relevant to this issue, we'll be closing it. thank you for filing and collaborating.

**Closed** 2019-09-11 16:17 UTC
Labels: waiting
