### ISSUE TITLE
Missing Week of March 10 when date is supplied to Calendar Component

### ISSUE THREAD

**Issue by alfredkam** [grommet/grommet#2931] opened 2019-03-15 06:07 UTC
### Expected Behavior
Week of March 10 should appear in the calendar component, even when date as iso string was supplied

### Actual Behavior
Week of March 10 disappeared

### URL, screen shot, or Codepen exhibiting the issue
![Screen Shot 2019-03-14 at 11 03 35 PM](https://user-images.githubusercontent.com/1495567/54411831-caf74500-46ad-11e9-912b-c1aff0a5bf97.png)

Issue also appears in current story book.
https://storybook.grommet.io/?selectedKind=Calendar&selectedStory=Simple&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

### Steps to Reproduce

supply a date value of `date={"2019-03-15T06:00:01.409Z"}` to calendar component
### Your Environment

- Grommet version: 2.5.5
- Browser Name and version: chrome 72.0.3626.121
- Operating System and version (desktop or mobile): mac

**Comment by ShimiSun** [comment] 2019-03-15 16:28
Did you make any changes to the storybook to reproduce the problem? would you be able to share a snippet of what made the dates disappear?

**Comment by ShimiSun** [comment] 2019-03-15 18:00
OK, we were able to reproduce it. thanks for filing the issue.

**Comment by oorestisime** [comment] 2019-03-19 22:47
Closing this since PR was merged

**Closed by oorestisime** 2019-03-19 22:47 UTC
Labels: Bug :bug:, in progress
