### ISSUE TITLE
Jumping to top of page when elements get focus.

### ISSUE THREAD

**Issue by samogami** [grommet/grommet#230] opened 2015-11-04 17:15 UTC
In Chrome go to http://www.grommet.io/docs/develop/button
Then press the tab key to bring focus to the button element.
The page keeps jumping back to top of page each time the focus changes to a differnt button.

I have tested Chrome 46.0.2490.80 m for windows and also on Mac

I do not see the same behavior in FF 41.0.2 or IE 11.096

**Comment by bryanjacquot** [comment] 2016-07-28 22:07
@samogami do you still see this issue on Chrome?  I'm not able to reproduce it any longer.

**Comment by bryanjacquot** [comment] 2016-08-08 21:48
Closing.

**Closed by bryanjacquot** 2016-08-08 21:48 UTC
