### ISSUE TITLE
TextInput placeholder shows over value when input is decimal number

### ISSUE THREAD

**Issue by brucedonovan** [grommet/grommet#5096] opened 2021-03-23 11:35 UTC
### Expected Behavior

The placeholder should not obscure the input text when a number is entered.

### Actual Behavior

When entering a number followed by a decimal point, the placeholder shows. 

### URL, screen shot, or Codepen exhibiting the issue

<img width="335" alt="Screenshot 2021-03-23 at 11 21 38" src="https://user-images.githubusercontent.com/5603206/112139322-88d13a00-8bca-11eb-9f81-124c1792cb90.png">

### Steps to Reproduce

1. Add a `plain` TextInput box a Number `type="number"` , with a `placeholder="Enter value"` 
2. Enter a number with a decimal point (opposite to the system default decimal - i.e. if system uses ',' as decimal (like some parts of Europe) enter a '.' . 

### Your Environment

- Grommet version: 2.17
- Browser Name and version: chrome Version 89.0.4389.90
- Operating System and version (desktop or mobile): MAC OS 11.2.3

**Comment by jcfilben** [comment] 2021-03-24 19:37
Hi @brucedonovan I am having a hard time reproducing this. 
Here is the code I used for the TextInput: `<TextInput name="name" plain type="number" placeholder="Enter value" />`. 
I tried typing a number with a decimal point but it showed up correctly for me. You mentioned that this happens when the decimal is the opposite of the system default decimal so I tried typing commas (my system default is periods) but I was unable to type those into the TextInput when `type='number'`. I changed my system defaults so that a comma was the default decimal separator and still the TextInput was working as expected when I entered a number with a period as the decimal.
![Mar-24-2021 13-25-29](https://user-images.githubusercontent.com/54560994/112371652-77f4f700-8ca4-11eb-8217-041a3c449f19.gif)

**Comment by brucedonovan** [comment] 2021-03-25 10:33
Hi @ShimiSun thanks for your time. After some very superficial experimenting - It seems to be related more to the **region** rather than the decimal divider used. The issue presents itself with the default settings for european regions such as Portugal, Spain, France. 

<img width="351" alt="Screenshot 2021-03-25 at 10 24 35" src="https://user-images.githubusercontent.com/5603206/112458528-cd88dc80-8d54-11eb-9e08-0eacb031a2ed.png">

It happens in Safari too. Although that manifests in a slightly different way - it happens if you combine '.'s and ','s in the number input. 

I hope this helps. :|

**Comment by jcfilben** [comment] 2021-03-26 19:29
Even after switching the region to Spain I am still unable to reproduce this. I tested in both safari and chrome and both of them were working as expected. There was a [similar issue](https://github.com/grommet/grommet/issues/4922) with the TextInput placeholder that has been resolved since version 2.16.3. Can you just confirm that you are using the latest version of grommet? If you are using the latest version, I think the next step would be for you to share a codesandbox of the code you are using. I just want to make sure I am testing with the exact code that you are using.

**Comment by ShimiSun** [comment] 2021-04-06 17:42
I'll be closing this issue as it is not reproducible, please let us know if we can help in any other way.

**Closed by ShimiSun** 2021-04-06 17:42 UTC
Labels: bug, waiting
