### ISSUE TITLE
DataTable: Pagination does not work along with "groupBy" property

### ISSUE THREAD

**Issue by vbushma** [grommet/grommet#6560] opened 2023-01-04 13:15 UTC
DataTable pagination is broken when the "groupBy" property is provided. If I remove the "groupBy" property,so pagination works fine.
Usage:  <DataTable paginate={true} groupBy="company" {...otherProps} />  
### Expected Behavior
1. Pagination, if I click on the "next" button, I can see the next page, or if I click on pageNumber, I should see the page data.

### Actual Behavior
1. Pagination not working, I'm trying to click on the "next" or "pageNumber" buttons, but nothing happens

### URL, screen shot, or Codepen exhibiting the issue

  -- Here's a Codesandbox template that serves as a nice starting point
  -- for demonstrating an issue: https://codesandbox.io/s/groupby-not-working-with-paginate-i9k12c?file=/src/App.js

### Your Environment

- Grommet version: 2.28.0

**Comment by jcfilben** [comment] 2023-01-04 16:01
Duplicate of https://github.com/grommet/grommet/issues/6036

**Closed by jcfilben** 2023-01-04 16:01 UTC
