### ISSUE TITLE
Type error using react-hook-form

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#3653] opened 2020-01-10 15:38 UTC
I'm trying to use [react-hook-form](https://react-hook-form.com) with grommet but I have a typing issue.

Using the register function provided by react-hook-form inside the `ref` prop (see react-hook-form doc) with `TextInput` component I get this compiling error:

```
TS2322: Type 'void' is not assignable to type 'string | (string & ((instance: HTMLInputElement) => void)) | (string & RefObject<HTMLInputElement>) | (((instance: Component<TextInputProps & Pick<...>, any, any>) => void) & string) | ... 4 more ... | (RefObject<...> & RefObject<...>)'
```

Using a standard react `<input>` everything works as expected.

[This codesandbox](https://codesandbox.io/s/grommet-ts-dwb3w) reproduces my problem.
As you can see at 12 line I get transpiler error but next line, with the standard input component I get no errors by the transpiler.

Grommet version: 2.9.0

**Comment by ShimiSun** [comment] 2020-01-16 21:34
Thank you for the detailed issue and example.
Grommet doesn't redefine the `ref` type, it actually picks the same type as the `input` `ref`, so I'm not sure what is the root cause of the problem.
On https://github.com/grommet/grommet/blob/master/src/js/components/TextInput/index.d.ts
we do not override `ref` on TextInputProps, hence the original type definition for `ref` supposed to come from https://github.com/grommet/grommet/blob/a3c75c2310ac789120b137f6310a432ffb98fb92/src/js/components/TextInput/index.d.ts#L24
`JSX.IntrinsicElements['input']` but somehow it doesn't.

I ran your example locally and I couldn't find a straight forward way to the solution, feel free to shoot ideas if you have any.

**Comment by c3s4** [comment] 2020-01-17 09:14
You're right, I was surprised about this behavior. I figured out that to make react-hook-form works with grommet I have to use the `forwardRef` instead of `ref` but the error is the same.

At the moment I'm using `@ts-ignore` comments to shut up the type checker but, obviously, I don't like it.

I investigated a little on this but, so far, I didn't find anything.

**Comment by jcfilben** [comment] 2022-03-28 17:32
Closing since I am no longer seeing this issue in the codesandbox provided when using the latest versions of dependencies https://codesandbox.io/s/grommet-ts-forked-cqsjge

**Closed by jcfilben** 2022-03-28 17:32 UTC
Labels: help wanted, typescript
