### ISSUE TITLE
Grommet 2.7.8 Layer crashes

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#3359] opened 2019-09-18 23:47 UTC
In Grommet 2.7.4 this works correctly. If I change to 2.7.8 I get an error whenever Layer is used...
Uncaught TypeError: Cannot read property 'style' of null
    at Layer.componentWillUnmount (Layer.js:74)
    at Layer.componentWillUnmount (react-hot-loader.development.js:698)
    at callComponentWillUnmountWithTimer (react-dom.development.js:17123)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at safelyCallComponentWillUnmount (react-dom.development.js:17130)
    at commitUnmount (react-dom.development.js:17507)
    at commitNestedUnmounts (react-dom.development.js:17538)
    at unmountHostComponents (react-dom.development.js:17799)

### Steps to Reproduce
1) Upgrade to 2.7.8
2) Run a piece of code that users a Layer.

**Comment by RobertGary1** [comment] 2019-09-19 00:32
PR 3307 introduced this. It assumes it can find an element by a query and then deference it.

**Comment by RobertGary1** [comment] 2019-09-20 00:35
clonedContainer is null here...

      var clonedContainer = layerClone.querySelector('[class*="StyledLayer__StyledContainer"]');
      clonedContainer.style.animationDirection = 'reverse';

**Comment by RobertGary1** [comment] 2019-09-20 18:20
Hmm, running against master directly now and I don't think I"m seeing it. Maybe this was fixed??

**Comment by brodybits** [comment] 2019-09-20 18:37
> PR 3307 introduced this.
> [...]

Adding GitHub reference to #3307

> Hmm, running against master directly now and I don't think I"m seeing it. Maybe this was fixed??

I think we should add a test case to help ensure this kind of issue does not appear in the future, if possible.

A [minimal, reproducible example ([1])](https://stackoverflow.com/help/minimal-reproducible-example) would help outsiders like me reproduce the issue on the recent release and maybe contribute a test case.

Assuming that we are able to reproduce the issue on 2.7.8 and not on master, I would really favor a new patch release asap.

[1] https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ShimiSun** [comment] 2019-09-30 20:10
@brodybits SPOT ON!! I'm gonna save this link and probably use it in the near future... :)
We are working on a new release now.
I'll be closing this issue, feel free to reopen if needed.

**Closed by ShimiSun** 2019-09-30 20:10 UTC

**Comment by iMerica** [comment] 2019-10-16 18:44
Please re-open this issue. I've verified that it occurs in the current (v 2.7.9) version.

**Comment by iMerica** [comment] 2019-10-16 22:34
The problem is in `src/js/components/Layer/Layer.js`
```jsx
var clonedContainer = layerClone.querySelector('[class*="StyledLayer__StyledContainer"]');
clonedContainer.style.animationDirection = 'reverse';
```

A null check needs to exists on `clonedContainer`.

**Comment by iMerica** [comment] 2019-10-16 22:37
Also important to note that this error occurs only on a page that is no longer mounted. Given a Single Page Application with pages A and B, this error occurs on Page A only when page B is mounted.

**Comment by brodybits** [comment] 2019-10-16 22:45
> The problem is in `src/js/components/Layer/Layer.js`
> [...]

Any pointers how that problem can be reproduced?

**Comment by iMerica** [comment] 2019-10-16 22:49
@brodybits  

This one is not something I can quickly create a CodePen for. 

Basically:

- Build a Single Page Application using Grommet with tools like React Router. 
- Use a Layer component on a one of the Pages.
- Navigate between pages.
- Observe that since this layer component is piercing through the virtual DOM and is not un-mounting itself, the null DOM element error occurs.

**Comment by brodybits** [comment] 2019-10-16 23:02
@iMerica can you do me a favor and give me some pointers to help me with each of the steps, with examples if possible?

I am an outsider, would love to help fix the crash if possible, ... BUT I am unfortunately not so familiar with using layers or routers. My one contribution so far has been an incomplete **draft** PR to use React Primitives: #3029

I think they would need a test before accepting a PR to add the null check, like you suggested.

The issue with the Layer component does sound pretty bad.
