### ISSUE TITLE
SVG Errors when passing an empty array to charts

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3563] opened 2019-11-20 00:22 UTC
Sometimes, in React components we need to pass an initial state before dynamic data is loaded. When you pass this empty data to the chart component, errors display in the console.

```
Error: <svg> attribute viewBox: A negative value is not valid. ("0 0 -24 192")
```

### Expected Behavior

`[]` should be valid data for charts.

### Actual Behavior

SVG errors

### Steps to Reproduce

```jsx
<Chart
  type="bar"
  overflow
  values={[]}
  size={{ width: "auto" }}
/>
```

### Your Environment

- Grommet version: "grommet": "^2.8.0",
- Browser Name and version: Chrome Latest
- Operating System and version (desktop or mobile): macOS

**Comment by ShimiSun** [comment] 2019-11-26 19:01
Thanks for reporting, the issue is fixed on the master branch and will be available on our next release.

**Closed by ShimiSun** 2019-11-26 19:01 UTC
Labels: Bug :bug:
