### ISSUE TITLE
Button within a Header shows a border despite being "plain"

### ISSUE THREAD

**Issue by arabold** [grommet/grommet#1343] opened 2017-05-04 22:05 UTC
### Expected Behavior
A button configured to be _plain_ shouldn't render a border, regardless if placed within the main body of the page or in any header.

### Actual Behavior
Button works as expected if rendered within a Box somewhere on the page and doesn't show a border. However, if I place it inside of a `<Header>` tag it will suddenly render a border without any configuration change.

### URL, screen shot, or Codepen exhibiting the issue

```jsx
<Button icon={ <Icons.Base.Close /> }
	plain={ true } onClick={ onToggle } />

<Header direction="row" colorIndex="brand" pad="medium" justify="between">
	<Title>Hello World</Title>
	<Button icon={ <Icons.Base.Close /> }
		plain={ true } onClick={ onToggle } />
</Header>
```

![image](https://cloud.githubusercontent.com/assets/1548229/25726811/bd3e26a8-30da-11e7-8a4a-c771dbe9a381.png)

I'm rendering this inside of a `<Sidebar>` and a `<Split>` control. The purpose of this button is (surprise, surprise) to allow closing the sidebar.

### Your Environment
* Grommet version: 1.4.0
* Browser Name and version: Chrome Version 57.0.2987.133 (64-bit)
* Operating System and version: macOS Sierra 10.12.4

**Comment by cherih** [comment] 2017-05-18 21:17
Hi @arabold,

I'm sorry, but we aren't able to replicate this issue using the latest source code in the repo. Do you still see the problem or have an updated codepen that reflects the issue?

**Comment by alansouzati** [comment] 2017-06-10 00:03
We cannot reproduce this issue. I'm closing it. Feel free to reopen if you can reproduce it. And if you are able to reproduce,  please provide a codepen where we can validate it.

**Closed by alansouzati** 2017-06-10 00:03 UTC
Labels: this sprint, waiting
