### ISSUE TITLE
Add Dutch translation

### ISSUE THREAD

**Issue by wdonne** [grommet/grommet#1223] opened 2017-03-06 10:23 UTC
It would be nice to have a translation file for Dutch in the components/messages directory.

### Expected Behavior

Static labels, such as "Total" in a legend for example, should appear in Dutch when the language of the browser is set on that language.

### Actual Behavior

The default language is used.

### Steps to Reproduce
 1. Use a Legend component
 2. Set the language of the browser to Dutch
 3. Refresh

### Your Environment

* Grommet version: 1.2.1
* Browser Name and version: Chrome 56.0.2924.87
* Operating System and version (desktop or mobile): macOS 10.12.3

**Comment by alansouzati** [comment] 2017-03-09 00:35
We don't have the resources in our team to add Dutch translation. You can either add that Total entry in your react-intl or send a pull request to add Dutch support.

See this video for reference on internationalization: https://vimeo.com/173575546

I'm closing this issue as I believe it is not a bug in Grommet. We kindly appreciate pull requests! 👍

**Closed by alansouzati** 2017-03-09 00:35 UTC
Labels: needs attention
