### ISSUE TITLE
Style ResponsiveBreakpoint values other than "small" generate an exception

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#4246] opened 2020-06-29 23:41 UTC
see https://codesandbox.io/s/grommet-scroll-works-yhm1o?file=/index.js

StyledBox gapStyle() is looking for theme.global.breakpoints.medium.edgeSize which is undefined

**Comment by RobertGary1** [comment] 2020-06-30 01:12
Also if borderSize is undefined it breaks

**Comment by ShimiSun** [comment] 2020-07-01 17:11
I believe it is related to #4217 and that fix is available on the stable branch. Let me know if we can close the issue.

**Comment by RobertGary1** [comment] 2020-07-01 17:52
The codesandbox example above is using 2.14.0. Is there a more recent version? Or are you asking me to test from the master branch?

**Comment by ShimiSun** [comment] 2020-07-01 17:58
The [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) has a more recent fix on the breakpoint behavior, I think if the issue is fixed there then we can close the issue. Please be mindful stable couldn't be tested on codesandbox since it is not published on NPM.

**Comment by jcfilben** [comment] 2020-09-11 21:31
Hey @RobertGary1 just wanted to check back in on this issue and see if using the most recent version of grommet fixed this issue

**Comment by ShimiSun** [comment] 2020-09-22 06:21
I've just verified the problem still reproduces on v2.15.0.

**Comment by netochaves** [comment] 2020-09-22 21:09
That's because grommet don't have breakpoints values set for `medium` and `large` responsive options, only for small. If this is documented somewhere I could implement it. 

https://github.com/grommet/grommet/blob/f2ecd5ee71cb133b2d210f5a7e43322b549a11da/src/js/themes/base.js#L164-L198

**Comment by jcfilben** [comment] 2020-10-16 20:39
@ShimiSun Adding borderSize, edgeSize, and size to medium and large in breakpoints does fix the problem but I am not sure what pixel values should go here. Is there a reason these fields were left blank in the first place?

**Comment by halocline** [comment] 2020-10-19 20:56
> @ShimiSun Adding borderSize, edgeSize, and size to medium and large in breakpoints does fix the problem but I am not sure what pixel values should go here. Is there a reason these fields were left blank in the first place?

@jcfilben I believe they were never defined under the `breakpoints` property because the idea is if they don't need to be adjusted for a breakpoint, they should use the defaults set elsewhere in the theme:
- https://github.com/grommet/grommet/blob/f2ecd5ee71cb133b2d210f5a7e43322b549a11da/src/js/themes/base.js#L157
- https://github.com/grommet/grommet/blob/f2ecd5ee71cb133b2d210f5a7e43322b549a11da/src/js/themes/base.js#L227
- https://github.com/grommet/grommet/blob/f2ecd5ee71cb133b2d210f5a7e43322b549a11da/src/js/themes/base.js#L308

Let me know if you'd like to talk through this at all, or if this is enough to get you started.

**Comment by ericsoderberghp** [comment] 2020-10-19 21:50
> if they don't need to be adjusted for a breakpoint, they should use the defaults set elsewhere in the theme

Agreed

**Closed** 2020-11-04 17:24 UTC
Labels: Bug :bug:, hacktoberfest

**Comment by ShimiSun** [comment] 2020-11-04 19:42
Thank you for reporting, the fix will be available on our next official release.
