### ISSUE TITLE
Creating image links: wrapping <Image> with <Anchor> causes image to render full size, ignoring parent <Box>

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#3186] opened 2019-07-04 10:13 UTC
### Expected Behavior
Anchor should have no effect on sizing of children

### Actual Behavior
Wrapping `<Image>` with `<Anchor>` causes image to render full size, ignoring parent `<Box>` height and width.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-github-issue-3186-0m2dl (see src/Image.js and https://0m2dl.codesandbox.io/image)

**Comment by Mr-Magnificent** [comment] 2019-10-08 00:51
I believe `max-width: 100%; max-height: 100%` on `<img>` in `src/js/components/Image/StyledImage.js` could solve the issue? Can I take this up?

**Comment by britt6612** [comment] 2019-10-08 01:23
@Mr-Magnificent I'm sure @ShimiSun will be grateful if you take this up! 👍 🥇

**Comment by Mr-Magnificent** [comment] 2019-10-08 13:41
How can I test if my changes solves the issue?

**Comment by oorestisime** [comment] 2019-10-08 13:47
You can create a new story on storybook with a reproduction of the issue.

**Comment by Mr-Magnificent** [comment] 2019-10-08 14:40
Should the patch include the story?

**Comment by oorestisime** [comment] 2019-10-08 14:52
If you feel this could be interesting for users why not!

**Comment by Mr-Magnificent** [comment] 2019-10-08 15:26
> If you feel this could be interesting for users why not!

To be honest, I am not entirely sure. Maybe check if it adds value during review? :sweat_smile:

**Comment by oorestisime** [comment] 2019-10-08 15:30
sure will be easier to review! :)

**Comment by IanKBovard** [comment] 2020-04-23 16:42
If #3443 solved this issue we can close this.

**Comment by markjackson02** [comment] 2020-06-22 00:59
Retested on 2.14.0. This still seems to be an issue.

**Comment by halocline** [comment] 2020-07-13 16:19
@markjackson02 -- I looked into this and think there are a couple of options here, but my recommendation would be to move the `Anchor` so that it contains the `Box` and `Image`, rather than the `Anchor` being placed in between the `Box` and `Image`.
```
<Anchor>
  <Box height="small" width="small" >
    <Image fit="cover" />
  </Box>
</Anchor>
```

I have modified your CodeSandbox example to demonstrate: https://codesandbox.io/s/grommet-github-issue-3186-gingn?file=/src/Image.js

**Explanation**
If we were to perform the same implementation in pure HTML/CSS, we would run into a similar issue where an `<a>` in between a `<div>` and `<img>`. This is because `<a>` is an inline element and receives it dimensions from its contents. When the anchor is immediately wrapping the image, there is nothing (outside of the source file) setting the image's dimension. The solution here would be similar: `<a><div><img /></div></a>`.

There is a newer CSS spec recommendation for `display: contents` which when applied to the anchor would achieve the desired results, but it is not production ready and still has accessibility issues: https://caniuse.com/#feat=css-display-contents & https://developer.mozilla.org/en-US/docs/Web/CSS/display

@markjackson02 Can you checkout the modified CodeSandbox and confirm this alternate approach solves your needs?

**Comment by ShimiSun** [comment] 2020-08-18 04:50
Thank you @halocline for the detailed analysis, I'll be closing this issue. One can feel free to reopen if still relevant or file a new issue.

**Closed by ShimiSun** 2020-08-18 04:50 UTC
Labels: waiting
