### ISSUE TITLE
TypeError in Table._adjustBodyCells() due to array index out of bounds

### ISSUE THREAD

**Issue by h-arlt** [grommet/grommet#1249] opened 2017-03-20 10:30 UTC
### Expected Behavior
State transitions caused by click on anchors/buttons defined in table body work as expected and no errors are logged.

### Actual Behavior
Browser console logs: TypeError: Cannot read property 'innerText' of undefined
and clicking on any anchor defined in table body does not cause state transition anymore.

### Sample code
```javascript
class HelloWorldApp extends React.Component {

  constructor(props) {
    super(props);   
    this.state = { showLayer: false, item: undefined};
  }
  
  _onClickEditItem(item) {
    this.setState({showLayer: true, item: item})
  }

  _onSort(idx, asc) {
    console.log('onSort');
  }

  render() {
    const items = [{
      name: 'My Test Item1',
      shortName: 'test1',
      description: 'bla fasel bum'
    }, {
      name: 'My Test Item2',
      shortName: 'test2',
      description: 'Lorem isum ...'
    }, {
      name: 'My Test Item3',
      shortName: 'test3',
      description: 'foo bar baz'
    }, ];
    const sortIndex = 1,
      sortAscending = true;
    const headerLabels = [
      <FormattedMessage id="name" />,
      <FormattedMessage id="shortName" />,
      <FormattedMessage id="desc" />,
    ];
    
    let child = null;
    if(this.state.showLayer && this.state.item){
      child = <Layer modal={true}><h2>{this.state.item.name}</h2></Layer>
    }
    return (
      <App>
        <Title>Hello World</Title>
        <Table>
            <TableHeader labels={headerLabels} sortIndex={sortIndex} sortAscending={sortAscending} onSort={this._onSort} />
          <tbody>
            { items.map(item => {
              return             <TableRow key={item.shortName}>
        <td><Anchor onClick={() => this._onClickEditItem(item)}>{item.name}</Anchor></td>
        <td>{item.shortName}</td>
        <td>{item.description}</td>
      </TableRow>

            })}
          </tbody>
        </Table>
        {child}
      </App>
    );
  }
};

```

### Steps to Reproduce
 1. Run code above with v1.3.0.
 2. Click on any anchor.
 3. Compare result with v1.3.1

### Your Environment

* Grommet version: 1.3.1
* Browser Name and version: Chromium 56.0.2924.76 / Firefox 52
* Operating System and version (desktop or mobile): Linux Mint 18.1 Cinnamon

**Comment by psales** [comment] 2017-03-20 10:59
I have the same error message when loading a data into a Table component.
I think the issue is that the `headerIndex` variable is not reset to `0` when looping through the next row of the table.

In this line:
https://github.com/grommet/grommet/blob/v1.3.1/src/js/components/Table.js#L331 @alansouzati

**Comment by alansouzati** [comment] 2017-03-20 16:36
Yeah, sorry I should have tested this more. Let me work on a fix for this today.

**Comment by alansouzati** [comment] 2017-03-20 17:30
Shame on me, sorry folks. I've fixed this on https://github.com/grommet/grommet/commit/cd5b9ac23cfba79682dc805ff7a84367a9c0bb9b

I will soon release 1.3.2 with this fix, there are a couple of other items I will include in this release as well.

**Closed by alansouzati** 2017-03-20 17:30 UTC
Labels: in progress

**Comment by alansouzati** [comment] 2017-03-21 03:55
1.3.2 released https://github.com/grommet/grommet/releases/tag/v1.3.2

**Comment by h-arlt** [comment] 2017-03-21 07:59
Awesome! Thanks.
