### ISSUE TITLE
FileInput onChange event not called when files are removed

### ISSUE THREAD

**Issue by vincentl** [grommet/grommet#5023] opened 2021-03-02 03:40 UTC
### Expected Behavior

The new FileInput component (introduced from issue #2535) `onChange` event should be called when files are removed so client code can responded to removal.

### Actual Behavior

`onChange` is only called when files are added.

**Comment by abnersajr** [comment] 2021-03-03 04:21
Good call @vincentl. I think to be more flexible we can add a callback `onRemove`  to be triggered when you remove a file using the button.

**Comment by ericsoderberghp** [comment] 2021-03-03 04:23
Agreed. This shouldn't be too hard to create a pull request for. Any takers?

**Comment by abnersajr** [comment] 2021-03-03 04:53
@ericsoderberghp I'm doing. Will add `onRemove`  and `onRemoveAll`

**Comment by ericsoderberghp** [comment] 2021-03-03 04:55
I think leveraging `onChange` would be sufficient. Just have it reflect the current set of files. The callee already has to track when multiple files are added sequentially. Removing would mirror in reverse.

**Comment by abnersajr** [comment] 2021-03-03 05:01
IMO,  Give to the user the possibility to declare a specific callback for `remove` and `removeAll`  would be nice, in case he wants he can simply pass the same function used in the `onChange`  to these callbacks.

One possibility is to add the `onChange`  as default. In case the user doesn't pass callbacks to `onRemove`  and `onRemoveAll` by default we can use the `onChange` if it exists.
Adding this to the documentation to let the user know about it.
@ericsoderberghp what you think?

**Comment by abnersajr** [comment] 2021-03-03 05:26
Opening the PR and thinking in the backward compatibility, only leveraging the `onChange` function, might lead users to unexpected behaviors.
The addition of a new callback does not impact old users that don't want this behavior.

**Comment by ericsoderberghp** [comment] 2021-03-03 05:47
Part of my point was we don't have `onAdd`, when adding a subsequent file to a multiple file input. Also, Select that allows multiple options being selected only indicates changes to the selected options via `onChange`. I think it is more consistent to stay with just `onChange`.

**Comment by abnersajr** [comment] 2021-03-03 06:31
Cool. PR is opened.

**Comment by jcfilben** [comment] 2021-09-24 22:10
Closing since #5028 was merged.

**Closed by jcfilben** 2021-09-24 22:10 UTC
Labels: bug
