### ISSUE TITLE
Dropdown menu ui bug on scroll

### ISSUE THREAD

**Issue by JonathanWbn** [grommet/grommet#1389] opened 2017-06-16 08:27 UTC
I have a dropdown menu in my navbar. When I extend it and start scrolling with the menu dropped down, the menu is not overflowing the viewport size.
Tough to explain, here is how it looks:

This is the very top of the page, menu dropped down, everything perfect.
![screen shot 2017-06-16 at 10 16 38](https://user-images.githubusercontent.com/19997520/27218130-21149a7c-527d-11e7-8589-3cc81eba2b2f.png)

I start scrolling, everything perfect.
![screen shot 2017-06-16 at 10 16 48](https://user-images.githubusercontent.com/19997520/27218131-2115a9f8-527d-11e7-8a7f-da2a9e7bf7bb.png)

When I reach the point of which is bottom of the page when we are at the top, this happens:
![screen shot 2017-06-16 at 10 16 56](https://user-images.githubusercontent.com/19997520/27218133-211704e2-527d-11e7-9731-7d11454b8a50.png)

It continues while scrolling...
![screen shot 2017-06-16 at 10 17 05](https://user-images.githubusercontent.com/19997520/27218132-2116b38e-527d-11e7-88d9-39d906049003.png)

And when we passed that point (which is bottom when at the top), everything is perfect again:
![screen shot 2017-06-16 at 10 17 14](https://user-images.githubusercontent.com/19997520/27218134-2118875e-527d-11e7-93dc-7e8fd73b0425.png)

I can't make sense of this error, since I am basically just using grommet boxes and did not make any z-index modifications.
Would appreciate some input on how this might happen.

**Comment by RyanCCollins** [comment] 2017-06-16 14:03
Hey @JonathanWbn,

Thanks for your issue!  In order to help diagnose this, is it possible that you can post a codepen to exhibit the symptoms?  If not codepen, an example project would be helpful. Thanks!

**Comment by JonathanWbn** [comment] 2017-06-16 17:47
I am happy to try and reproduce with a codepen. How can I set up a codepen with grommet?

**Comment by alansouzati** [comment] 2017-06-16 17:59
You can fork our template from here:

https://codepen.io/grommet/pen/gaEGPY

**Comment by JonathanWbn** [comment] 2017-06-17 10:34
Here is the codepen with the issue. Just open the menu and start scrolling:
https://codepen.io/anon/pen/VWPbqp

**Comment by alansouzati** [comment] 2017-06-28 20:38
yeah that's pretty bad. let my try to fix this.

**Comment by alansouzati** [comment] 2017-06-28 21:17
just FYI I cannot reproduce this issue on Chrome.

**Comment by alansouzati** [comment] 2017-06-28 21:48
Fixed by https://github.com/grommet/grommet/commit/6b7ec5c9bfc246e8f9d47d5d4450e6e99d3cbc9e

**Closed by alansouzati** 2017-06-28 21:48 UTC
Labels: in progress
