### ISSUE TITLE
Grommet Calendar Format changed

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#2729] opened 2019-02-05 19:31 UTC
### Expected Behavior
The Grommet calendar used to show the date formatted like: `January 1, 2019`. (In the sandbox, you will also notice that the calendar is very broken, i.e. 1/13 is showing twice, no 1/12, etc.  I have seen this before, but think it may have been addressed already?  We are not seeing this happen any longer in OneSphere).

### Actual Behavior
Grommet calendar is showing date formatted like: `1/1/2019`

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/l94v022w4l

<img width="472" alt="screen shot 2019-02-05 at 2 29 12 pm" src="https://user-images.githubusercontent.com/13810084/52299036-5dece300-297c-11e9-96dc-4930ec3abaeb.png">

### Steps to Reproduce
1. Create a calendar
2. Pass in a date string like: 1/1/2019

### Your Environment

- Grommet version: 2.3.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Any

**Comment by ShimiSun** [comment] 2019-02-06 18:26
@oorestisime due to your different timezone, the misalignment of the date you are seeing may be related to https://github.com/grommet/grommet/issues/2685

**Comment by oorestisime** [comment] 2019-02-06 18:42
oh no sorry i put `1/2/2019` on my example. didn't meant to say there's a bug actually. jsut the day number is missing. but i am not sure there was ever

**Comment by ShimiSun** [comment] 2019-02-06 21:22
I don't see any issue either, the codesandbox example is shown as expected on my client:
![screen shot 2019-02-06 at 2 18 22 pm](https://user-images.githubusercontent.com/6320236/52374447-89260f80-2a1a-11e9-89be-41ff8c28d574.png)

and I've also ran regression testings on storybook with the most recent branch and it looks good.
let me know what we are missing.

**Comment by MikeWalrath** [comment] 2019-02-13 20:21
@RyanCCollins were you able to look into this issue any more?

**Comment by MikeWalrath** [comment] 2019-02-25 14:42
@RyanCCollins I will be closing this issue since we were unable to validate it. Please feel free to reopen the issue if you as still seeing it.

**Closed by MikeWalrath** 2019-02-25 14:42 UTC
Labels: waiting
