### ISSUE TITLE
Scrollbar issue in distribution chart

### ISSUE THREAD

**Issue by ishwark7** [grommet/grommet#1232] opened 2017-03-10 07:13 UTC
Hovering over the distribution chart, adds vertical/horizontal scrollbars to the chart

### Expected Behavior

Scroll bars should be avoided on the distribution chart.

### Actual Behavior

Scrollbars don't show up on first load.
Once you hover over the chart/tiles, they get added.They don't go away even when you remove the cursor from it.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/ishwark7/pen/MpyQrr

### Steps to Reproduce
 1. Open the codepen
 2. Hover over the tiles in ditribution chart
 3. Scroll bar appears, it goes away only on reload.

### Note
This maybe due to different properties added to Section or Box component, if yes, then can you please help me with that.

### Your Environment

* Grommet version: Latest
* Browser Name and version: Chrome/IE

Thanks,
Ishwar

**Comment by ericsoderberghp** [comment] 2017-03-14 15:09
I haven't been able to reproduce this.

**Comment by hdehal** [comment] 2017-03-14 19:03
Are you testing across multiple browsers? I can get scrollbars in Firefox on OS X. 

And in other browsers (e.g. Safari) I can get the charts to move around on mouseover (not in a good way).

![charts_scrollbar](https://cloud.githubusercontent.com/assets/21130143/23917908/2ccec41e-08ae-11e7-9bcb-a481a5c6a487.png)

**Comment by ishwark7** [comment] 2017-03-15 07:07
Hi,

Maybe, you can try to change the layout of the codepen as seen in the screenshots below.

I am able to reproduce this on Windows:
1. Chrome : 57.0.2987.98 (64-bit)  The issue was present earlier, it still exists in latest update too.
![chrome](https://cloud.githubusercontent.com/assets/24618233/23937066/89799e8c-097b-11e7-9501-84de5988fec8.PNG)


2. Firefox: 52.0 (32-bit) The issue was present earlier, it still exists in latest update too.
![firefox](https://cloud.githubusercontent.com/assets/24618233/23937069/8ed8be12-097b-11e7-82a0-d568a366e384.png)

Thanks,
Ishwar

**Comment by alansouzati** [comment] 2017-03-25 00:43
I could not reproduce the scrollbar issue. I've pushed changes to the distribution i hopes that will improve this.

For Grommet 2.0 we will re-evaluate the way Distribution is implemented. In the meantime, I believe this is going to stay as is.

Checkout this commit that has some improvements already:

https://github.com/grommet/grommet/commit/fc6f5a2a5dfa168a121106b3b2d977b63c374f73

**Comment by tracybarmore** [comment] 2017-05-01 16:08
Hey @ishwark7, I'm going to go ahead and close this issue due to Alan's response. If you still have questions or are able to reproduce the issue, please feel free to reopen. Thanks!

**Closed** 2017-05-01 16:08 UTC
