### ISSUE TITLE
Markdown Component Giving webpack error

### ISSUE THREAD

**Issue by britt6612** [grommet/grommet#6366] opened 2022-09-30 13:36 UTC
### Expected Behavior
no error

### Actual Behavior
I was using the "Markdown" component to render some markdown as JSX, which used to work.
Recently, where Markdown component is used, the app crashes and I get the following error in the console:
Uncaught TypeError: react__WEBPACK_IMPORTED_MODULE_0__ is not a function

### URL, screen shot, or Codepen exhibiting the issue

```              {post.Introduction ? (
                <Markdown
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    backgroundColor: "#F3F7FB",
                    padding: "20px",
                    marginRight: "5%",
                    marginLeft: "5%",
                    color: "#395E9D",
                    fontStyle: "italic",
                    height: "100%",
                  }}
                  components={{
                    p: {
                      component: "Paragraph",
                      props: { maxWidth: "100%" },
                    },
                  }}
                >
                  {post.Introduction}
                </Markdown>
              ) : null}
```

<img width="645" alt="Screen Shot 2022-09-30 at 7 37 38 AM" src="https://user-images.githubusercontent.com/42451602/193281620-33c7826c-4e13-4ab7-bf31-d5f9c0df067c.png">

### Steps to Reproduce

1. 2. 3.

### Your Environment

"grommet": "^2.26.0",
"styled-components": "^5.3.6",

**Comment by jcfilben** [comment] 2022-10-10 21:44
Marking this as closed, we were not able to reproduce the issue and didn't get a response from the original person who reported the issue on slack. We can reopen later if needed.

**Closed by jcfilben** 2022-10-10 21:44 UTC
Labels: waiting
