### ISSUE TITLE
V2. Displacement of elements bug on Safari

### ISSUE THREAD

**Issue by srockk** [grommet/grommet#2270] opened 2018-09-10 20:05 UTC
### Expected Behavior

Button should be clickable on the button

### Actual Behavior

Button is not clickable on the button (but on displaced location)

### URL, screen shot, or Codepen exhibiting the issue
<img width="735" alt="screen shot 2018-09-10 at 3 58 19 pm" src="https://user-images.githubusercontent.com/8532807/45321393-4287c400-b513-11e8-8159-ddd034ae4eda.png">
<img width="570" alt="screen shot 2018-09-10 at 3 58 03 pm" src="https://user-images.githubusercontent.com/8532807/45321399-49163b80-b513-11e8-82da-29a047964ca7.png">
<img width="778" alt="screen shot 2018-09-10 at 3 58 42 pm" src="https://user-images.githubusercontent.com/8532807/45321406-4b789580-b513-11e8-85f2-27aa93861259.png">
<img width="797" alt="screen shot 2018-09-10 at 3 59 03 pm" src="https://user-images.githubusercontent.com/8532807/45321412-4ddaef80-b513-11e8-905b-1c4c121982d4.png">

play around in different screen resolution
v2.grommet.io/play
```
/**
* Welcome to the Grommet playground!
* This is the hello world example. There are more examples available
* in the top right header, so feel free to explore all of it.
* Grommet components can be accessed by their direct name, e.g.:
* Box, Button, ...
* Icons are available inside Icons variable: Icons.Add, for example.
*
* About this hello world example:
*
* It simulates a form (no real action). It adds a Header, Body, and Footer.
* The body scrolls independently. Header and Footer are sticky.
* See overflow='auto' in the Box for the Body component.
*
* Don't forget to checkout the Theme playground, where we demonstrate how to
* customize the Grommet theme to match your brand.
*
* Have fun :)
**/

const ConfirmationLayer = ({ onClose }) => (
  <Layer position='center' onClickOutside={onClose}>
    <Box pad='large' gap='medium'>
      <Text>Are you sure?</Text>
      <Box direction='row' gap='medium' align='center'>
        <Button label='Yes' onClick={onClose} />
        <Button label='No' primary={true} onClick={onClose} />
      </Box>
      <Box direction='row' gap='medium' align='center'>
        <Button label='Yes' onClick={onClose} />
        <Button label='No' primary={true} onClick={onClose} />
      </Box>
      <Box direction='row' gap='medium' align='center'>
        <Button label='Yes' onClick={onClose} />
        <Button label='No' primary={true} onClick={onClose} />
      </Box>
      <Box direction='row' gap='medium' align='center'>
        <Button label='Yes' onClick={onClose} />
        <Button label='No' primary={true} onClick={onClose} />
      </Box>
      <Box direction='row' gap='medium' align='center'>
        <Button label='Yes' onClick={onClose} />
        <Button label='No' primary={true} onClick={onClose} />
      </Box>
      <Box direction='row' gap='medium' align='center'>
        <Button label='Yes' onClick={onClose} />
        <Button label='No' primary={true} onClick={onClose} />
      </Box>
    </Box>
  </Layer>
);

class Body extends React.Component {
  constructor() {
    this.state = {}
  }
  render () {
    const { layerType } = this.state;
    let layer;
    if (layerType === 'Confirmation') {
      layer = <ConfirmationLayer onClose={() => this.setState({ layerType: undefined })} />;
    }

    return (
      <Box flex={true} pad='medium' overflow='auto'>
        <Box margin='small'>
          <Button
            label={'Confirmation'}
            onClick={() => this.setState({
              layerType: (layerType === 'Confirmation' ? undefined : 'Confirmation'),
            })}
          />
        </Box>
        {layer}
      </Box>
    );
  }
}

const App = () => (
  <Grommet theme={Themes.grommet} full={true}>
    <Box fill={true}>
      <Body />
    </Box>
  </Grommet>
);

render(<App />);
```
### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: V2
* Browser Name and version: latest Safari
* Operating System and version (desktop or mobile): desktop

**Comment by alansouzati** [comment] 2018-09-10 21:48
thanks for reporting this. looks like a bug. I will try to fix this later today.

Glad to see you are using the playground, FYI

**Comment by prateekgoel** [comment] 2018-10-01 11:10
@alansouzati In case you are not working on this, can I try to fix this?

**Comment by alansouzati** [comment] 2018-10-05 21:06
yes!! @prateekgoel thanks for volunteering!!! sorry for the delay in my response. I can't believe I missed this.

**Comment by prateekgoel** [comment] 2018-10-08 06:32
@alansouzati So for the solution, shall we show the scrollbar in case the content exceeds the size of the container?

**Comment by alansouzati** [comment] 2018-10-08 16:51
yeah probably. But I'm more curious to understand why this is a problem only on safari.

**Comment by prateekgoel** [comment] 2018-10-09 04:45
@alansouzati I investigated the issue in Safari, Chrome and Firefox.
I am not able to reproduce the click on the displaced location. For me, the click is still on the button itself.
However, the buttons do overlap when the Layer container is not big enough to fit all buttons.
I believe we can just have a scrollbar appear when the content does not fit.

**Comment by alansouzati** [comment] 2018-10-09 06:37
let me try to reproduce this on my end

**Comment by prateekgoel** [comment] 2018-10-10 17:01
@alansouzati Did you get a chance to check on this?

**Comment by alansouzati** [comment] 2018-10-10 21:06
not yet Im sorry. I will keep you posted

**Comment by prateekgoel** [comment] 2018-10-11 06:44
Ok, no problem

**Comment by alansouzati** [comment] 2018-10-11 19:48
I'm not able to reproduce this issue with safari `Version 12.0 (13606.2.11)`.

I'm going to close this issue since I believe there is nothing to change on our end with regards to that.

We can reopen if we are able to reproduce it.

**Closed by alansouzati** 2018-10-11 19:48 UTC
Labels: 2.0, Bug :bug:, pre-v2-rc
