### ISSUE TITLE
Select cannot display 0 as a value, instead it displays blank

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#3985] opened 2020-04-20 23:26 UTC
### Expected Behavior

0 value ought to be displayed as "0", not blank.

### Actual Behavior

0 value displays as blank.

### URL, screen shot, or Codepen exhibiting the issue

Visit my [CodeSandbox](https://codesandbox.io/s/grommet-select-issue-with-0-value-owix5), or use the code below.

```
import React, { useState } from "react";
import { Grommet, grommet, Select } from "grommet";
import "./styles.css";

export default function App() {
  const options = [0, 1, 2, 3];
  const [value, setValue] = useState(options[0]);
  return (
    <Grommet full theme={grommet}>
      Instructions:
      <ol>
        <li>Toggle between grommet v2.12 and v2.13</li>
        <li>Reload the page</li>
        <li>Notice v2.13 displays blank, where v2.12 display 0</li>
      </ol>
      <Select
        options={options}
        value={value}
        onChange={({ option }) => setValue(option)}
      />{" "}
    </Grommet>
  );
}
```

### Steps to Reproduce

See CodeSandbox.

### Your Environment

- Grommet version: v2.12 compared with v2.13
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): W10 desktop.

**Comment by ShimiSun** [comment] 2020-04-21 22:08
Thanks for reporting and providing us constant feedback! the issue is fixed on the stable and will be available on the official next release.

**Closed** 2020-04-21 22:08 UTC
