### ISSUE TITLE
There's no way to show range input color range without the thumb

### ISSUE THREAD

**Issue by Cpt-Falcon** [grommet/grommet#6848] opened 2023-06-14 14:31 UTC
### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment] 2023-06-14 15:37
I'm assuming this is a duplicate of https://github.com/grommet/grommet/issues/6849

**Comment by jcfilben** [comment] 2023-06-16 15:27
Closing, I think this is a duplicate

**Closed by jcfilben** 2023-06-16 15:27 UTC
