### ISSUE TITLE
Carousel setting infinite to false does not work

### ISSUE THREAD

**Issue by ashik-f-ahmed** [grommet/grommet#1220] opened 2017-03-03 15:37 UTC
Setting the infinite attribute/property to Carousel component does not work.
### Expected Behavior

We need a way to stop this infinite loop
### Actual Behavior

Loops infinitly. Goes to last Carousel page when swiping left from first and vice-versa.
### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/carousel/examples/?autoplay=true&persistentNav=true&infinite=false

### Steps to Reproduce
 1. Add Carousel Component to any ReactJS page
 2. Change infinite to false
 3. Does not work when tested

### Your Environment

* Grommet version: 1.2.1
* Browser Name and version: Chrome / any broswer
* Operating System and version (desktop or mobile): Windows/Android/iOS

**Comment by ericsoderberghp** [comment] 2017-03-06 23:40
I cannot reproduce this in either of two ways:

1 - Go to initial example page and then turn off `infinite`. When it gets back to the first one, it stops playing.
2- Starting with the URL in the issue description above, the carousel plays through once and then returns to the beginning and stops.

If you are still able to reproduce the issue, can you further clarify the instructions on how to reproduce it?

**Comment by ashik-f-ahmed** [comment] 2017-03-09 12:05
Thanks @ericsoderberghp, so infinite works only with autoplay? 

We would like to stop swiping in the Carousel page from first to last and last to first.

Here is a sample: https://codepen.io/manjitp46/pen/jByemR?editors=1010

**Comment by manjitpandey** [comment] 2017-04-07 11:27
we have a fix for it when infinite is false. it will not go to to last to first slide and vice-versa

**Comment by manjitpandey** [comment] 2017-04-07 11:30
Here is the code fix for that to be done in Carousel.js file 

`    var children = this.props.children;
      var activeIndex = this.state.activeIndex;

      var numSlides = children.length;
      if(this.props.infinite){
      this.setState({
        activeIndex: (activeIndex + 1) % numSlides
      });
      }else if(activeIndex < children.length-1){
        this.setState({
        activeIndex: (activeIndex + 1) % numSlides
      });
      }``
/////
the above should in _slidenext function
/////////////
  var children = this.props.children;
 var activeIndex = this.state.activeIndex;
if(this.props.infinite){
      this.setState({
        activeIndex: (activeIndex + numSlides - 1) % numSlides
      });
      }else if(activeIndex > 0){
        this.setState({
        activeIndex: (activeIndex + numSlides - 1) % numSlides
      });
      }
//this should  in_slideprev function`

**Comment by tracybarmore** [comment] 2017-05-01 20:13
Hi @manjitpandey, I created this codepen that I believe solves your problem: http://codepen.io/anon/pen/bWWPVV

By indicating both infinite and autoplay are false, this allows the carousel to stop swiping once it has reached the end of all your slides.

**Comment by tracybarmore** [comment] 2017-05-01 20:14
I'm going to go ahead and close this issue since it seems fixed. If you still have questions or if the this issue is still a problem, please feel free to reopen. Thanks!

**Comment by dgennetten** [comment] 2017-05-17 20:54
This issue still exists. Verified on Win10/Edge.  This is a duplicate of #1327 I am working on solution.

**Closed** 2017-06-06 16:03 UTC
