### ISSUE TITLE
Select: Warning Maximum update depth exceeded.

### ISSUE THREAD

**Issue by versoworks** [grommet/grommet#5095] opened 2021-03-23 08:03 UTC
Updated to the latest v2.17 and am seeing the following warning when opening the `Drop` on a `Select` component;

`Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at InfiniteScroll (https://p86yu.csb.app/node_modules/grommet/es6/components/InfiniteScroll/InfiniteScroll.js:21:23)`

Here's a [Codesandbox ](https://codesandbox.io/s/elated-proskuriakova-p86yu?file=/src/App.js) reproducing the issue.

**Comment by ShimiSun** [comment] 2021-03-23 15:40
Thanks for reporting.

Notes: 
1. The warning appears when trying to open Select.
2. The `fill` prop on the Grommet isn't valid and throwing warning as well - `fill` could be removed.

**Comment by halocline** [comment] 2021-03-23 17:14
Investigation Update:
It looks like this might have been introduced in:
![Screen Shot 2021-03-23 at 11 13 10 AM](https://user-images.githubusercontent.com/1756948/112188791-ec5a6800-8bc8-11eb-987e-322be449ade8.png)

**Comment by ShimiSun** [comment] 2021-03-23 17:19
Thanks, @halocline. I'll tag @leossantiago for awareness and potential insights.

**Comment by halocline** [comment] 2021-03-23 18:02
These two useEffects seem to be entering into an infinite loop. Each have dependencies of `pendingLength` which gets set in each, which then satisfies the dependency condition as well as the checks within the useEffects. Seems like we need to add an additional condition around `pendingLength`.
![Screen Shot 2021-03-23 at 11 46 26 AM](https://user-images.githubusercontent.com/1756948/112195437-93da9900-8bcf-11eb-9284-43f1e3a99c21.png)

**Comment by leossantiago** [comment] 2021-03-24 18:06
Thanks for the inputs @ShimiSun and @halocline . I'll definitely take a look at this later today. Hope we can have a fix out ASAP 😄

**Comment by halocline** [comment] 2021-03-24 18:19
@leossantiago It looks like you originally had a check for `items.length === 0` which would prevent the infinite loop.

I believe with that approach, it assumes the caller would always be resetting their data to an empty array. Something just feels a bit off about assuming that is what the caller would want to do.

I was exploring some other approaches to see if we could avoid that assumption, but no luck so far.

We may need to put `items.length === 0` in as a patch to resolve the regression, and then explore working around the assumption later. @ShimiSun thoughts on this approach?

**Comment by ShimiSun** [comment] 2021-03-24 19:08
I'd be curious to understand why `items.length === 0` was removed from the first place, and which purpose did removing it served.

**Comment by halocline** [comment] 2021-03-24 19:17
Here's the related comment: https://github.com/grommet/grommet/pull/4936#discussion_r572226929

By reading the comment, I am not entirely clear. My interpretation is that it may have been a similar concern to not wanting to assume to which value items would be reset.

**Comment by halocline** [comment] 2021-03-25 23:58
@ShimiSun I was thinking about how this might have been caught sooner. Thinking a Select Jest test similar to this https://gist.github.com/halocline/d8d7d11aca684eaa624f840d6c703106 would be beneficial to add and might have identified this issue sooner.

**Comment by ShimiSun** [comment] 2021-03-26 17:31
@halocline , perfect - thank you, feel free to add the test, the tricky thing will be to simulate the `onMore` scenario and rest, but we should have examples for that. I'd love it if you can run the test on grommet 2.17 to verify you see the error, I'll be releasing 2.17.1 today with the fix for it.

**Comment by ShimiSun** [comment] 2021-03-26 21:49
The issue is fixed and released in grommet v2.17.1, Thank you for reporting!!

**Closed by ShimiSun** 2021-03-26 21:49 UTC
Labels: Bug :bug:

**Comment by serp777** [comment] 2021-10-08 19:25
this problem still exists on 2.18
