### ISSUE TITLE
Some components are not exposed/exported

### ISSUE THREAD

**Issue by valeporti** [grommet/grommet#5579] opened 2021-09-07 18:43 UTC
import { Notification } .. do not detect "notification"

### Expected Behavior

Get Notification component as told in the docs

### Actual Behavior

Typescript Error: 
Module '"grommet"' has no exported member 'Notification'

Also, if I go to *node_modules* , to the grommet folder, I can't find the component, weird because I see it in src in your page.

### Steps to Reproduce

Just try to import Notification Component

import { Notification } from 'grommet';

### Your Environment

- Grommet version: 2.17.5
- typescrypt 4.3.4
- yarn 1.22.5
- Operating System and version (desktop or mobile): Ubuntu 20

**Comment by halocline** [comment] 2021-09-07 19:35
@valeporti thank you for reporting. Notification has not been officially released -- however, it is available on [Grommet's Stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) for immediate use. Grommet will release v2.18.0 near the end of September and will include Notification at that time.

Since this is by design, I will close this issue. Please feel free to re-open or reply if any of the above is unclear.

**Closed by halocline** 2021-09-07 19:35 UTC
