### ISSUE TITLE
Bug of tiles when resizing window

### ISSUE THREAD

**Issue by zzl1** [grommet/grommet#302] opened 2016-01-19 02:49 UTC
See attachment.
[Bug of tiles when resizing window.pdf](https://github.com/grommet/grommet/files/95265/Bug.of.tiles.when.resizing.window.pdf)

**Comment by zzl1** [comment] 2016-01-19 03:00
### Tested browsers: 
Firefox 43.0.4 
Chromium V47.0.2526.80
Opera 34.0

### Grommet Version:
react: '^0.14.2',
grommet: '^0.5.2'

### Reproduce step
1.	Enter *http://172.17.0.2/test/* (browser window max)
2.	Resize window to make it like a smart phone.
3.	Resize window to original (max)
4.	Click arrow “-->”. The expected result is this arrow “-->” should be moved to the left of the page (as below). But it does not.

**Comment by jwijay** [comment] 2016-06-20 21:55
Closing this issue, since it is not reproducible when testing with the following steps in Chrome, Firefox, and Safari:
1) open Tiles page (see "Row" example)
2) resize window to mobile size
3) resize window to desktop size
4) click next arrow to show more tiles, and previous arrow now appears on left of tiles (instead of right arrow on right of tiles, as previously reported).

**Closed by jwijay** 2016-06-20 21:55 UTC
Labels: this sprint
