### ISSUE TITLE
[Medium App] URI creation is different between Chrome and IE11

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#126] opened 2015-08-06 15:20 UTC
Click on the Active Alert critical arc meter, the landing page has different url between chrome and IE11.
Chrome has all the required parameters: 'http://grommet.io/medium-app/activity?q=state%3AActive%20status%3AWarning'

![image](https://cloud.githubusercontent.com/assets/13039669/9115405/c0806410-3c13-11e5-83d1-e4470a0a4e60.png)

IE 11 does not have any parameters: "http://grommet.io/medium-app/activity?q="

![image](https://cloud.githubusercontent.com/assets/13039669/9115418/d1f7c328-3c13-11e5-995e-b6a8b3d98273.png)

**Comment by alansouzati** [comment] 2016-08-03 17:20
Medium app has been deprecated and I cannot reproduce this issue with Ferret or HC380. Closing the issue for now.

**Closed by alansouzati** 2016-08-03 17:20 UTC
