### ISSUE TITLE
InfiniteScroll isn't working on Edge via browserstack

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#2953] opened 2019-03-20 21:51 UTC
### Expected Behavior

https://storybook.grommet.io/?path=/story/infinitescroll--simple (Safari on MacOS)

scrolls past 50th item

### Actual Behavior

(Edge on Windows 10 via browserstack.com)

doesn't scroll past 50th item

**Comment by oorestisime** [comment] 2019-03-20 22:15
is this a duplicate of #2901 ?

**Comment by ShimiSun** [comment] 2019-03-28 04:11
@oorestisime yep, I think you are right.

**Closed by ShimiSun** 2019-03-28 04:11 UTC
Labels: Bug :bug:, browser related
