### ISSUE TITLE
Documentation is poor

### ISSUE THREAD

**Issue by funktr0n** [grommet/grommet#2475] opened 2018-11-22 15:45 UTC
The documentation is pretty poor guys...

### Expected Behavior

I should be able to read through the Documentation and learn how everything works without wanting to hit my head on the wall
### Actual Behavior

I read through incomplete samples that are poorly rendered and don't describe pretty basic use-cases

### URL, screen shot, or Codepen exhibiting the issue

A few samples...

#### You guys realize that you can specify borders for any of the four sides (in any combination) of a block-level element in CSS, right? How might I specify borders for `top`, `left`, and `right` but not bottom?  Not clear...

From https://v2.grommet.io/box

![image](https://user-images.githubusercontent.com/1269536/48911811-d514df80-ee41-11e8-92ba-faf83c83d152.png)

#### What is with the "count" value when you specify an object for `columns`?  Can you specify a number here or is it just "fit" or "fill"?  Why would you call this property "count"? Further, did you know that when you try to use the `areas` property in conjunction with specifying an object for the `columns` property that you get an error?  Why is that not written anywhere?

From https://v2.grommet.io/grid

![image](https://user-images.githubusercontent.com/1269536/48912018-7dc33f00-ee42-11e8-835c-7c9a59454bd9.png)

#### What exactly is going on here?  You expect me to want to use your library when you clearly have rendering issues?

https://v2.grommet.io/datatable

![image](https://user-images.githubusercontent.com/1269536/48912327-499c4e00-ee43-11e8-9b5e-a8d74b04e29c.png)

### Steps to Reproduce

Visit the links I provided and see for yourself

### Your Environment

I'm on Windows 10/Chrome

**Comment by alansouzati** [comment] 2018-11-22 17:56
Thanks for reporting this. We will look into fixing these issues. We recognize our site has its limitations and bugs. Just don’t let that prevent you from trying and engaging with us. I think Grommet is far from being perfect, but we appreciate contributions from the community. You seem to know what you are talking about so yeah please contribute to make it better. This is the right open source mentality.

**Comment by fredyagomez** [comment] 2018-12-21 15:47
@alansouzati  Hi Alan, maybe not a topic for this issue but what was the motivation to move to V2?. I am glad V1 still running and loved that one. V2 does not look like a step forward from what I have seen so far.

**Comment by alansouzati** [comment] 2018-12-21 18:32
https://github.com/grommet/grommet/wiki/Why-Grommet-2.0%3F

Curious as to why you don't think it is a step forward. Thanks for being honest about this.

**Comment by ShimiSun** [comment] 2019-02-21 00:10
We use `count` since that is the way css uses.
multiple borders is a valid enhancement
need to reproduce the error in question when using `columns` and `areas`

**Comment by ShimiSun** [comment] 2019-03-19 15:58
multiple borders is a valid `enhancment`

**Comment by aviemet** [comment] 2019-07-06 19:04
The docs suggest the following as a parameter for `columns` on Grid: `{"count": "fit", "size": "..."}`. Simply using that object as a value for `columns` produces an error.

You can visit [the code sandbox for Grid](https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=grid&module=%2Fsrc%2FGrid.js) to view the error by replacing the value of `columns` with `{"count": "fit", "size": "small"}`. 

Been playing around in the code sandbox but still not getting how this value is to be used. The `areas` prop is similarly confusing. Doesn't storybook have an option to view the source which describes the layout? It would be very helpful to be able to see some source examples which are less trivial than those shown in the docs. There are some interesting uses on your storybook which if I could see the source would go a long way in helping me understand how to use the component.

**Comment by elpagano** [comment] 2019-12-13 14:08
how can I put lines between the columns of a table

**Comment by ericsoderberghp** [comment] 2019-12-16 23:28
> how can I put lines between the columns of a table?

Via the `border` property of DataTable. https://v2.grommet.io/datatable#border

**Comment by elpagano** [comment] 2019-12-17 11:42
Yes ok but how? there are no examples?
Can you put vertical lines? because in the documentation it only says horizontal.
I solved it by putting a box with a fill = "vertical" border = {{size: "xsmall", side: "left"}} but it's not an elegant solution

**Comment by ShimiSun** [comment] 2020-04-08 21:37
> Box - multiple borders is a valid `enhancement`
> 
> Grid - on https://v2.grommet.io/grid? there is a built-in example of using areas with column object and I wasn't able to reproduce the error in the description, feel free to share more information on the GRid you used that reproduced the error, we do need to document it if it still exists.
> 
> Datatable - The Datatable layout problem on the grommet-site is fixed.

Reviewing this issue, the multiple border enhancement request was implemented during Hacktoberfest I believe, see the updated docs https://v2.grommet.io/box#border

The other errors and warnings are fixed and no longer reproducible.

The last issue raised on the documentation of Datatable `border` has a fix on #2475

Thank you for reporting this issue, we came a long way with our documentation since v2 was released, and we are continuing to look for ways to improve. I'll be closing this issue, but feel free to file any new issues that can help us improve.

**Closed by ShimiSun** 2020-04-08 21:37 UTC
Labels: documentation :memo:, enhancement, needs attention
