### ISSUE TITLE
In Edge browser (13), clicking Menu icon triggers unhandled error.

### ISSUE THREAD

**Issue by johnnyvcn** [grommet/grommet#1197] opened 2017-02-17 06:12 UTC
In Edge browser (13), clicking Menu icon triggers unhandled error.

### Expected Behavior

No error happens.

### Actual Behavior

JS error happens.

### Steps to Reproduce
 1. In Edge browser, press F12 to open developer tool, then go to [https://grommet.github.io/hpe/docs/menu/examples?responsive=true&icon=true&label=true&i-anchors=true](https://grommet.github.io/hpe/docs/menu/examples?responsive=true&icon=true&label=true&i-anchors=true).
 2. Click the menu icon besides the label 'Label', then select 'First action'.
 3. In developer tool Console, error is printed: 
     SCRIPT438: Object doesn't support property or method 'focus' 
 
However, in step 2, if I click the menu label ('Label'), no error happens.

I'm an HPE Software employee, developing a new UI for our product based on grommet. We have to support Edge. In our new UI, this Menu error prevents our subsequent actions from functioning. 

### Your Environment

* Grommet version: 1.2.1 and latest
* Browser Name and version: Edge 13
* Operating System and version (desktop or mobile): Windows 10

**Comment by tracybarmore** [comment] 2017-02-28 21:35
Hey @johnnyvcn, I can't seem to replicate this issue on BrowserStack Edge 14 and 13. Can you verify this is still an issue? Thanks!

**Comment by alansouzati** [comment] 2017-03-23 23:46
hey @johnnyvcn any updates on this?

**Comment by tracybarmore** [comment] 2017-05-01 18:55
Hey @johnnyvcn, I'm going to go ahead and close this issue since we could not replicate the issue. If you still have questions or are able to reproduce the issue, please feel free to reopen. Thanks!

**Closed** 2017-05-01 18:56 UTC
