### ISSUE TITLE
Grommet 'Value' component must have a prop to make the numerical part 'not bold'

### ISSUE THREAD

**Issue by kokanek** [grommet/grommet#1673] opened 2017-10-10 06:47 UTC
### Expected Behavior
When we use the Value component, we should be able to pass a prop and make the numerical part 'not bold and prominent' which is bold by default

### Actual Behavior
Currently, the component shows numerical part bold by default and there is no way to control it.

### Steps to Reproduce
 1.  Use the 'Value' component.
 2.  Pass it a 'value' prop and a 'units' prop.
 3.  The value part appears in bold.

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by dgennetten** [comment] 2017-11-02 21:03
This is by design. Grommet is a fairly opinionated environment, imposing certain design patterns for consistency and usability.  What is application and reasoning behind wanting the deemphasis?

**Comment by dgennetten** [comment] 2017-11-07 21:30
Closing this issue as it is 'as designed'. Please let us know if you need further assistance regarding this.

**Closed by dgennetten** 2017-11-07 21:30 UTC
Labels: needs attention

**Comment by tobias-flitsch** [comment] 2017-11-15 23:46
Then what is the suggestion on this enhancement request to provide a `strong` property to value, similar to Heading that allows this to be controlled. Is the suggestion to use inline text instead?

In an application that we are building, we want to not draw attention to the value as it is not the most important element on the page. That means having the same text size and "regular" font weight: 

![image](https://user-images.githubusercontent.com/4466053/32866350-1b6c8fa0-ca1c-11e7-9bbd-e2823115c265.png)

Or: https://codepen.io/tobias-flitsch/pen/MOEJBZ/
