### ISSUE TITLE
Position of modal container is in conflict when responsive flag is enabled on Layer component

### ISSUE THREAD

**Issue by aga5tya** [grommet/grommet#3639] opened 2020-01-02 07:38 UTC
When on mobile responsive view, the modal container does not show up if the user has scrolled to some extent already. This happens due to the container position being relative while it is expected to be fixed.

Also, this could be browser specific issue as it seems to work as expected in firefox not able to reproduce in codesandbox. Given the styles on container, making container position to relative does not make sense to me.

### Expected Behavior

The modal should show work irrespective of the scroll position while on mobile with responsive on Layer enabled.

### Actual Behavior

If the user has significantly scrolled, the modal does not show up.

### Your Environment

- Grommet version: v2.9.0
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): Desktop Responsive Mode

**Comment by ericsoderberghp** [comment] 2020-03-16 19:32
I cannot reproduce this with Safari, Chrome, or Firefox on Mac OSX 10.15.3 (19D76). Can you provide some more details on how to reproduce this?

**Comment by ShimiSun** [comment] 2020-09-23 20:59
From @MikeKingdom 
>@ShimiSun I haven't been able to reproduce this issue either. My opinion is we should close this PR and issue unless someone has an example that can show the problem.

I'll be closing the issue, feel free to reopen with more details for reproduction if still  relevant.

**Closed by ShimiSun** 2020-09-23 20:59 UTC
