### ISSUE TITLE
Image component  Failed to construct 'Image': Please use the 'new' operator

### ISSUE THREAD

**Issue by bemineni** [grommet/grommet#2177] opened 2018-08-16 00:56 UTC
import logo from '../../img/logo.svg'
<Image src={primary_logo_small}/>

Uncaught TypeError: Failed to construct 'Image': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

The same works with
<img src={logo}>

I even tried with png

### Expected Behavior
Image component should load the image 

### Actual Behavior
react-hot-loader.development.js:675 Uncaught TypeError: Failed to construct 'Image': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at ProxyFacade (react-hot-loader.development.js:675)
    at ReactCompositeComponent.js:303
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:302)
    at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js:277)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:185)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:234)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:701)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:520)

### URL, screen shot, or Codepen exhibiting the issue

Dont know how to load images in this code pen

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:grommet@1.11.0 
* Browser Name and version: Chrome 67.0.3396.99 (Official Build) (64-bit)
* Operating System and version (desktop or mobile):

**Comment by alansouzati** [comment] 2018-10-11 18:22
I dont think this is related to grommet. there is nothing we do on our end to load images. please clarify how to reproduce the issue.

**Comment by ShimiSun** [comment] 2019-01-04 21:44
Hi, I'm closing this issue since I believe nothing needs to be changed on our end. 
Please feel free to reopen it with a way to reproduce the issue, in case you think otherwise

**Closed by ShimiSun** 2019-01-04 21:44 UTC
Labels: waiting

**Comment by darwinarugayvpi** [comment] 2021-03-01 05:51
Same issue, when I created a component and received the 'src' attribute as a props this cause me an issue using nextjs Image

**Comment by amanmishra7ave** [comment] 2022-08-06 03:44
react-dom.development.js:14985 Uncaught TypeError: Failed to construct 'Image': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at discreteUpdates$1 (react-dom.development.js:22420:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)


Can anyone help me to resole this error

**Comment by jcfilben** [comment] 2022-08-09 16:17
Hi @amanmishra7ave can you share a codesandbox that reproduces the issue? Here is a template https://codesandbox.io/s/m7mml8l0zj

**Comment by cosmicknox** [comment] 2022-10-18 11:57
Seem like he needed to import Image from next/image

**Comment by mozammilkarim** [comment] 2023-01-23 16:43
You should try to rename the files, as using Img or Image or img often leads to errors because we accidentally start to call system files.
Just Renaming my files worked for me.
