### ISSUE TITLE
DataTable into a Box with scrolling

### ISSUE THREAD

**Issue by atoy40** [grommet/grommet#3065] opened 2019-04-29 14:27 UTC
Datatable scrolling

### Expected Behavior

When I reach the end of displayed data it must display more data

### Actual Behavior

My datatable is inside a box with an overflow "auto" so the scrollbar are not on "window" but on the Box. But when I reach the bottom of the Box (and so the end of displayed data), it seems it's not detected and data are not appended at the end. I've seen in the source code that the InfiniteScroll componement has a hardcode scrollableAncestor set to "window". May be it's the key of this problem ? The InfiniteScroll marker is render properly has an empty table row.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/q60y69oyj

### Your Environment

- Grommet version: 2.6.5
- Browser Name and version: chrome 73.0.3683.103
- Operating System and version (desktop or mobile): ubuntu 18.10

**Comment by ShimiSun** [comment] 2019-04-29 15:40
Hi @atoy40 , will you be able to share a codesandbox that reproduces the problem?

**Comment by atoy40** [comment] 2019-04-29 15:41
Yes, I'm working on :) but the problem seems to be because my all layout fit into a "filled" box.

**Comment by atoy40** [comment] 2019-04-29 20:35
https://codesandbox.io/s/q60y69oyj

Here is a code sandbox demonstrating the problem. If you go at the bottom, it never load the missing values. If you remove the fill={true} of the first Box, it works (but the layout is not the desired one)

Anthony.

**Comment by ericsoderberghp** [comment] 2019-04-29 20:44
1) I think you want the Box containing the right panel, with the Hello World Heading, to have `flex={true}` instead of `fill={true}`. I think you want the right panel to take all remaining space in the containing Box, which is different than attempting to fill all of the containing Box.
2) I think you want `flex={false}` on the Box containing the DataTable.

**Comment by atoy40** [comment] 2019-04-29 21:46
@ericsoderberghp whooo, just thoses two fixes and the infinitescroll works ! :) thanks ! So, what in my sample prevent datatable to detect the scroll end marker ?
Anthony

Thanks again :)

**Comment by ShimiSun** [comment] 2019-04-30 04:25
I'm labeling this one as a `discussion` to see if there is anything we can improve on the documentation to avoid misuse of the component.

**Comment by AndreyKovanov** [comment] 2019-05-15 11:55
Hi @ericsoderberghp 
what conditions should we follow to scroll works properly?

In our case, we try to use DataTable into Grid. Link to a sandbox:
https://codesandbox.io/s/92m58kj3wr?fontsize=14

**Comment by jcfilben** [comment] 2021-12-17 16:33
Going to close this since an explanation and fix was provided above. This is an older issue so I think if changes are still needed to clarify the DataTable documentation they can be brought up in a new issue.

**Closed by jcfilben** 2021-12-17 16:33 UTC
Labels: discussion, DataTable
