### ISSUE TITLE
IE11: In page footer is too high, covering page content

### ISSUE THREAD

**Issue by mirzaooo** [grommet/grommet#1058] opened 2016-11-15 15:26 UTC
### Expected Behavior
Footer should be down on the bottom

### Actual Behavior
Footer is in the middle of the page, covering page content 
### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/mirzao/pen/pNyXwM

### Steps to Reproduce
 1. put an argument in Box component: full={true}
 2. open page in IE
 3. full={true} is adding css classes which have different behavior in IE (grommetux-box--full and grommetux-box--full-vertical are setting height: 50vh in IE) 
### Your Environment
* Grommet version: 0.6.9 and the latest
* Browser Name and version: IE 11
* Operating System and version (desktop or mobile): Windows 10

**Comment by mirzaooo** [comment] 2016-11-15 15:36
### Expected Behavior
Footer should be down on the bottom

### Actual Behavior
Footer is in the middle of the page, covering page content 
### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/mirzao/pen/pNyXwM

### Steps to Reproduce
 1. put an argument in Box component: full={true}
 2. open page in IE
 3. full={true} is adding css classes which have different behavior in IE (grommetux-box--full and grommetux-box--full-vertical are setting height: 50vh in IE) 
### Your Environment
* Grommet version: latest
* Browser Name and version: IE 11
* Operating System and version (desktop or mobile): Windows 10

**Comment by ericsoderberghp** [comment] 2016-11-16 16:46
Agreed that the IE specific styling is causing problems. We'll evaluate.

**Comment by alansouzati** [comment] 2016-11-22 23:31
I'm trying to reproduce this issue. I open the codepen in IE11 and it works. Can you be more explicit on what is breaking?

The 50vh height is there but it will get overwritten by the min-height which is 100vh. 

If you don't set the height IE11 will break alignment. I'm happy to investigate this further, but I would need more details as I cannot reproduce the overlap in the codepen using ie11.

Can you provide a screenshot?

**Comment by mirzaooo** [comment] 2016-11-23 08:00
@alansouzati if you're opening my CodePen it's because of this in CSS: .grommetux-box--full {
  height: 100% !important;
}
So check now without this code: http://codepen.io/mirzao/pen/pNyXwM

**Comment by alansouzati** [comment] 2016-11-29 22:06
I would be careful with using nested full attributes. It is designed to be used only at the top level structure as it uses the virtual width/height.

I believe this is what you are trying to achieve:

http://codepen.io/alansouzati/pen/jVaOgP?editors=0010

Sidebar also uses the VH attribute and it will not working properly if you have other stuff before or after.

I'm closing this issue as I believe there is nothing to fix. Feel free to reopen if you still think there is something broken.

**Closed** 2016-11-29 22:06 UTC
