### ISSUE TITLE
Custom Theme not applied (Grommet & NextJS)

### ISSUE THREAD

**Issue by kolbis** [grommet/grommet#6006] opened 2022-03-19 09:19 UTC
I have an application written in NextJS 
I am trying to apply custom theme, yet no changes are being applied.

I must be doing something wrong.

### Expected Behavior

I defined the theme:
```
const hoozTheme = deepMerge(hpe,{
        global:{
            colors:{
                focus: 'neutral-1'
            },
        },
        button: {
            default: {},
            primary: {
                color: 'red'
            }
        }
    }
)
```

applied it as so
```
port default function App({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Grommet theme={themes.hoozTheme}>
        <Web3ReactProvider getLibrary={getLibrary}>
          <Component {...pageProps} />
        </Web3ReactProvider>
      </Grommet>
    </Provider>
  );
}
```

theme is not applied.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: latest
- Browser Name and version: any
- Operating System and version (desktop or mobile): any

**Comment by ShimiSun** [comment] 2022-03-19 18:02
Hello, thanks for reaching out.
Can you please add a more complete example of how you are trying to load the theme?
For example, it is not clear how you are importing the hpe theme, what is the `themes` object you are referring to, and what is your file structure.
We have done many POCs of NextJS + Grommet with no issues on theme-ing, take a look at the boilerplate and make sure your Grommet component is loaded correctly https://github.com/grommet/nextjs-boilerplate
Also, for troubleshooting, try to `console.log` the value of `themes.hoozTheme` right before injecting it into the theme prop, it will help you understand whether the theme is passed to the prop properly.

**Comment by jcfilben** [comment] 2022-03-28 15:30
I'm going to close this, but feel free to re-open and comment if the issue is still happening.

**Closed by jcfilben** 2022-03-28 15:30 UTC
Labels: waiting

**Comment by kolbis** [comment] 2022-04-02 14:33
@jcfilben @ShimiSun 
Sorry for the delayed response. 
I still have the issue. 

for simplicity, i changed the code to the following, which still does not apply:

```
export default function App({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Grommet
        theme={{
          global: {
            colors: { doc: "#ff99cc" },
          },
        }}
      >
        <Web3ReactProvider getLibrary={getLibrary}>
          <Component {...pageProps} />
        </Web3ReactProvider>
      </Grommet>
    </Provider>
  );
}
```

This is my nextjs _document.tsx file:

```
import Document from "next/document";
import { ServerStyleSheet } from "styled-components";
import React from "react";

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
    } finally {
      sheet.seal();
    }
  }
}

```

No styles are applied.

**Comment by kolbis** [comment] 2022-04-03 15:24
Reverting back with conclusions:
I overriden the theme elsewhere in the code.

Issue can be closed.
Thanks.
