### ISSUE TITLE
Allow setting the DateTime component read only

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet#1341] opened 2017-05-04 16:34 UTC
Currently, there is no way to set the DateTime component read only or disabled.

### Expected Behavior

The component should allow setting it to read only or disabled so the users should not have the ability to alter the data.

### Actual Behavior

Instead, it allows setting the value to a new value.

### Your Environment

* Grommet version: "grommet": "^1.3.0",
* Browser Name and version: Chrome  58.0.3029.96 (64-bit)
* Operating System and version (desktop or mobile): Windows 10, desktop

**Comment by przytrzask** [comment] 2017-07-02 19:34
Can you consider one more scenario in this case? Since grommet doesn't mask datetime format  I would like to get rid of checking what user types in the input and get this component to behave like input is disabled but being changing date still possible. It could work when you specify both onChange and disabled prop on DateTime component .You can simply reproduce it by manually adding disabled attribute on <input"> tag

**Comment by alansouzati** [comment] 2017-07-07 23:26
Grommet does not recommend disabled input fields. But you can definitely achieve that by removing the DateTime when read-only and replace it with a native input with read-only attribute set.

It is confusing to show the icon in the right when it is ready only.

I'm closing this issue since I believe there is nothing to be fixed on Grommet. We can continue the discussion and re-open in case we decide to fix anything.

**Closed by alansouzati** 2017-07-07 23:26 UTC
