### ISSUE TITLE
Heading doesn't respect "small" responsive theme settings

### ISSUE THREAD

**Issue by sandersoeteman** [grommet/grommet#3161] opened 2019-06-14 12:53 UTC
I'm trying to have a heading that is smaller on phones (small) than on tablets and desktop (medium & large). The size and height specified in the theme are respected for medium and large breakpoints, but not for the small breakpoint. It seems to always default to a global setting.
Tested on FF and Chrome.

See codesandbox for a demonstration: https://codesandbox.io/s/92rzl96r9y

**Comment by oorestisime** [comment] 2019-06-24 08:39
Hey so i had a look at the code. it seems the idea is to not to reduce the size property from medium to small etc depending on the screen size but the heading level. which seems to be working.
Maybe we should mention this in the docs?

**Comment by sandersoeteman** [comment] 2019-06-24 09:45
Disagree. The heading level communicates hierarchy in the page. It is a constant for the instance and should not be changed depending on the screen width.

**Comment by oorestisime** [comment] 2019-06-24 10:13
Yeah true. I am trying to find the rationale behind this. i might be even wrong actually and the level doesn't change. I read the code a week ago and forgot to answer here so i ll need to recheck.

**Comment by jackielfu** [comment] 2019-10-08 16:28
any update on this? i'm getting the same issue in version 2.7.8.

**Comment by sandersoeteman** [comment] 2019-10-08 16:49
Sorry, no. I've decided to implement another system instead.

**Comment by ShimiSun** [comment] 2019-10-08 21:55
The `level` prop is communicating the hierarchy from the responsive aspect, each `level` has different `size` values and the value can be determined using the size `prop` (defaults to 'medium').
The `size` prop doesn't control the responsive behavior; if the user assigns `size="small" ` and using responsive behavior, the size will remain `small` though the `level` will change according to the global breakpoints definitions from the theme. https://github.com/grommet/grommet/blob/7efd28655787d4f8aefc2ffaa584227db3c7855a/src/js/themes/base.js#L131

For further customizations on `size`, you could always create your own responsive behavior by using `<ResponsiveContext />`.

For now, I'm putting an action item to improve documentation and maybe state on the storybook example that the Headings(s) displayed are according to the screen size, and `level` values may vary according to the responsive behavior.
One more action item is to explore the `Math.min(props.level + 1, 4)` behavior when the user defines level 5 and 6. https://github.com/grommet/grommet/blob/7efd28655787d4f8aefc2ffaa584227db3c7855a/src/js/components/Heading/StyledHeading.js#L27 

@jackielfu would you like to share your issue so we can see what else is missing in this area?

**Comment by jackielfu** [comment] 2019-10-09 16:03
hey shimi!

our app is purely mobile-web, so i'm working only with the `small` breakpoint. i'm attempting to change the `size` and `lineHeight` of `<Heading level={1} />` using this theming option: 

```{
  "1": {
    "font": {},
    "small": {
      "size": "34px",
      "height": "40px",
      "maxWidth": "816px"
    },
  },```

the expected behavior is that by changing `theme.heading.level.1.size` to say, `20px`, would change the `<Heading level={1} />` at the small breakpoint to `20px`, but it continues to default to the standard `34px`.

**Comment by bklmustapha** [comment] 2020-01-02 14:40
I have the same issue, on responsive on small breakpoint the heading do not take his small font-size and line-height value but he take the medium value of another heading,
example : for heading level 1 on small breakpoint it will take the medium value of heading level 2 and for heading level 2 on small breakpoint he weill take the value of medium of level 3.

See codesandbox for demonstration and compare on inspect vs config theme [https://codesandbox.io/s/rough-sea-futx9](https://codesandbox.io/s/rough-sea-futx9)

**Comment by buoyantair** [comment] 2020-07-01 14:54
Looks like this issue has been fixed already, @ShimiSun close?

**Comment by ShimiSun** [comment] 2020-07-01 17:42
Great, thanks for confirming @buoyantair !

**Comment by IanKBovard** [comment] 2020-09-29 17:09
I don't believe it's because heading doesn't respect the theme, it's because heading changes its level on resize which causes it to pull from a different part of theme. 
The question is should we leave the current functionality of heading(it sizes down a level on lower widths) or remove this functionality and rely on theme exclusively. I like the second option, but that could cause a lot of backwards compatibility issues.

**Comment by ShimiSun** [comment] 2020-10-02 13:55
In the constraint of maintaining backward compatibility, I think the fix above should have taken care of the issue.
We have been waiting for a confirmation for a few months now, so I'll be closing this issue, though feel free to elaborate more and reopen if the issue still exists.

**Closed by ShimiSun** 2020-10-02 13:55 UTC
Labels: Bug :bug:
