### ISSUE TITLE
DataTable - Warning: Failed prop type: Invalid prop `background` supplied to `DataTable`, expected one of type [string].

### ISSUE THREAD

**Issue by JacintoJT** [grommet/grommet#7075] opened 2023-12-28 09:50 UTC
I have passed a object with the fields header, body and footer to the background prop and I am having this Warning:

Warning: Failed prop type: Invalid prop `background` supplied to `DataTable`, expected one of type [string].

I expect no warning because object is a valid type for DataTable background

- Grommet version: 2.34.2 or 2.19.2 (both i have tested)
- Browser Name an version: Google Chrome 120.0.6099.109 (Build oficial) (64 bits)
- Operating System and version (desktop or mobile): Ubuntu 23.04

**Comment by jcfilben** [comment] 2024-01-02 18:07
Hi @JacintoJT can you share a [codesandbox](https://codesandbox.io/s/m7mml8l0zj) that reproduces the issue?

**Comment by jcfilben** [comment] 2024-01-29 18:10
Closing, unable to reproduce the issue. Feel free to re-open with a codesandbox example that demonstrates the issue.

**Closed by jcfilben** 2024-01-29 18:10 UTC
Labels: waiting
