### ISSUE TITLE
Select Box is not responsive in Mobile view

### ISSUE THREAD

**Issue by naveenrj98** [grommet/grommet#4130] opened 2020-05-30 11:43 UTC
### Expected Behavior

Select box and Arrow down icon inside the select button should be responsive in mobile view and also arrow icon should expand with select button when we make select button size small/any.

### Actual Behavior
when we expands/increase/reduce the size of the select button, only border is responding, but the arrow-down icon inside the Select button is not expanding with give size. In Mobile view, getting some odd-view of the select button

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: v1
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): win-10

**Comment by ShimiSun** [comment] 2020-06-01 20:02
The issue is fixed on Select v2. we are no longer maintaining to v1.

**Closed by ShimiSun** 2020-06-01 20:02 UTC

**Comment by naveenrj98** [comment] 2020-06-02 02:03
How we can migrate from grommet v1 to grommet v2

**Comment by ShimiSun** [comment] 2020-06-02 15:07
Yo can start with https://github.com/grommet/grommet/wiki/2.0-Migration-Guide
