### ISSUE TITLE
SSR (Next.js) build fails when using Grommet/Stable branch

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#3914] opened 2020-04-02 18:58 UTC
### Expected Behavior

SSR (Next.js) build should complete successfully.

### Actual Behavior
Summary: Build fails
As Next.js attempts to build, it proceeds to pre-render each page in the site. During this step, logs report an "Error occurred prerendering page" & "ReferenceError: document is not defined" for each page in the site. The end result is a failed build.

Notes: 
- Error first occurred 5:30 MDT
- Build successfully completes when using Grommet v2.12.0
- [Error message documentation](https://github.com/zeit/next.js/blob/master/errors/prerender-error.md)
- Hunch: Grommet is trying to reference `document` during SSR which doesn't exist since `document` is client side only.
- Potentially related to the `ContainerTargetContext` depending on `document` introduced in [this PR](https://github.com/grommet/grommet/pull/3883)

### URL, screen shot, or Codepen exhibiting the issue

Screenshot of log (full log in following comment)
![Screen Shot 2020-04-02 at 10 11 17 AM](https://user-images.githubusercontent.com/1756948/78290831-92f1b880-74e1-11ea-855d-84a58aa34918.png)

### Steps to Reproduce

1. Next.js + Grommet stable branch as dependency (Here's a quick repo I set up as an [environment to reproduce](https://github.com/halocline/grommet-nextjs-starter))
2. 
```
yarn
yarn build
``` 

### Your Environment

- Grommet version: https://github.com/grommet/grommet/tarball/stable

Next.js - v9.1.2

- Browser Name and version: N/A
- Operating System and version (desktop or mobile): N/A

**Comment by halocline** [comment] 2020-04-02 19:00
5:30:29 PM: Build ready to start
5:30:31 PM: build-image version: 2dbd444fcdce00cf06325060a8238d5ae3e86774
5:30:31 PM: build-image tag: v3.3.7
5:30:31 PM: buildbot version: bd31cf433d2d899021d41733f271c39fdf2f8880
5:30:32 PM: Fetching cached dependencies
5:30:32 PM: Starting to download cache of 229.9MB
5:30:33 PM: Finished downloading cache in 1.271218109s
5:30:33 PM: Starting to extract cache
5:30:46 PM: Finished extracting cache in 13.21818613s
5:30:46 PM: Finished fetching cache in 14.555191645s
5:30:46 PM: Starting to prepare the repo for build
5:30:47 PM: Preparing Git Reference pull/629/head
5:30:48 PM: Found Netlify configuration file netlify.toml in site root
5:30:48 PM: Found Netlify configuration file(s). Overriding site configuration
5:30:48 PM: Starting build script
5:30:48 PM: Installing dependencies
5:30:48 PM: Started restoring cached node version
5:30:53 PM: Finished restoring cached node version
5:30:54 PM: v10.19.0 is already installed.
5:30:55 PM: Now using node v10.19.0 (npm v6.13.4)
5:30:55 PM: Attempting ruby version 2.6.2, read from environment
5:30:56 PM: Using ruby version 2.6.2
5:30:57 PM: Using PHP version 5.6
5:30:57 PM: Started restoring cached node modules
5:30:57 PM: Finished restoring cached node modules
5:30:57 PM: Started restoring cached yarn cache
5:30:57 PM: Finished restoring cached yarn cache
5:30:57 PM: Installing NPM modules using Yarn version 1.17.0
5:30:58 PM: yarn install v1.17.0
5:30:58 PM: [1/4] Resolving packages...
5:31:00 PM: [2/4] Fetching packages...
5:31:31 PM: info fsevents@2.1.2: The platform "linux" is incompatible with this module.
5:31:31 PM: info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
5:31:31 PM: info fsevents@1.2.12: The platform "linux" is incompatible with this module.
5:31:31 PM: info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
5:31:31 PM: [3/4] Linking dependencies...
5:31:31 PM: warning " > aries-core@1.0.0" has unmet peer dependency "react@^16.12.0".
5:31:31 PM: warning " > aries-core@1.0.0" has unmet peer dependency "react-dom@^16.12.0".
5:31:31 PM: warning " > aries-core@1.0.0" has unmet peer dependency "styled-components@^5.0.0".
5:31:31 PM: warning "workspace-aggregator-3aa20fdc-f805-4fe3-bc20-1589ac65ccc5 > aries-core > @storybook/addon-storysource@5.3.17" has unmet peer dependency "@storybook/source-loader@*".
5:31:31 PM: warning "workspace-aggregator-3aa20fdc-f805-4fe3-bc20-1589ac65ccc5 > aries-core > styled-components@5.0.1" has unmet peer dependency "react-is@>= 16.8.0".
5:31:31 PM: warning "workspace-aggregator-3aa20fdc-f805-4fe3-bc20-1589ac65ccc5 > aries-site > react-ga@2.7.0" has unmet peer dependency "prop-types@^15.6.0".
5:31:31 PM: warning "workspace-aggregator-3aa20fdc-f805-4fe3-bc20-1589ac65ccc5 > aries-core > @storybook/addon-actions > @storybook/api@5.3.17" has unmet peer dependency "regenerator-runtime@*".
5:32:02 PM: [4/4] Building fresh packages...
5:32:11 PM: success Saved lockfile.
5:32:11 PM: Done in 72.47s.
5:32:11 PM: NPM modules installed using Yarn
5:32:11 PM: Started restoring cached go cache
5:32:11 PM: Finished restoring cached go cache
5:32:11 PM: unset GOOS;
5:32:11 PM: unset GOARCH;
5:32:11 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
5:32:11 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
5:32:11 PM: go version >&2;
5:32:11 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
5:32:11 PM: go version go1.12 linux/amd64
5:32:11 PM: Installing missing commands
5:32:11 PM: Verify run directory
5:32:11 PM: Executing user command: yarn --cwd aries-site export
5:32:11 PM: yarn run v1.17.0
5:32:12 PM: $ yarn build && next export
5:32:12 PM: $ next build
5:32:13 PM: Creating an optimized production build...
5:32:16 PM: > Using external babel configuration
5:32:48 PM: Compiled successfully.
5:32:48 PM: Automatically optimizing pages...
5:32:57 PM: Error occurred prerendering page "/components/checkbox". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:57 PM: Error occurred prerendering page "/components/button". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:57 PM: Error occurred prerendering page "/components/header". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:57 PM: Error occurred prerendering page "/components/grid". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:57 PM: Error occurred prerendering page "/components". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:57 PM: Error occurred prerendering page "/components/accordion". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:57 PM: Error occurred prerendering page "/components/footer". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:57 PM: Error occurred prerendering page "/components/radiobuttongroup". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:57 PM: Error occurred prerendering page "/components/layer". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:57 PM: Error occurred prerendering page "/components/maskedinput". Read more: https://err.sh/next.js/prerender-error:
5:32:57 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/menu". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/main". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/stack". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/select". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/rangeinput". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/textinput". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/extend/api-chomp". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/textarea". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/extend/designer". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/tabs". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/extend/audience". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/anchor". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/components/box". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/extend/global-sidebar". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:58 PM: Error occurred prerendering page "/extend/docs". Read more: https://err.sh/next.js/prerender-error:
5:32:58 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/extend/table-topper". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/foundation/human-centered". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/foundation/content". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/extend". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/feedback". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/foundation/color". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/extend/images". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/foundation/philosophy". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/foundation". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/foundation/icons". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/foundation/principles". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/foundation/typography". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/foundation/our-brand". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/templates/cards". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/templates/dashboards". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/templates". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/templates/forms". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: Error occurred prerendering page "/templates/lists". Read more: https://err.sh/next.js/prerender-error:
5:32:59 PM: ReferenceError: document is not defined
5:32:59 PM: > Build error occurred
5:32:59 PM: Error: Export encountered errors
5:32:59 PM:     at _default (/opt/build/repo/node_modules/next/dist/export/index.js:19:811)
5:32:59 PM:     at process._tickCallback (internal/process/next_tick.js:68:7)
5:32:59 PM: error Command failed with exit code 1.
5:32:59 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
5:32:59 PM: error Command failed with exit code 1.
5:32:59 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
5:32:59 PM: Skipping functions preparation step: no functions directory set
5:33:00 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
5:32:59 PM: Caching artifacts
5:32:59 PM: Started saving node modules
5:32:59 PM: Finished saving node modules
5:33:00 PM: Shutting down logging, 15 messages pending

**Comment by ShimiSun** [comment] 2020-04-02 19:54
Thanks for reporting!
I'm wondering if its a nextjs issue or an SSR in general, it will be interesting to see if this one reproduces on a Gatsby project.

**Comment by brentropy** [comment] 2020-04-02 22:03
@ShimiSun I am not using SSR in my project. It looks like I broke it :grimacing: I will look in to it right now.

**Comment by brentropy** [comment] 2020-04-02 22:59
I just did a quick test with gatsby and it builds fine. I will do a little more digging later. I haven't every done anything with Next.js, but I can give that shot. Not sure what would really be different in terms of SSR issues though.

**Comment by brentropy** [comment] 2020-04-03 05:04
I was able to reproduce with nextjs and it was my commit that introduced the issue. I will have a PR up shortly.

**Comment by ShimiSun** [comment] 2020-04-09 17:30
Thank you @halocline & @brentropy for the quick turnaround! the issue is fixed.

**Closed by ShimiSun** 2020-04-09 17:30 UTC
