### ISSUE TITLE
Layer component resonsive mobile

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#699] opened 2016-07-14 07:12 UTC
When you open Layer dialog component in desktop view works as expected. 

### Expected Behavior
On mobile screen size it should either appear as dialog over content or "page should scroll to the top".

### Actual Behavior
When you open Layer dialog component in mobile - phone view size it is attached to the top and initially "not visible".

### Steps to Reproduce
 1. Open http://www.grommet.io/docs/develop/layer on the phone
 2. Click confirmation button (You will be presented with "empty screen")
 3. Scroll to the top to see layer content 

To work around this I have to set window.scroll...(0,0) on mobile click.

**Comment by alansouzati** [comment] 2016-07-14 17:27
Hi @primozs thanks for the detailed information on the issue.

I believe this one is a good candidate for a PR.

I agree with scroll top fix if `responsive=small`.

**Comment by primozs** [comment] 2016-07-18 16:22
Hi @alansouzati, I will check it out...
Cheers

**Comment by primozs** [comment] 2016-07-20 15:29
Hi, @alansouzati 
Better then window.scrollTo(0,0) It looks to me that in _object.layer.scss visibility: hiden; should be changed to display:none;
```
// _object.layer.scss

  @include media-query(palm) {
    &:not(.#{$grommet-namespace}layer--hidden) + .#{$grommet-namespace}app {
      // visibility: hidden;
      display: none;
      width: 0px;
      height: 0px;

      // IE11 specific fix for layer to hide content behind layer and
      // eliminate white gap under layer content (when content behind is taller)
      @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
        display: none;
      }
    }
  }
```
What do you think?

**Comment by alansouzati** [comment] 2016-07-20 16:53
Unfortunately we can't do that as it present accessibility issues.

Check this out: https://css-tricks.com/places-its-tempting-to-use-display-none-but-dont/

**Comment by primozs** [comment] 2016-07-20 17:13
Ok, But then we could use suggested solution:
```
position: absolute !important;
   top: -9999px !important;
   left: -9999px !important;
```
or just:
```
overflow: hidden;
```
Both seams to work.

**Comment by acornejo** [comment] 2016-08-20 22:03
I was about to file a bug, but I realize its a duplicate of this one. Here is a video showing the behavior:

https://youtu.be/xGikvv42y50

Neither of the suggested scss fixes worked for me. The scroll to top solution is also less than ideal. Imagine a user is scrolling through a long list of items, clicking one of them causes a dialog/layer to come up. In that scenario fiddling with the scrolling state is not what you want to do.

Any other suggestions?

**Comment by alansouzati** [comment] 2016-08-23 23:01
Fixed in https://github.com/grommet/grommet/commit/1c348ff8f1946d98a9e4046b42677357845bf277

**Closed by alansouzati** 2016-08-23 23:01 UTC
Labels: good first bug, help wanted
