### ISSUE TITLE
Clicking outside modal ("layer") no longer closes it

### ISSUE THREAD

**Issue by hdehal** [grommet/grommet#1209] opened 2017-02-24 21:52 UTC
### Expected Behavior
Clicking outside of the modal ("layer") should close it (in addition to clicking the "X" close button). This used to work as of a few weeks ago and is the expected UX in all major frameworks outside of Grommet.

### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/layer/examples?closer=true&flush=true

### Your Environment
Mac OS X
Safari, Firefox, Chrome, etc.

**Comment by tracybarmore** [comment] 2017-02-28 21:12
linking with #1183

**Comment by alansouzati** [comment] 2017-03-21 18:54
Closing is a duplicate of #1183. let's use that use to discuss this.

**Closed by alansouzati** 2017-03-21 18:54 UTC
