### ISSUE TITLE
DataFilters + Select null attribute error

### ISSUE THREAD

**Issue by JCoder121** [grommet/grommet#6675] opened 2023-03-08 18:09 UTC
### Expected Behavior
There should be no errors on console. On previous Filtering examples, we got around this issue by requiring the user to close the layer with 'Apply filters' or 'Cancel', disallowing them from clicking outside of the layer to close it.

### Actual Behavior

The default DataFilters implementation with Data properties throws a TypeError specifically when a Select drop down menu is present among the Filters.
To reproduce the issue:
1. open Select drop down menu from DataFilters, then
2. nothing is selected OR all checked boxes are deselected, then
3. the user clicks out of the Filter layer (as shown in the screen capture video).

### URL, screen shot, or Codepen exhibiting the issue

https://user-images.githubusercontent.com/23144209/223541825-264f2db1-695a-4cc1-b0e3-c0b72c4362a8.mov

The issue does not crash the live site/production build, and coincidentally because no filters were previously selected, the Datatable view remains unchanged. However, the error is present in the console: 
![image](https://user-images.githubusercontent.com/23144209/223543231-ad9b7238-52f3-41e8-8ba1-72dac5ce11ea.png)

Related to #3182 FilterServers example's `DataFilters` component.

**Comment by ericsoderberghp** [comment] 2023-03-09 22:46
I am unable to reproduce this at
https://storybook.grommet.io/?path=/story/data-datafilters-layer--layer&globals=theme:hpe
or
https://design-system.hpe.design/templates/filtering#filtering-with-selectable-results
Are there any other URLs that can be used to reproduce the issue?

**Comment by JCoder121** [comment] 2023-03-10 17:34
Hi Eric, I realized that I didn't include the link where Filters actually causes the error, that would be the Refactor Filtering with Data Deploy Preview link here: https://deploy-preview-3182--keen-mayer-a86c8b.netlify.app/templates/filtering#filtering-with-selectable-results from [this PR](https://github.com/grommet/hpe-design-system/pull/3182). The live site Filtering link for Servers is currently non-Data, which is why no error appears. 

I can't seem to reproduce the error on Storybook, as the `DataFilters layer` story doesn't give any console errors. However, when I copy over the exact story to the Design Site and use Data + DataFilters, as pictured in the screen capture video, the error appears. Should I move this to hpe-design-system issue?


https://user-images.githubusercontent.com/23144209/224383844-bee34164-c541-4945-a0c2-ae51b00eff89.mov

**Comment by taysea** [comment] 2023-07-10 22:50
@jcfilben and I were no longer able to reproduce the issue, so I believe this has been resolved in subsequent Data PRs.

**Closed by taysea** 2023-07-10 22:50 UTC
Labels: enhancement
