### ISSUE TITLE
Accordion component causes a warning in console about usage of useLayoutEffect which causes SSR issue. 

### ISSUE THREAD

**Issue by B-Esmaili** [grommet/grommet#5185] opened 2021-04-22 07:12 UTC
When I use Accordion component in my next-js application it shows a warnning in console which looks like following :

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Collapsible (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Collapsible/Collapsible.js:29:23)
    at div
    at StyledBox (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Box (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Box/Box.js:27:24)
    at div
    at StyledBox (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Box (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Box/Box.js:27:24)
    at AccordionPanel (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/AccordionPanel/AccordionPanel.js:33:23)
    at div
    at StyledGrommet (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Grommet (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Grommet/Grommet.js:60:24)
    at SideNavItem (webpack-internal:///./components/layouts/admin/side-nav/index.tsx:51:5)
    at div
    at StyledBox (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Box (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Box/Box.js:27:24)
    at Accordion (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Accordion/Accordion.js:25:26)
    at div
    at StyledBox (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Box (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Box/Box.js:27:24)
    at side-nav__StyledSideNav (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at SideNav (webpack-internal:///./components/layouts/admin/side-nav/index.tsx:178:5)
    at div
    at StyledBox (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Box (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Box/Box.js:27:24)
    at div
    at StyledBox (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Box (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Box/Box.js:27:24)
    at Sidebar (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Sidebar/Sidebar.js:19:23)
    at div
    at StyledBox (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Box (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Box/Box.js:27:24)
    at div
    at StyledGrid (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Grid (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Grid/Grid.js:19:25)
    at AdminLayout (webpack-internal:///./components/layouts/admin/index.tsx:21:5)
    at Index
    at AppContextProvider (webpack-internal:///./context/app-context/index.tsx:20:5)
    at div
    at StyledGrommet (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at Grommet (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/grommet/components/Grommet/Grommet.js:60:24)
    at MyApp (webpack-internal:///./pages/_app.tsx:32:33)
    at I18nProvider (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/next-translate/lib/cjs/I18nProvider.js:44:18)
    at AppWithTranslations (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/next-translate/lib/cjs/appWithI18n.js:65:92)
    at ae (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/styled-components/dist/styled-components.cjs.js:1:13243)
    at AppContainer (/home/behnam/Documents/projects/Personal/appgres/appgres/node_modules/next/dist/next-server/server/render.js:25:874)
```
I thought it worth reporting to the great `grommet` team. Thanks for your life-saving library by the way.

**Comment by MikeKingdom** [comment] 2021-04-22 17:03
This is a duplicate of #4765 and should be addressed by PR #5157.

Thanks for the kind words!

**Closed by MikeKingdom** 2021-04-22 17:03 UTC
