### ISSUE TITLE
Import issues with Grommet 1.3.0

### ISSUE THREAD

**Issue by arabold** [grommet/grommet#1244] opened 2017-03-17 11:27 UTC
I've upgraded from Grommet 1.2.1 to 1.3.0 and found a couple of issues with my imports.

Here's an example of how I include Grommet's components using ES6 and Babel:

My custom app class:
```javascript
import Grommet from 'grommet';

export class App extends React.Component {

	static propTypes = {
		children: React.PropTypes.element
	}

	constructor() {
		super();
	}

	render() {
		return (
			<Grommet.App centered={ false }>
				{ this.props.children }
			</Grommet.App>
		);
	}
}
```

After upgrading Node complained `Cannot read property 'App' of undefined`. I had to change my import statement to this:
```javascript
import GrommetApp from 'grommet/components/App';
```

Similar is true for icons. I used to be able to do
```javascript
import { Icons } from 'grommet';

//...
	render() {
		return <Icons.Base.Menu />;
	}
//...
```

This throws the similar error `Cannot read property 'Base' of undefined`.

I understand that it's not necessarily optimal to import `Grommet` and `Icons` directly, but is this really an intentional change between 1.2.1 and 1.3.0?

### Your Environment
* Grommet version: 1.3.0
* Node v4.4.7 with Babel and Webpack

**Comment by alansouzati** [comment] 2017-03-17 17:07
Im sorry about that. it should have any breaking change. Let me investigate that and release a patch fix that allows using `import Grommet from 'Grommet'`

**Comment by alansouzati** [comment] 2017-03-17 19:08
I'm so sorry we added this breaking change in minor version increment.

We added the fix for that in this commit: https://github.com/grommet/grommet/commit/605d8bac8ed7bc08af4bfc61724f27957aa9bcdd

We are going to release 1.3.1 with this fix today.

**Comment by arabold** [comment] 2017-03-18 07:38
Hi @alansouzati , thanks for the update. While the import statement `import Grommet from 'grommet'` works, it's still not possible to use either `Grommet.App` or `Icons.Base.Menu` following the examples above.

In other words, the following code just prints `undefined` for both `Grommet` and `Icons.Base`:

```
import Grommet from 'grommet';
console.log("Grommet =", Grommet.App);

import { Icons } from 'grommet';
console.log("Icons =", Icons.Base);
```

**Comment by alansouzati** [comment] 2017-03-20 16:39
Let me try to reproduce this.

**Comment by alansouzati** [comment] 2017-03-20 19:00
Yeah, it turns out the return of the import was the Grommet object itself. Sorry I should have done that more carefully.

I've added the fix for this here: https://github.com/grommet/grommet/commit/90f2a509222117e5ce177214cdd7e24f43ef0da5

I'm going to release 1.3.2 today with this fix in it.

**Comment by alansouzati** [comment] 2017-03-21 03:55
1.3.2 released https://github.com/grommet/grommet/releases/tag/v1.3.2

Thanks for your patience @arabold

**Comment by arabold** [comment] 2017-03-21 10:15
Thanks for the update, @alansouzati . Indeed `Grommet.App` works as expected now.

However, there's still a problem with Icons: The class names have changed!

In the past (1.2.x) I could do something like this (note the `Icons.Base`):
```js
import { Icons }  from 'grommet';
//...
render() {
  return <Icons.Base.Menu />;
}
```

Since 1.3.x this doesn't work anymore and results in an error:
> React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined

Instead of referencing `Icons.Base.Menu` I have to reference `Icons.Base.MenuIcon` (note the "Icon" at the end).

**Comment by alansouzati** [comment] 2017-03-21 15:18
Humm 😢 

I need to double check that, but you are probably right. Sorry it is being a while since I've touch the commonjs bundle and I apologize for the back and forth.

**Comment by alansouzati** [comment] 2017-03-21 16:25
Cool, I've removed the `Icon` suffix from the exports in this commit:

https://github.com/grommet/grommet/commit/a6b4ea54c686892e1d9aba1780bd2073fdc489ef

When I release 1.3.3 I'm confident that you will be able to use grommet as you used to before 1.3.0

**Closed by alansouzati** 2017-03-21 16:25 UTC
Labels: in progress

**Comment by alansouzati** [comment] 2017-03-22 02:51
1.3.3 released. hopefully this is it :)

**Comment by arabold** [comment] 2017-03-22 08:23
Uhmm... not sure how to put this, but no, it doesn't work 😭 

While `Grommer.App` and `Icons.Base.*` works fine now (thanks!), v1.3.3 breaks `Layers` and other components such as `Split`. This is new! 

Here's an error I get when using `Layer` (The `Login` component is my own one using the Layer for layouting):
```jsx
<Layer align='center' flush={ true }>
  <Box direction='column' focusable={ false } appCentered={ false }
       full={ false } justify='center' size='medium'
       pad={{ horizontal: 'medium', vertical: 'medium', between: 'medium' }}>
    <Heading align='center'>Sign In</Heading>
    { /* ... */ }
  </Box>
</Layer>
```

```
Warning: Unknown props `align`, `flush` on <svg> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in svg (created by Layer)
    in Layer (created by Login)
    in Login (created by Connect(Login))
    in Connect(Login) (created by RouterContext)
    in div (created by App)
    in App (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider
```

In the browser only a single icon is rendered - It's the Layer *icon* instead of the Layer *component*:
![image](https://cloud.githubusercontent.com/assets/1548229/24187655/3cd61214-0ede-11e7-9be4-294b69eb66e1.png)


I have cleaned up my `node_modules` just to be sure, rolled back to my original 1.2.1 to double check, etc. This is new in 1.3.3 and didn't happen in 1.3.2. To verify this is a bug in 1.3.3, I've taken a closer look at how I load the component:

If I load `Layer` using my _current_ implementation like this, it fails with the error above:
```js
import { Layer } from 'grommet';
```

However, if I load it explicitly from path, it works fine:
```js
import Layer from 'grommet/components/Layer';
```

And no, I'm not using the `Layer` (or `Split`) icon anywhere in my code. The reasons seems that by changing the icon names from `LayerIcon` back to `Layer`, this also affected how icons are loaded in the main module namespace. I don't speak `gulp`, so I haven't found the root cause yet, but in the *generated* index.js, you'll see the problem in line 644 onwards:
```js
var _icons = require('./components/icons');

Object.keys(_icons).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _icons[key];
    }
  });
});
```

Here the already loaded `Layer` and the `Split` components are replaced with their respective icons, which is wrong.

**Comment by alansouzati** [comment] 2017-03-22 18:10
that's weird, let me try to reproduce this. I supposed this is something to do with es6 exports with conflicting names (which is not being used in your case).

**Comment by alansouzati** [comment] 2017-03-22 18:21
yeah, this is happening because I've removed the suffix which I believe is wrong. We should be able to do:

`import { App, LayerIcon, Layer } from 'Grommet'`

I will add the suffix back and add a temporary fallback structure for es5. But, in the future we will be adding the suffix for Icons.

**Comment by alansouzati** [comment] 2017-03-22 18:41
Cool. I've pushed this commit: https://github.com/grommet/grommet/commit/2c57e21973b7f1b87daf66cc1b2c515f201c9346

Now we should be able to do both:

`import { App, LayerIcon, Layer } from 'grommet'`

and 

`import Grommet, { Icons } from 'grommet'`


`Icons.Base.Layer` vs `LayerIcon`

But let me more careful this time with the release. The CI is currently running for this commit: 

https://travis-ci.org/grommet/grommet/builds/213957045

When it is finished a stable branch should be published. Could you please try to switch to stable branch and test it?

If you are not aware of stable branch please checkout this page:

https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F

Thanks for trying it

**Comment by arabold** [comment] 2017-03-22 22:01
This week I'm traveling in GMT+1 timezone, so I'll give it a try first thing tomorrow morning. Sorry for keep being a pain in the ..

**Comment by alansouzati** [comment] 2017-03-22 22:09
not at all. I should thank you for trying out this structure.

I will release it. I tested with few other apps and it seems to be working. There are other people waiting for that also.

**Comment by alansouzati** [comment] 2017-03-22 22:35
1.3.4 released

https://github.com/grommet/grommet/releases/tag/v1.3.4

**Comment by arabold** [comment] 2017-03-23 08:36
I'm happy to tell you that this works as expected now 👍 

Thanks for taking care of all the issues. I will rework our code to use the `Icon` postfix in future.
