### ISSUE TITLE
Issue with grommet TableHeader in Firefox & IE 11 browsers

### ISSUE THREAD

**Issue by prepaka** [grommet/grommet#2308] opened 2018-09-28 03:02 UTC
I am using grommet 1.11.0 with react in my project. As per my project requirement in UI I need to display the data in table format, there I used grommet Table, TableHeader and TableRow.
I have a requirement that I need to select each row using checkbox individually and all rows at a time along with sorting the column based on header. For that, I used grommet Checkbox in TableHeader for selecting all rows and in TableRow for selecting an individual row. 

I have written the code for all above-mentioned requirements and it is working fine in Chrome and Edge, but in Firefox & InternetExplorer I am facing issue while trying to select the Checkbox which is there in Header(to select all rows at a time) it is not selectable and it is not throwing any error also. For individual row, the checkbox is working fine in Firefox also.

Observation, when SortIndex or onSort parameters are not there in TableHeader then in Mozilla also Checkbox is selectable, but in other browsers with these parameters also it is working.

### Expected Behavior
Checkbox in TableHeader should be selectable in Firefox & InternetExplorer browsers.

### Actual Behavior
Checkbox in TableHeader is not selectable in Firefox & InternetExplorer browsers.

### URL, screenshot, or Codepen exhibiting the issue
https://codepen.io/prepaka/pen/xaMjbr

### Your Environment

* Grommet version: 1.11.0
* Browser Name and version: Mozilla Firefox 62 & InternetExplorer 11

**Comment by spencerkordecki** [comment] 2018-10-05 00:04
Not sure this is related to Grommet itself, seems to be more related to the browser's implementation of nested interactive elements; see this SO post: https://stackoverflow.com/questions/31092439/click-on-checkbox-inside-a-button-element-firefox-issue

I tested this out too by just doing a general click listener on the document and looking for what it was targeting and on Chrome it targets the checkbox, but on Firefox it targets the button. 

What's interesting about this is that if you tab to the header and then use space to select the checkbox, the CodePen and demo works as intended on Firefox, so it seems to be only relegated to clicks in this case. My guess is that the table header elements are buttons for accessibility reasons, but changing the type could be a fix for this.

**Comment by prepaka** [comment] 2018-10-05 07:15
Spencer Thanks for the reply, but when I remove the onSort or SortIndex options from the TableHeader the Checkbox click is working as expected in Firefox browser also. So, my assumption something onSort or SortIndex causing the issue in Firefox browser. 
If we need to change the type in TableHeader of grommet means how to do it? Is there any option to change?

**Comment by spencerkordecki** [comment] 2018-10-07 15:01
@prepaka Since the main interaction with the first column in the table is just the ability to select all, you can place the checkbox that handles this behavior inside of a normal `th` instead of the Grommet `TableHeader`. If you don't want to do that, removing the `onSort` property will remove the `button` element from the `TableHeader` which will allow you to use the checkbox without having to click the button first; see example here: https://grommet.io/docs/table-header/examples

These changes would require some refactoring of your code since you render the headers based on an array, but it would lead to a better experience overall because then the first header is only responsible for selecting and then you can even make that column smaller to not use up as much space.

**Comment by ShimiSun** [comment] 2020-09-22 07:44
I'll be closing this issue since it is stale and since we no longer actively supporting v1. 
Feel free to reopen or make a contribution that addresses this issue.

**Closed by ShimiSun** 2020-09-22 07:44 UTC
Labels: 1.0, Bug :bug:, browser related, help wanted
