### ISSUE TITLE
DataChart labels are not aligned

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet#4902] opened 2021-01-27 02:45 UTC
I created a simple DataChart and I can't have the labels center aligned, see in the picture below

`<DataChart
    data={values}
    series={["date", "value"]}
    axis={{x: {property: "date", granularity: "fine"}}}/>`

![image](https://user-images.githubusercontent.com/3382143/105935268-decaab00-607b-11eb-94f4-0874e087f222.png)

**Comment by ShimiSun** [comment] 2021-01-27 16:56
Can you please provide more information, which version of grommet are you using? Is the DataChart placed in a Box or under the Grommet component? are you using a theme?

Attaching a reproducible environment code such as sandbox usually help us to speed up the issue solution.

**Comment by nomadus** [comment] 2021-01-27 17:08
Hi, you can see it in the Storybook, the labels are not consistently aligned
![image](https://user-images.githubusercontent.com/3382143/106026809-7835a380-60f4-11eb-9f15-96e079b2bfad.png)

**Comment by ShimiSun** [comment] 2021-01-27 17:27
Quick link https://storybook.grommet.io/?path=/story/visualizations-datachart--axis

**Comment by joaoGabriel55** [comment] 2021-02-03 11:47
Hello @ShimiSun, can I work on this?

**Comment by joaoGabriel55** [comment] 2021-02-03 13:43
Hello again @ShimiSun. 
I looked into the code bellow, and I think it could have a way to align the labels from XAxis accordingly to the generated chart type, like bar, line, etc. For example, in a Bar chart, each bar would have its own label instead of having a different div with display flex that aligns the labels disregarding the columns positions.

![image](https://user-images.githubusercontent.com/23138717/106748650-4d6fb180-6604-11eb-98df-7455d18195f8.png)

**Comment by ShimiSun** [comment] 2021-02-05 23:20
@joaoGabriel55  thank you for jumping on this buddy, go for it and file a PR so we can discuss your solution further.

**Comment by jcfilben** [comment] 2022-03-28 20:37
Looks like this issue was fixed in https://github.com/grommet/grommet/pull/5959. You can see it is fixed in the storybook story here: https://storybook.grommet.io/?path=/story/visualizations-datachart-axis--axis

**Closed by jcfilben** 2022-03-28 20:37 UTC
Labels: bug
