### ISSUE TITLE
`theme.global.input.font.size` does not accept custom sizes

### ISSUE THREAD

**Issue by Tbhesswebber** [grommet/grommet#5382] opened 2021-06-28 15:00 UTC
### Expected Behavior

Setting `theme.global.input.font.size` to `"16px"` should change the size of the text to be 16 pixels.
Setting `theme.global.input.font.size` to `"small"` should change the size of the text to be "small".

### Actual Behavior

Setting `theme.global.input.font.size` to `"16px"` breaks the entire rendering of the page.
Setting `theme.global.input.font.size` to `"small"` changes the font size.

### URL, screen shot, or Codepen exhibiting the issue

Here's a code sandbox repro: https://codesandbox.io/s/clever-cloud-refi7?file=/src/theme/index.js

**Comment by LucasCarrias** [comment] 2021-06-28 17:48
I was able to reproduce the error. Thanks for sharing that.

I'd like to work with this issue.

**Comment by jcfilben** [comment] 2021-07-07 20:45
Closing since #5399 was merged

**Closed by jcfilben** 2021-07-07 20:45 UTC
