### ISSUE TITLE
Enhance Select to allow for optgroup option

### ISSUE THREAD

**Issue by britt6612** [grommet/grommet#7314] opened 2024-09-17 15:38 UTC
### Is this something you or your team is interested in contributing a pull request towards?
yes

### Expected Behavior
I would like to be able to have the ability to have something similar to `optgroup` in our Select component.

### Actual Behavior
this is not currently supportive

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment] 2024-09-17 15:46
Duplicate of https://github.com/grommet/grommet/issues/5886

**Closed by jcfilben** 2024-09-17 15:46 UTC
Labels: enhancement
