### ISSUE TITLE
Layer Component is not compatible in Mobile View

### ISSUE THREAD

**Issue by sampathkatari** [grommet/grommet#1074] opened 2016-11-30 16:32 UTC
When we use layer and have more content in it which is browser height filled or more scrollable content its not mobile responsive. The content of the layer just goes below the actual content. 
This is the Browser view. 
<img width="876" alt="screen shot 2016-11-29 at 10 43 43 pm" src="https://cloud.githubusercontent.com/assets/5628804/20760901/47de3568-b747-11e6-98a5-92d464dcf9a2.png">

This is the Mobile view for the same.
<img width="455" alt="screen shot 2016-11-29 at 10 47 31 pm" src="https://cloud.githubusercontent.com/assets/5628804/20760952/6bde538a-b747-11e6-87d9-173c8abf55a8.png">
If you observe, the content in the layer is being hidden behind the actual content outside the layer.
One more observation, when we have a form(some editable fields) there we are able to till the end of form with tab(button). So basically I think the issue is layer is not scrollable in mobile view.

**Comment by alansouzati** [comment] 2016-11-30 16:33
Here is the codepen:

http://codepen.io/anon/pen/qqVYZp

But I cannot reproduce it.

**Comment by alansouzati** [comment] 2016-11-30 16:37
Sorry I thought this was about text cropping. I can see the issue with the underlying content being visible.

**Comment by alansouzati** [comment] 2016-11-30 18:31
Fixed in https://github.com/grommet/grommet/commit/0eb3e49124a8c89a01129f8d8c79c406cb80a63d

**Closed by alansouzati** 2016-11-30 18:31 UTC
