### ISSUE TITLE
fail to import Card component

### ISSUE THREAD

**Issue by cheuk3** [grommet/grommet#1251] opened 2017-03-21 03:09 UTC
Cannot find module 'path' from 'vfile/index.js'

**Comment by alansouzati** [comment] 2017-03-21 03:30
can you provide more details? which version of grommet are you using? which version of node and npm?

**Comment by cheuk3** [comment] 2017-03-21 03:32
sorry about that
im using grommet 1.3.1
node v6.9.5
npm 3.10.10
everything work fine except Card component is failed to import. Thanks!

**Comment by alansouzati** [comment] 2017-03-21 03:42
this is very weird. I'm not able to reproduce this. can you share how are you importing it?

```
import React, { Component } from 'react';
import App from 'grommet/components/App';
import Card from 'grommet/components/Card';

export default class Test extends Component {

  render () {
    return (
      <App className="docs" centered={false}>
        <Card thumbnail='/img/carousel-1.png'
          label='Sample Label'
          heading='Sample Heading'
          description='Sample description providing more details.' />
      </App>
    );
  }

};
```

Also checkout this codepen, this seems to be working: http://codepen.io/alansouzati/pen/oZEJOB?editors=0010.

Can you delete and install your node_modules again?

**Comment by cheuk3** [comment] 2017-03-21 03:45
I'm using Phoenix framework with brunch. I've already tried deleting node_modules.

import React, { PropTypes } from 'react';

import Tile from 'grommet/components/Tile';
import Card from 'grommet/components/Card';

const ProductTile = ({ item }) => {
  return (
    <Tile align='stretch' pad='small' direction='column' size='small'>
      <Card label={item.name}
            thumbnail={item.url} />
    </Tile>
  )
}

export default ProductTile;

**Comment by alansouzati** [comment] 2017-03-21 03:51
are you using webpack 2? can you try adding a `json-loader` to your webpack config?

**Comment by alansouzati** [comment] 2017-03-21 03:52
I believe we need to add the json-loader to the phoenix framework and push that to the repo.

**Comment by cheuk3** [comment] 2017-03-21 04:19
im not using webpack 2. im using brunch which is phoenix default bundler.
i have tried to install json-brunch but i got the same error :(

**Comment by alansouzati** [comment] 2017-03-21 04:31
I don't have experience with brunch. By looking at the logs I can say with confidence that there is something wrong with the way the loader works. As you can see `node_modules\character-reference-invalid\index.json.js` there is an unexpected `.js` suffix that most likely the loader is adding.

Is there a way to configure extension with brunch ?

**Comment by cheuk3** [comment] 2017-03-21 04:38
yes. it has a config file like webpack does but what do i need to config?

**Comment by alansouzati** [comment] 2017-03-21 04:40
do you have `.json` as an extension in the brunch extensions array?

**Comment by cheuk3** [comment] 2017-03-21 04:43
this?
`exports.config = {
  // See http://brunch.io/#documentation for docs.
  files: {
    javascripts: {
      joinTo: "js/app.js"

      // To use a separate vendor.js bundle, specify two files path
      // http://brunch.io/docs/config#-files-
      // joinTo: {
      //  "js/app.js": /^(web\/static\/js)/,
      //  "js/vendor.js": /^(web\/static\/vendor)|(deps)/
      // }
      //
      // To change the order of concatenation of files, explicitly mention here
      // order: {
      //   before: [
      //     "web/static/vendor/js/jquery-2.1.1.js",
      //     "web/static/vendor/js/bootstrap.min.js"
      //   ]
      // }
    },
    stylesheets: {
      joinTo: "css/app.css",
      order: {
        after: ["web/static/css/app.css"] // concat app.css last
      }
    },
    templates: {
      joinTo: "js/app.js"
    }
  },

  conventions: {
    // This option sets where we should place non-css and non-js assets in.
    // By default, we set this to "/web/static/assets". Files in this directory
    // will be copied to `paths.public`, which is "priv/static" by default.
    assets: /^(web\/static\/assets)/
  },

  // Phoenix paths configuration
  paths: {
    // Dependencies and current project directories to watch
    watched: [
      "web/static",
      "test/static"
    ],

    // Where to compile files to
    public: "priv/static"
  },

  // Configure your plugins
  plugins: {
    babel: {
      presets: ['es2015', 'react', 'stage-2', 'stage-0'],
      // plugins: ['transform-runtime'],
      // Do not use ES6 compiler in vendor code
      ignore: [/web\/static\/vendor/]
    },
    sass: {
      mode: 'native',
      options: {
        includePaths: ["node_modules"]
      }
    }
  },

  modules: {
    autoRequire: {
      "js/app.js": ["web/static/js/app"]
    }
  },

  npm: {
    enabled: true
  }
};`

**Comment by alansouzati** [comment] 2017-03-21 05:52
how do you declare `.json` extension using brunch? this config does not help much.

unfortunately Grommet does not support brunch. 

Some issues that might be helpful:

https://github.com/brunch/brunch/issues/1236

https://www.npmjs.com/package/json-brunch: The last activity in this plugin was 4 years ago!

Can you try to load a JSON file without grommet using Brunch? If this also fails, then it would be an explanation.

**Comment by cheuk3** [comment] 2017-03-21 06:32
after install json-brunch, i can just require json file in js file. if i remove it, it fails
what json file does the Card component needs?

**Comment by cheuk3** [comment] 2017-03-21 06:50
this is from the source map 

```
  var require = function(name, loaderPath) {
    if (loaderPath == null) loaderPath = '/';
    var path = expandAlias(name);

    if (has.call(cache, path)) return cache[path].exports;
    if (has.call(modules, path)) return initModule(path, modules[path]);

    throw new Error("Cannot find module '" + name + "' from '" + loaderPath + "'");
  };
```

**Comment by cheuk3** [comment] 2017-03-21 06:51
Cannot find module 'path' from 'vfile/index.js'

```
require.register("unified/index.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {"node-extend":"extend"}, "unified");
  (function() {
    /**
 * @author Titus Wormer
 * @copyright 2015 Titus Wormer
 * @license MIT
 * @module unified
 * @fileoverview Pluggable text processing interface.
 */

'use strict';

/* Dependencies. */
var events = require('events');
var has = require('has');
var once = require('once');
var extend = require('extend');
var bail = require('bail');
var vfile = require('vfile');
var trough = require('trough');
var buffer = require('is-buffer');
var string = require('x-is-string');
```

**Comment by cheuk3** [comment] 2017-03-21 07:17
I think the issue is not related to grommet but i wonder why does it occur only in Card component :(

**Comment by alansouzati** [comment] 2017-03-21 15:16
Yeah I also agree this is most likely not a problem in Grommet.

I tried to check if `vfile/index.js` exists in my `node_modules` and in fact it does:

![screen shot 2017-03-21 at 8 15 33 am](https://cloud.githubusercontent.com/assets/1207250/24154551/b649fdfc-0e0e-11e7-9f1e-75ae79248312.png)

Can you validate this on your end as well?

**Comment by cheuk3** [comment] 2017-03-21 15:32
yes it does exist. i found out that the path module is unable to import in vfile and the replace-ext module.
i tried to comment out both of the path import
and the card component works

**Comment by alansouzati** [comment] 2017-03-21 15:41
I have to idea why brunch is not able to import these modules :(

**Comment by cheuk3** [comment] 2017-03-21 15:47
np alan, i will try to figure it out. thanks for your help :D

**Comment by alansouzati** [comment] 2017-03-21 15:55
I'm going to close this issue for now as I believe there is nothing to fixed inside Grommet core.

Please post your results here once you figure it all out. We can always reopen later if we find that something needs to be fixed.

**Closed by alansouzati** 2017-03-21 15:55 UTC
