### ISSUE TITLE
Long Menu not accessible on Chrome

### ISSUE THREAD

**Issue by ssolari** [grommet/grommet#4026] opened 2020-04-29 21:10 UTC
When a Menu list extends beyond the bottom of the screen clicking on any item after scrolling down the menu does not select the item, but rather snaps the menu list back to the top.

This is observed only on Chrome only.  I tested on Chrome Version 80.0.3987.163 (Official Build) (64-bit).   The menu seems to work fine on Firefox and Safari.

### Expected Behavior

Behavior of Menu on Chrome should match Firefox and Safari.

### Steps to Reproduce
Create a long menu.  Clicking on an initially visible item works.   However, try to scroll the menu and click on an element at bottom and it will not be selected.
```javascript

export function MenuTest(props) {

    const [item, setItem] = useState(1)

    const menuItems = []
    for (let i=0; i<100; i++) {
        menuItems.push({label: i+1, onClick: () => setItem(i+1)})
    }

    return (
        <Box>
            <Box direction={'row'}>
                <Text>Lower menu not acessible</Text>
                <Menu
                    label={item}
                    items={menuItems}
                />
            </Box>

        </Box>

    )
}
```

**Comment by IanKBovard** [comment] 2020-04-30 14:31
Could be the same as #3854

**Comment by ericsoderberghp** [comment] 2020-05-06 15:39
I am unable to reproduce this using grommet stable branch on Chrome Version 81.0.4044.138 (Official Build) (64-bit) on Mac OSX.

**Comment by IanKBovard** [comment] 2020-05-06 17:43
Im able to reproduce it using the code provided here. Same version of chrome on mac.

https://codesandbox.io/s/awesome-elgamal-pep2f?file=/src/App.js

it doesn't happen all of the time. my guess is that sometimes onblur fires first, sometimes onclick does.

**Comment by ericsoderberghp** [comment] 2020-05-06 17:49
I need some more guidance on how to reproduce it. I opened that sandbox and tried more than 10 times to trigger it, but I couldn't reproduce it. :(

**Comment by IanKBovard** [comment] 2020-05-06 17:52
I was able to do it consistently by scrolling up and down then clicking. 
Is my version of grommet and chrome correct?

**Comment by ericsoderberghp** [comment] 2020-05-06 17:57
Can you verify which side of the drop down you are clicking? I am wondering if the scrollbar is still there and the click is causing a scroll because it is actually clicking on the scrollbar. This happens for me when I scroll up and down with the touchpad and then click on the right side of the drop while the scrollbar is still there or is animating away. If I wait a bit after scrolling such that the scrollbar fully disappears, then the click selects the menu item. Or, if I scroll with the trackpad but then click on the left or middle, the click selects the menu item.

**Comment by ssolari** [comment] 2020-05-06 17:59
I can reliably reproduce it on the sandbox.    Make sure you are on Chrome.   It works fine on Firefox and Safari, but if you scroll to click on numbers like 73 etc then it does snap back to 1 without filling the number.  I'm using Chrome Version 81.0.4044.129 (Official Build) (64-bit).   MacOS 10.14.16.   Just upgraded Chrome to Version 81.0.4044.138 (Official Build) (64-bit) and problem is still there.

Make sure to scroll down fast and then click on a number > 70.   Its happening at least 50% of the time or more for me.

**Comment by IanKBovard** [comment] 2020-05-06 18:03
![Kapture 2020-05-06 at 13 02 25](https://user-images.githubusercontent.com/21990914/81212121-02077480-8f9a-11ea-90c9-d162d288bf47.gif)

**Comment by ericsoderberghp** [comment] 2020-05-06 18:14
Thanks, the video helps. If only I could reproduce it myself. I will resume trying ...

**Comment by ericsoderberghp** [comment] 2020-05-18 21:43
I think this has been addressed by https://github.com/grommet/grommet/pull/4096.

**Comment by IanKBovard** [comment] 2020-05-19 16:45
Just tested, #4096 addresses the issue. This can be closed.

**Closed** 2020-05-20 15:17 UTC
