### ISSUE TITLE
Reorder List via drag and drop problem

### ISSUE THREAD

**Issue by jonka5** [grommet/grommet#6369] opened 2022-09-30 17:16 UTC
### Expected Behavior

With onOrder the item should be dropped to where ever the user wants it.

### Actual Behavior

When reordering the list via drag and drop you could only move the item one step up or down.

### URL, screen shot, or Codepen exhibiting the issue

Version 2.25.3 works as expected. Behavior starts to occur in 2.26.0

https://user-images.githubusercontent.com/74107477/193322053-8ae41a3f-dfc8-476d-9679-8443cce474b3.mov

https://codesandbox.io/s/list-with-order-and-action-combined-nmeh4o?file=/src/App.js

### Your Environment

- Grommet version: 2.26.0

**Comment by MikeKingdom** [comment] 2022-10-03 18:14
PR #6249 seems to have caused this regression

**Comment by britt6612** [comment] 2022-10-04 17:42
@MikeKingdom can we close this since it was merged?

**Comment by MikeKingdom** [comment] 2022-10-04 18:03
Yup. Must've forgot a keyword like Fixes :)

**Closed by MikeKingdom** 2022-10-04 18:03 UTC
Labels: bug
