### ISSUE TITLE
Collapsibles using min width overflow with a Box to their right

### ISSUE THREAD

**Issue by blakehilliard** [grommet/grommet#3544] opened 2019-11-12 19:26 UTC
An open Collapsible that is using a minimum width overflows with a Box next to it.

### Expected Behavior

Using a Collapsible should not affect this behavior. There should be no overflow between the Boxes.

### Actual Behavior

It overflows.

### URL, screen shot, or Codepen exhibiting the issue

![grommet-collapsible-overflow-bug](https://user-images.githubusercontent.com/25166376/68703080-7fa07980-054f-11ea-9f9a-64c37e152e5a.png)

In the above screenshot, the grey "Hello" Box is in a Collapsible extended by `width={{ min: '8em' }}`, and the "World" Box is supposed to be to the right of it.

This codesandbox lets you toggle whether the Collapsible is used or not, to see the issue come and go away: https://codesandbox.io/s/grommet-collapsible-min-width-bug-7yzls

### Steps to Reproduce

Use the codesandbox above, or just render this:

```
import React from 'react';
import { Box, Collapsible } from 'grommet';

export default () => (
  <Box border width="small" direction="row">
    <Collapsible open>
      <Box border background="light-4" width={{ min: '8em' }}>Hello</Box>
    </Collapsible>
    <Box fill border>World</Box>
  </Box>
);
```

### Your Environment

- Grommet version: 2.8.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows desktop

**Comment by blakehilliard** [comment] 2019-11-13 16:43
I found I can avoid the issue by using `flex` rather than `fill` for the Box to the right of the Collapsible.

**Comment by ShimiSun** [comment] 2019-11-15 20:43
>I found I can avoid the issue by using flex rather than fill for the Box to the right of the Collapsible.

@blakehilliard interesting it solved it for you, I've replaced `fill` with `flex` on line 21 on the codesandbox you've provided and it doesn't allow the Collapsible to close/open.

**Comment by IanKBovard** [comment] 2020-01-28 20:23
@blakehilliard Anything else we can do for you before we close this issue?

**Comment by blakehilliard** [comment] 2020-01-28 22:14
> @blakehilliard Anything else we can do for you before we close this issue?

What do you mean? The bug is still reproducible. I just updated the codepen to use the latest version of grommet, and you can still see the behavior I described.

**Comment by IanKBovard** [comment] 2020-01-29 16:45
@blakehilliard This isn't an issue with the Collapsible component, but the implementation. 
```
<Box>
  <Box flex={false} border background="light-4" width={{ min: "8em" }}>
    Hello
  </Box>
</Box>
  <Box fill border>
    World
  </Box>
</Box>
```
produces the same results. In your example the child div is styled, but not the collapsible causing the overflow.

```
    <Box>
      <Box border width="small" direction="row">
        <Box flex={false} border background="light-4" width={{ min: "8em" }}>
          <Collapsible open={doCollapsible}>
            <Box>
              Hello
            </Box>
          </Collapsible>
        </Box>
        <Box fill border>
          World
        </Box>
      </Box>
      <CheckBox
        checked={doCollapsible}
        label="Use Collapsible?"
        onChange={event => setDoCollapsible(event.target.checked)}
      />
    </Box>
```
This is not the best implementation, but here is a working version of your example.

**Comment by IanKBovard** [comment] 2020-01-30 16:17
@blakehilliard Is there anything else that you'd like to add. Since this is an implementation issue and not a bug, I recommend we close this.

**Closed** 2020-01-30 16:44 UTC
Labels: waiting
