### ISSUE TITLE
Items’ layout is wrong, no search and help function in IE11

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#610] opened 2016-06-01 05:26 UTC
Make address shown as https://16.125.106.105/directory-setting  press F5 to refresh the browser. The layout is wrong, the search input is too long, add and help function is gone.
User needs to switch to Settings page, then switch to Directory page, the layout will be back to right.

![5](https://cloud.githubusercontent.com/assets/16797825/15699021/6da68adc-27fc-11e6-90c2-7cd4f9242324.jpg)
![6](https://cloud.githubusercontent.com/assets/16797825/15699023/70e3cf2a-27fc-11e6-8d06-f47c7e06d572.jpg)

**Comment by DerekAhn** [comment] 2016-06-07 04:09
@christinHP I'm unable to experiment/test with the link above. However, judging from the images provided it could be possible that there is an issue in your React "container" (the component wrapping the grommet components inside the render method). Possibly an unintended race condition while propagating props of the sort. I'd be happy to help with a little more information and or steps to follow to recreate.

**Comment by epilande** [comment] 2016-06-30 12:51
@christinHP are you still receiving this issue? I'm not able to reproduce it.

![image](https://cloud.githubusercontent.com/assets/3210082/16487712/3790a446-3e68-11e6-8e17-23b489dc39e4.png)

**Comment by bryanjacquot** [comment] 2016-07-18 19:49
Closing until we get confirmation this is still an issue.

**Closed by bryanjacquot** 2016-07-18 19:49 UTC
