### ISSUE TITLE
DateInput test is not passing for other time zones

### ISSUE THREAD

**Issue by britt6612** [grommet/grommet#5539] opened 2021-08-24 14:21 UTC
except for a date-related one because the test doesn't allow for my +10 timezone.
### Expected Behavior
all tests should pass

no errors
### Actual Behavior
Different time zones fail the `dateinput` test
<img width="787" alt="Screen Shot 2021-08-24 at 8 20 34 AM" src="https://user-images.githubusercontent.com/42451602/130633692-c004bae7-8701-4cea-805e-f348487dd1f3.png">

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by DanielBaird** [comment] 2021-08-25 06:45
I wish I had made this issue when I came across it the first time.  From memory the problem is when the "correct" datetime is dinked together as a string with `timezoneOffset`, which is made like this:
```
    if (timezoneOffset < 10) timezoneOffset = `0${timezoneOffset}`;
```
In Australia my timezone is +10, which makes a negative timezoneOffset, but a negative number is less than 10 so it gets prepended with a `0` by that code. Then, subsequent dates assembled like this:
```
`${year}-${month}-20T${timezoneOffset}:00:00.000Z`,
```
...are crazy looking.

If I get a chance over the next few weekends I'll try for a fix. Hopefully I can work out something that works in all timezones but doesn't require adding Moment or date-fns or whatever to the deps.

Post a comment here if you start working on this so I can ping you and we don't double up

**Comment by AkshayChoulwar** [comment] 2021-09-08 07:31
@DanielBaird @britt6612 Not sure what exactly the test case because I couldn't found in the file. Generally working with the times can we use the UTC date here to avoid issues related to timezone?

**Comment by JackGoldsworth** [comment] 2021-09-08 17:38
@DanielBaird @AkshayChoulwar I've also been having a timezone-related issue similar to the one above, and I was wondering if you could possibly provide an alternative in order to only get the date (without time) on selection. For example, date input could have a boolean prop called dateOnly, so that when you select September 8th, 2021, you'd get the date 2021-9-8 (Without worrying about the timezone mess). Correct me if this already exists or if I am misunderstanding how this works.

**Comment by alexmirrington** [comment] 2021-09-25 08:51
Been running into this one locally too, and have been needing to push with the `-n` flag which is not ideal. Would be great to get this one merged before Hacktoberfest to make sure tests are being run locally by any new contributors

**Comment by taysea** [comment] 2021-11-03 16:40
I am wondering if we should update this test somehow -- it seems part of the issue that has been happening is due to daylight savings timezone. According to this thread, there are functions we could create to see if a caller is in standard time or daylight savings, but according to the discussion under the reply it doesn't necessarily seem like it's fully reliable:

https://stackoverflow.com/a/11888430

**Closed** 2021-12-15 18:51 UTC
Labels: bug
