### ISSUE TITLE
DE1347: UI: Grommet version changes ( https://rally1.rallydev.com/#/319337422988d/detail/defect/369717382932 )

### ISSUE THREAD

**Issue by anushachaparala** [grommet/grommet#3889] opened 2020-03-27 15:51 UTC
### Expected Behavior

Its updated in the wiki https://wiki.hpelabs.net/pages/viewpage.action?spaceKey=HCSS&title=New+Grommet+Changes and https://rally1.rallydev.com/#/319337422988d/detail/defect/369717382932

### Actual Behavior
Its updated in the wiki https://wiki.hpelabs.net/pages/viewpage.action?spaceKey=HCSS&title=New+Grommet+Changes and https://rally1.rallydev.com/#/319337422988d/detail/defect/369717382932

### URL, screen shot, or Codepen exhibiting the issue

https://wiki.hpelabs.net/pages/viewpage.action?spaceKey=HCSS&title=New+Grommet+Changes

### Steps to Reproduce
Its updated in the wiki https://wiki.hpelabs.net/pages/viewpage.action?spaceKey=HCSS&title=New+Grommet+Changes and https://rally1.rallydev.com/#/319337422988d/detail/defect/369717382932

### Your Environment

- Grommet version:
- Browser Name and version: Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by ShimiSun** [comment] 2020-03-27 15:52
Not sure I understand this issue, can you elaborate?

**Comment by anushachaparala** [comment] 2020-03-27 15:55
> Not sure I understand this issue, can you elaborate?

With new grommet version change we are seeing this issues in Catalog.
https://wiki.hpelabs.net/pages/viewpage.action?spaceKey=HCSS&title=New+Grommet+Changes

**Comment by anushachaparala** [comment] 2020-03-27 16:02
@priya.kou.l@hpe.com can you please update grommet version which is being used by Catalog.

**Comment by ShimiSun** [comment] 2020-03-27 16:03
@anushachaparala I need the issue to be isolated reliably from your project in order to investigate, and I can't log in to the link you have provided.

**Comment by ShimiSun** [comment] 2020-03-27 22:45
Please provide a detailed description of the issue, without links that requires login credentials.
The issue needs to be isolated from your working environment and be reproducible reliably so we can investigate the code. thank you for your cooperation.

**Comment by ShimiSun** [comment] 2020-04-06 15:47
I'll be closing the issue due to unclarity, feel free to reopen or file a new issue that can help us understand the problem and investigate.

**Closed by ShimiSun** 2020-04-06 15:47 UTC
Labels: waiting

**Comment by Priya-Koushik-L** [comment] 2020-04-11 13:57
@ShimiSun  I had updated details for this in the notes section(in rally) of this bug. Please let me know if weren't able to view the same.

**Comment by Priya-Koushik-L** [comment] 2020-04-11 13:58
I'm not able to reopen this issue, Please do the needful with the above details.

**Comment by ShimiSun** [comment] 2020-04-15 15:14
@Priya-Koushik-L for full transparency with others that may be encountering similar issues, let's post all the details on this github issue. I don't have a Rally account to enter your links so please list the information as the template suggests when you file an issue.
