### ISSUE TITLE
Possible to have a multiple Select message for single selection?

### ISSUE THREAD

**Issue by chancesmith** [grommet/grommet#3089] opened 2019-05-07 19:37 UTC
### Expected Behavior

If my multiple Select fields only has one option selected, I'd like the placeholder text to remain as the default.

### Actual Behavior

The single option selected is now the placeholder text. 😔

![Screenshot 2019-05-07 14 30 21](https://user-images.githubusercontent.com/4466585/57327742-43d6b400-70d5-11e9-8262-9b94923a18e1.png)

### ideal

Maybe...

```
<Select
messages={{
	multiple: 'Cost',
	single: 'Cost', ***
}}
...
/>
```

**Comment by ShimiSun** [comment] 2019-05-08 17:36
Can we get a little more context of what the [X] is intending? and what will you show on the placeholder if nothing was selected?

**Comment by brantleyenglish** [comment] 2019-05-16 18:16
The [X] is to remove the option from the multi-select field. That part isn't really related to Grommet.

> What will you show on the placeholder if nothing was selected?
The placeholder text. Ex: "Cost"

```
<Select
 messages={{
	multiple: 'Cost',
	single: 'Cost'
 }}
 placeholder="Cost"
 ...
/>
```

**Comment by chancesmith** [comment] 2019-05-16 19:21
I looked at the Select.js component. There are quite a few of IF() statements. I got a bit lost in there.

I understand a Select box with a single option selected should show the new value selected. The way you guys have the component made makes sense.

**In my case**, I'm displaying the options selected as labels/tags under the Select box. The placeholder text should never change after a option(s) is selected.

@ShimiSun, is there a temporary fix for this? Any ideas?

**Comment by chancesmith** [comment] 2019-05-17 16:07
Here is the example of the UI:

![grommet-select-tags](https://user-images.githubusercontent.com/4466585/57941207-f48e4180-7893-11e9-9178-90ed590427f6.gif)

**Comment by chancesmith** [comment] 2019-05-20 13:48
I found a workaround...

```
const CGSelect = props => {
  const newValue =
    props.multiple && props.value.length === 1 ? [{id: props.value.id, title: props.placeholder}] : props.value;
  return (
    <SelectWrapper>
      <Grommet theme={selectTheme}>
        <Select {...props} value={newValue} />
      </Grommet>
    </SelectWrapper>
  );
};
```

..., but I'm not able to see a match after the first item is selected. It seems the `value.id` of an object is not matched by the `options[0].id`.

![grommet-select-value-no-match](https://user-images.githubusercontent.com/4466585/58026258-ae2b2380-7adb-11e9-90d8-9490c51bef37.gif)

@ShimiSun, thoughts?

**Comment by kenjdavidson** [comment] 2020-12-17 02:57
Came across this while trying to figure out my own issue, after spending some time looking at the code (I'm posting for my own info when I login tomorrow) but it looks like

On change the selected values can be reduced into a string and provided to the Select as

valueLabel={value.map().reduce()}

This being provided should skip inputValue. 

Since the comments say passing a value of react element is deprecated it makes no sense to try that. As the value should continue ot be an array. 

With regard to the OP

Unless I'm crazy in this instance adding 

valueLabel="Cost" 

Should bypass the messages logic completely.

**Comment by kenjdavidson** [comment] 2020-12-17 15:12
Just a follow up, this works well, although there are a couple things:

- `valueLabel` is not placed in an input, which leads its look to be different (padding/spacing) when placed within a `Form` and `FormField`.  It should probably be wrapped in `SelectInputText` within the component itself? 
- Wrapping it in `valueLabel={<TextInput readonly plain value={reducedValue}/>}` works perfectly, except it is marked as `deprecated`.  Since `SelectInputText` isn't exported getting the styling to match needed extra steps.  Don't see a reason why it couldn't be exported.

For all intents and purposes I think this is working well (as designed).

**Comment by jcfilben** [comment] 2021-01-25 23:01
As @kenjdavidson said, `valueLabel` can be used to get the desired behavior, but will look different than a regular input. Full example [here ](https://codesandbox.io/s/grommet-v2-template-forked-zdpxg?file=/index.js) with some styling of `valueLabel`. I think this issue can be closed.

**Closed** 2021-01-26 20:32 UTC
Labels: discussion, enhancement
