### ISSUE TITLE
hpe-fonts-path references 'amazonaws.com' despite fonts being available locally.

### ISSUE THREAD

**Issue by maysst** [grommet/grommet#755] opened 2016-08-09 08:29 UTC
### Expected Behavior

Within Grommet the _**Metric**_ font is provided in `grommet/src/scss/hpe/font`.  Fonts should therefore be bundled with the distribution.
### Actual Behavior

The line within `grommet/src/scss/hpe/_hpe.defaults.scss` sets a url to a location on _**amazonaws.com**_  as below:

`$hpe-fonts-path: "https://hpefonts.s3.amazonaws.com/web" !default;`

In our environment, this causes web proxy authentication dialog to be displayed by the browser to enable download of the font from the remote site which is undesirable/unexpected behavior for the user.
### Your Environment
- Grommet version: 0.6.10
- Browser Name and version: Chrome 52.0.2743.116 m (64-bit)
- Operating System and version (desktop or mobile): Windows 7 desktop.

**Comment by alansouzati** [comment] 2016-08-09 21:11
Thanks for getting in touch.

The main reason we are using sass is to allow for folks to easily override these values. `!default` allows you to set it to a different value. It is too bad that we don't have a page that describes which variables you can replace when dealing with our Sass.

Well, assuming you have your index.scss file, you can do this:

```
$hpe-fonts-path: "font";
@import '~grommet/scss/hpe/index';
```

This will look for the files inside your font folder located at the same level as your `index.scss` file.

Also, the fonts are available here for download: https://github.com/grommet/grommet/tree/master/src/scss/hpe/font.

Please make sure to keep the license when using it. If you are not an HPE employee you need to acquire a license to use the Metric font.

**Comment by maysst** [comment] 2016-08-10 16:22
@alansouzati - Many thanks :+1: for the clarification!  Quite obvious when you spell it out like that :-)   The project is within an HPE account so licencing for the font is ok.

**Comment by alansouzati** [comment] 2016-08-10 16:49
perfect! glad to you are unblocked now.

**Comment by maysst** [comment] 2016-12-07 13:12
Hi, since grommet-toolbox moved to react-hot-loader ^3.0.0-beta.6, I'm no longer seeing the HPE Metric font being loaded when using `gulp dev`.  The font is defaulting back to Arial.  However, a `gulp dist` build works as expected.

My `index.scss` is as below:

```
$hpe-fonts-path: '~grommet/scss/hpe/font/';
@import '~grommet/scss/hpe/index';
```

Am I doing something really stupid?

**Comment by alansouzati** [comment] 2016-12-07 16:19
let me try it locally and see if I can reproduce this.

**Comment by maysst** [comment] 2016-12-07 17:15
Hi Alan,

If any help, browsing to http://localhost:9000/webpack-dev-server shows that the hashed .woff files are there in the root:

```
- de48faee6019b25e8cda644f3654b35e.woff
- 1278b251d4da7f8fed4b48ee567b3c0a.woff
- f0cdcb22eecb468b06d6b7c7b1fffa59.woff
- 08febe75cf58d264f16ca1fc3a2965c8.woff
- index.js
- index (magic html for index.js) (webpack-dev-server)
```

...and the compiled style sheet has the following when you look at it in Chrome Dev tools:

`@font-face{font-family:"Metric";src:url(/de48faee6019b25e8cda644f3654b35e.woff) format("woff")}@font-face{font-family:"Metric";src:url(/1278b251d4da7f8fed4b48ee567b3c0a.woff) ...`

The end result though is that the text is defaulting to Arial and not using Metric... :-(

**Comment by maysst** [comment] 2017-01-04 18:39
Hi @alansouzati,

Any thoughts on this one?

**Comment by alansouzati** [comment] 2017-01-18 23:50
Sorry for taking such a long time to get back to you on this you need to manually copy the font folder because `~grommet/scss/hpe/font/` will not be moved to the `dist` folder.

To serve the font locally, you need to make sure that the font folder will be inside dist.

If you are using the grommet toolbox you need to manually add the copy asset to transfer things either from `grommet/scss/hpe/font` to `dist/` and then update your sass file to be something like:

```
$hpe-fonts-path: 'font/';
@import '~grommet/scss/hpe/index';
```

This is more less what the configuration in the toolbox should look like for the copy asset part:

```
...
copyAssets: [
   ...
    {
      asset: 'node_modules/grommet/scss/hpe/font/',
      dist: 'dist/font/'
    },
   ...
  ],
...
```

**Comment by alansouzati** [comment] 2017-01-24 00:51
hey @maysst did you have time to check this out?

**Comment by alansouzati** [comment] 2017-02-06 20:52
I'm closing this for now. Please feel free to reopen if you still believe this is something to fix

**Closed by alansouzati** 2017-02-06 20:52 UTC
Labels: in progress, waiting
