### ISSUE TITLE
Submit doesn't work when FormField has required flag

### ISSUE THREAD

**Issue by bilak** [grommet/grommet#3777] opened 2020-02-23 10:40 UTC
### Expected Behavior

When FormField has required flag and data are filled submit receives event with data.

### Actual Behavior

When FormField has required flag submit doesn't work even when data are filled.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/kind-napier-gyrpv

**Comment by ShimiSun** [comment] 2020-02-24 16:56
Hi buddy, thanks for reporting, I narrowed down the problem and took a look on https://storybook.grommet.io/?path=/story/form--required-label where the issue doesn't reproduce, and the reason you are experiencing this issue is that the `name` prop is missing from both FormField and TextInput components, hence are resolved as `undefined` under the hood which caused the issue. I added both name fields on the components and it seems to work as expected.
I will leverage this issue to improve our docs and be clear on this behavior, let me know if you have any more feedback for us on this matter.

`It Woks!` alert:
https://codesandbox.io/s/formfield-with-required-textinput-0s4pp

**Comment by bilak** [comment] 2020-02-24 17:52
Hi @ShimiSun 
so the only one requirement in `FormField` is to provide same `name` as in child component? If so that's ok for me, I just didn't know this.

**Comment by ShimiSun** [comment] 2020-02-24 19:16
@bilak correct, and you shouldn't have known it if it wasn't documented, I'm looking to see if we want to document it or take a default naming approach. Either way, thanks for reporting! I'll keep you posted.

**Comment by bilak** [comment] 2020-02-27 19:51
Hi @ShimiSun 
I found probably another issue. When `FormField` and it's child have defined name, then it's not possible to display fields with `useEffect`. Please look [here](https://codesandbox.io/s/admiring-voice-x0pjf) `name` field is without name attribute and it's loaded and other fields are with name attribute but are not loaded. Please can you tell me how can I fix this? I would like to have form validation and also be able to load data.

Thanks

**Comment by ericsoderberghp** [comment] 2020-02-28 18:59
Thanks for the great example. Instead of setting the value per input component, you can set it at the `Form` level, as in: `<Form value={userData}>`. I've forked the sandbox here to show it: https://codesandbox.io/s/prod-dust-hnmzq?fontsize=14&hidenavigation=1&theme=dark

**Comment by bilak** [comment] 2020-03-01 09:57
@ericsoderberghp you probably didn't saved the sandbox. I don't see any difference to my sandbox.

**Comment by bilak** [comment] 2020-03-02 07:53
@ericsoderberghp I've created [another sandbox](https://codesandbox.io/s/blissful-benz-l8odh) where I'm using FormField like you described, but it doesn't work

**Comment by ShimiSun** [comment] 2020-03-10 19:58
Hi @bilak, I think this issue is fixed on the master branch, care to take confirm it for us? you can point grommet to `https://github.com/grommet/grommet/tarball/stable` on your package.json and re-install it. let me know how it goes.

**Comment by ShimiSun** [comment] 2020-03-11 20:23
Here is a cleaner example of a Form value prop that is driving all the input components values https://codesandbox.io/s/form-value-1igd1

**Comment by ShimiSun** [comment] 2020-03-16 15:31
I'll be closing this issue, thanks for reporting.

**Closed by ShimiSun** 2020-03-16 15:31 UTC
Labels: documentation :memo:
