### ISSUE TITLE
Redundant filter to be present

### ISSUE THREAD

**Issue by RodHPE** [grommet/grommet#1431] opened 2017-07-18 09:31 UTC
when click filter icon to open filter drop. if has a lot  filter items using scrollbar to display., that cause have redundant filter to present.  open the source code we found  two  filter tags, see picture.
### Expected Behavior
has only one index filter to be present

### Actual Behavior
has multi-filter

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/20080920/28351708-1330ffce-6c84-11e7-9b57-623994bddaf8.png)

### Steps to Reproduce
 1.  click index filter icon to open index filter
 2.  click Ok, Waring status to filter
 3.  click all status to reset filter
 4. click filter icon to close filter

note: if not reproduce, pls do one more times.
### Your Environment

* Grommet version: 1.5.0
* Browser Name and version: chrome 57, win7

**Comment by RodHPE** [comment] 2017-07-19 07:02
It seems when has a lot filter item, the page will re-rend with scrollbar. the filter will be double

**Comment by frandr** [comment] 2017-08-23 00:07
I did a fair amount of triaging this and believe I have found root cause. There's a problem in the state machine in Menu.js (see code starting on ~line 272). The problem is that when the filter icon is clicked (under some circumstances) Menu goes thru the 'focused', expanded', and then 'collapsed' states. When we pass thru the expanded state there is already a Drop object in the DOM, and we add a new one when passing thru the expanded state. We then pass thru the 'collapsed' state, which removes the duplicate Drop from the DOM, but leaves the original drop in place. Thereafter, clicks on the filter icon just add/remove a duplicate Drop in the DOM. The only way to get rid of the original Drop is to refresh the browser.

This can be fixed by adding a conditional to the 'expanded' case, ie:
if (this._drop) {
     this._drop.remove();
     this._drop = undefined;
}

**Comment by karatechops** [comment] 2017-09-11 18:57
Hi @RodHPE and @frandr, I need a bit more context before I can investigate this issue further as FilterControl does not have a native menu. I've created a new [Codepen](https://codepen.io/karatechops/pen/bobYOZ?&editors=0010#) boilerplate which has the grommet-addons components lined in. Can you provide a code sample which reproduces the bug so I can review it?

**Comment by karatechops** [comment] 2017-09-21 15:32
Closing this as no further context was provided. Feel free to re-open with more info.

**Closed by karatechops** 2017-09-21 15:32 UTC
Labels: waiting
