### ISSUE TITLE
LayerForm Can’t be closed normally in IE11

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#608] opened 2016-06-01 05:23 UTC
Maximize IE, open add directory form, click left outside of LayerForm or “X” button to close the LayerForm. “focus” function can’t be run.
The “focus” function is in grommet/components/Layer.js, so this is a grommet defect. User needs to press F5 to refresh the browser, then do other operation
![1](https://cloud.githubusercontent.com/assets/16797825/15698963/ff2412c8-27fb-11e6-8cd6-568107839b3e.jpg)

![2](https://cloud.githubusercontent.com/assets/16797825/15698975/0beb5c5a-27fc-11e6-9390-3bd15f31464f.jpg)

.

**Comment by michaelgilley** [comment] 2016-06-01 17:13
Duplicate of #598

**Closed** 2016-06-01 17:19 UTC
