### ISSUE TITLE
Split not working inside of Carousel

### ISSUE THREAD

**Issue by bmperrea** [grommet/grommet#1128] opened 2017-01-10 17:41 UTC
If I use split to put two things side by side, I get something that makes sense. If I put that inside a carousel, the second thing disappears.

### Expected Behavior

Carousel should render the component the same as without it, but then scroll through the items.

### Actual Behavior

Only the first half of the split appears.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/bmperrea/pen/dNGNqP?&editors=0010

### Your Environment

* Grommet version: 1.1.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10

**Comment by alansouzati** [comment] 2017-01-10 17:58
Thanks for this issue. Split uses 100vw and 100vh by design, which is meant to be used to divide up the main screen. 

I've updated the codepen to reflect how to achieve what you are asking for

http://codepen.io/alansouzati/pen/MJKpgz?&editors=0010

I'm closing this issue but feel free to reopen it if you still think something needs to be done.

**Closed by alansouzati** 2017-01-10 17:58 UTC

**Comment by bmperrea** [comment] 2017-01-10 18:33
Alan - awesome. Thanks so much. This will do for me.
