### ISSUE TITLE
DateInput format="yyyy-mm-dd" converts 2021-11-10 text input as 2021-11-09 (various others too)

### ISSUE THREAD

**Issue by sbytnar** [grommet/grommet#5871] opened 2021-12-29 20:09 UTC
When typing in a date between 11/08->11/30 manually, the calendar will jump back one day on the last character typed

### Expected Behavior

When using a yyyy-mm-dd format and the user enters a valid YYYY-MM-DD text, the value shown must match what was entered.

### Actual Behavior

For many valid dates of the form 2021-11-08 through 2021-11-30, the date entered is converted into the day before. Note that not all are incorrectly converted. Probably happens in other situations too, this was just the most obvious.

### URL, screen shot, or Codepen exhibiting the issue

The only difference between working and not working is format="yyyy-mm-dd" (broken) vs format="mm-dd-yyyy" (working).
https://codesandbox.io/s/grommet-v2-template-forked-74ml3?file=/index.js

### Steps to Reproduce

Start typing "2021-11-10". Watch that when you type the last "0", the date is reset to 2021-11-09.

### Your Environment

- Grommet version: 2.18.0. Was happening with 2.17.something also and likely earlier.
- Browser Name and version: Chrome, Safari.
- Operating System and version (desktop or mobile): MacOS, Windows.

**Comment by jcfilben** [comment] 2022-01-04 16:13
Hi @sbytnar I confirmed this issue is happening up through v2.19.1 of Grommet, but it is no longer happening on the stable branch. I believe this was fixed by https://github.com/grommet/grommet/pull/5837 and will be available in the next release or on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) of Grommet.

**Comment by jcfilben** [comment] 2022-01-04 19:45
Actually I was able to reproduce this on the stable branch. Using the [DropButton/Calendar](https://storybook.grommet.io/?path=/story/controls-dropbutton-calendar--calendar-drop) story I selected January 10th on the Calendar and January 9th showed instead. Going to go ahead and mark this as a bug.

https://user-images.githubusercontent.com/54560994/148114941-839ea93c-cdca-49a4-984d-8cd2bd4ca3b8.mp4

**Comment by novykh** [comment] 2022-01-12 10:25
The issue lies here: https://github.com/grommet/grommet/blame/a6b0579b4273e487c54a1d14d5d6c59eb4a1287a/src/js/components/Calendar/utils.js#L148
Since the calculation `valueOffset = hourDelta * 60 * 1000;` is like translating hours to minutes.

**Closed** 2022-01-18 17:11 UTC
Labels: bug

**Comment by sbytnar** [comment] 2022-01-21 20:40
Thank you all. 👍
