### ISSUE TITLE
DateTime field becomes unclickable at certain widths

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#977] opened 2016-10-14 18:56 UTC
At certain widths, the DateTime icon becomes unclickable and a horizontal scroll bar is displayed.

### Expected Behavior

DateTime icon should always be visible.  No horizontal bar.

### Actual Behavior

See picture.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://cloud.githubusercontent.com/assets/14231471/19399156/eff78172-9204-11e6-9189-08a8571aa881.png)

### Steps to Reproduce
 1. Make a Box component that has a lot of padding
 2. Add a DateTime component
 3. Shrink window

### Your Environment

* Grommet version: 1.0.0 and stable
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Win10

**Comment by alansouzati** [comment] 2016-10-17 19:11
Im not able to reproduce this with the latest grommet

http://codepen.io/alansouzati/pen/YGZRPO

Can you try it in your end and see if it is fixed?

**Comment by ericsoderberghp** [comment] 2016-10-17 22:01
Fixed in e2d956272e9c82750656b325ab3837d65a21ffad.

**Closed by ericsoderberghp** 2016-10-17 22:01 UTC
Labels: bug
