### ISSUE TITLE
Icon aligning is broaken in Menu component

### ISSUE THREAD

**Issue by dmitrij-borchuk** [grommet/grommet#3209] opened 2019-07-23 15:00 UTC
https://github.com/grommet/grommet/blob/8105c0c2d9a5cb571702f5bb3fbcb0c3e9cad579/src/js/components/Menu/Menu.js#L198
Here you can see that Icon and Label are alined with the `<Box align="start">` and there is no clear method to aline them in the center.

**Comment by ShimiSun** [comment] 2019-07-23 16:52
Can you please share a markup of what you are trying to achieve?

**Comment by ShimiSun** [comment] 2019-07-24 01:13
@dmitrij-borchuk , I've created this sandbox to show how the menu icon can be handled in different alignments https://codesandbox.io/s/menu-icon-alignment-04m5k please share your thoughts on how else you'd like it to behave.

**Comment by dmitrij-borchuk** [comment] 2019-07-24 08:50
@ShimiSun Hi, thank you for answering. I have forked your example and modified it to show the problem. pls take a look here https://codesandbox.io/s/menu-icon-alignment-0ecq1

**Comment by dmitrij-borchuk** [comment] 2019-07-24 08:51
@ShimiSun You need to open the drop menu
![image](https://user-images.githubusercontent.com/3431453/61779428-52e21e00-ae09-11e9-9439-ee35f9a7a030.png)

**Comment by ShimiSun** [comment] 2019-07-31 16:47
I think the root cause is here https://github.com/grommet/grommet/blob/924f237001ebff76ba107e64ebe291a8869224d3/src/js/components/Menu/Menu.js#L181
so if I add for example `align="center"` to this line, I get this layout 
![Screen Shot 2019-07-31 at 10 45 19 AM](https://user-images.githubusercontent.com/6320236/62231003-541ec800-b380-11e9-8eb9-94e24a2a627c.png)

@dmitrij-borchuk, Is this what you are trying to achieve? 

We want to think of a generic solution to solve this, maybe dropProps can accommodate a generic prop for the Button container. thoughts?

**Comment by ShimiSun** [comment] 2019-07-31 17:44
after discussion: we might consider allowing the generic customization that is allowed with Select.

**Comment by dmitrij-borchuk** [comment] 2019-08-01 09:05
My suggestion is to remove this container https://github.com/grommet/grommet/blob/924f237001ebff76ba107e64ebe291a8869224d3/src/js/components/Menu/Menu.js#L198 so icon and label will be aligned by `Button` component and we already have the possibulity to set properties on the `Button`s

**Comment by ShimiSun** [comment] 2019-08-01 20:53
@dmitrij-borchuk , I suspect removing this line may cause a backward compatibility issue but I'm willing to consider your suggestion. 
Sounds like you are feeling comfortable enough with the code to file a PR, care to give it a try?

**Comment by ShimiSun** [comment] 2019-08-05 14:17
I've added another storybook example to demonstrate how you could still play with the alignment without changes on grommet-core. try to see if it helps you out.

**Comment by dmitrij-borchuk** [comment] 2019-08-08 19:27
@ShimiSun Thank you for the Storybook example. Later I will try to make a pull request if you still need it

**Comment by ShimiSun** [comment] 2019-08-08 19:41
@dmitrij-borchuk yes, feel free to file a PR, this issue will be waiting for you :) appreciate your collaboration.

**Comment by dmitrij-borchuk** [comment] 2019-08-23 18:36
@ShimiSun I have tried to make this fix, but looks like it pretty hard to do it with backward compatibility and without adding new component properties. So I gave up =( sorry

**Comment by ShimiSun** [comment] 2020-05-28 20:15
Thanks, I'll be closing this issue due to the backward compatibility concern and lack of community interest.

**Closed by ShimiSun** 2020-05-28 20:15 UTC
Labels: enhancement
