### ISSUE TITLE
dropContainer element with v1 menu component

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet#2619] opened 2018-12-31 01:42 UTC
I receive the following warning with menu component. The v1 documentation does not say anything on dropContainer prop. Where did it come from?

Warning: React does not recognize the `dropContainer` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dropcontainer` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in nav (created by Box)
    in Box (created by Menu)
    in Menu (at Header/index.js:158)

```
<Menu
  direction={isMobile ? 'column' : 'row'}
  responsive={false}
  pad={{ between: 'medium' }}>
  {isAuthenticated &&
	<Button
	  label='Label1'
	  onClick={this._handleClick1}
	  secondary={true} />
  }

  <Button
	label='Label 2'
	onClick={this._handleClick2}
	secondary={true} />
</Menu>
```

**Comment by ShimiSun** [comment] 2019-01-02 16:11
Hi @nomadus, thanks for taking the time to file an issue, I just wanted to verify that this issue is reproducible in GRommet v1?

**Comment by nomadus** [comment] 2019-01-03 02:32
It happens with G1, not sure if this is a reproducible, I have to check

**Comment by Morkalork** [comment] 2019-02-28 07:43
I'm getting this too, showed up when I upgraded to v1.13.0 (from 1.10.1).

**Comment by Morkalork** [comment] 2019-02-28 08:53
Downgrading to 1.11.0 removes the error.

**Comment by Morkalork** [comment] 2019-02-28 09:11
It seems to have been added in this PR: https://github.com/grommet/grommet/pull/2341/files

**Comment by ShimiSun** [comment] 2020-09-22 07:38
I'll be closing this issue sinsce it is staled. Feel free to make a contribution if the issue is still relevant.

**Closed by ShimiSun** 2020-09-22 07:38 UTC
Labels: 1.0
