### ISSUE TITLE
Selection count is wrong for SelectMultiple and expanded control is smaller than collapsed control

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet#6332] opened 2022-09-15 23:17 UTC
See: https://designer.grommet.io/?id=test-edgar-circenis-hpe-com

With just one out of 5 items selected, it is telling me that I have 23 selected and even though it is showing me only one, it says there are 18 more.

![image](https://user-images.githubusercontent.com/17883783/190524506-07305544-497c-4180-9722-1e6ca04b9fc0.png)
![image](https://user-images.githubusercontent.com/17883783/190524545-4550f69c-b28e-4513-af08-fd7e25eb0539.png)

A second issue is that, when expanding the 3-line control in the first image, the form repaints itself as the underlying control contracts to just one line (as can be detected by looking at the outlines in the second image or trying it yourself in the grommet designer design.  The underlying control should not resize itself unless the actual selection changes.

**Comment by jcfilben** [comment] 2022-09-15 23:43
Thanks for reporting this! It looks like the "23 selected" and "+18 more" issues are occurring when the value is set to undefined. I'll look into this.

As for the other issue of the underlying control resizing, this was a purposeful decision. When the drop is open the underlying input reverts to just showing the placeholder text (so it only takes up one line). This was done to prevent an issue where if the list of options becomes really small, by search for example, the underlying input won't be longer that the drop.

**Comment by ericsoderberghp** [comment] 2022-09-26 14:15
It appears that the the incorrect counts issue has been fixed.

**Comment by ericsoderberghp** [comment] 2022-09-26 14:16
As indicated above, the second issue mentioned is the intended behavior.

**Comment by jcfilben** [comment] 2022-09-26 23:23
> It appears that the the incorrect counts issue has been fixed.

I tested in grommet designer and I am no longer seeing this issue. Most likely this was fixed in https://github.com/grommet/grommet/pull/6339. Marking this as closed.

Grommet designer test file: https://designer.grommet.io/?name=test-1

**Closed by jcfilben** 2022-09-26 23:23 UTC
