### ISSUE TITLE
Title in Header is cut off in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#239] opened 2015-11-09 21:20 UTC
http://www.grommet.io/docs/hpe/develop/header
Look at any example except for the first 2, the e on Title is cut off.
Looks fine in chrome and firefox

![title cutoff on ie11](https://cloud.githubusercontent.com/assets/13527666/11046504/1821a11c-86eb-11e5-8779-c9dd4367058e.PNG)

**Comment by kylebyerly-hp** [comment] 2015-11-09 21:22
Also, looks like the icon is hidden/invisible.

**Comment by kylebyerly-hp** [comment] 2015-11-10 23:56
Probably related, the Title itself is odd in IE11. seems to do something odd with the svg icon.

![image](https://cloud.githubusercontent.com/assets/13527666/11079789/fbe1847c-87cb-11e5-8d99-e3d4dd378471.png)

**Comment by ericsoderberghp** [comment] 2016-02-25 23:57
This is only an issue with IE11. Cannot reproduce on Edge 13.

**Comment by ericsoderberghp** [comment] 2016-02-26 00:27
Fixed in grommet commit f4962e8a28dbefb336dfda2633d36f712f0b7e41.

**Closed by ericsoderberghp** 2016-02-26 00:27 UTC
Labels: in progress
