### ISSUE TITLE
InfiniteScroll within Grid: onMore not triggering after reach end of scroll with max length 

### ISSUE THREAD

**Issue by 2manoj1** [grommet/grommet#2805] opened 2019-02-20 10:38 UTC
- onMore callback function not called
### Expected Behavior
- onMore should call when reach max length so lazy load another group of items.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/q397vv01lw

### Your Environment

- Grommet version: 2.4.0
- Browser Name and version: Google Chrome 72.0.3626.109 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10, 64 bit desktop

**Comment by palecrow** [comment] 2019-02-21 16:30
I feel as though there is a relationship between the step number and this.  If you go to: https://v2.grommet.io/infinitescroll and add `onMore={() => alert('more')}` it won't trigger, but if you add `step={3}` it will.

**Comment by mrebb** [comment] 2019-02-22 06:32
@palecrow @2manoj1 Here is my findings. 

If `step` is not provided as `prop` to `InfiniteScroll`, current logic assumes that the default of `step` as `50`. 
Two possible ways, onMore() function can get triggered. 

1. Try filling array of items with more than 50 and then `step` is not required to be passed in as a `prop`. onMore() function will be called as you scroll down. This works because the `lastPage` value becomes `0` or `-1` when `items` length is `50` or less, which is never going to be equal to `nextEndPage` value that is incremented as user scrolls down. 

2. Passing `step` as prop would automatically call onMore() as the `lastPage` value is derived from `step` value and `items` array length like below. 
```
const lastPage = Math.ceil(items.length / step) - 1;  // if step =10 then Math.ceil(50/10)-1  = 4
....
....
if (onMore && nextEndPage === lastPage) {
              onMore();
            }
```
Hope this clarifies.

**Comment by 2manoj1** [comment] 2019-02-22 07:42
@mrebb @palecrow I tried with step = {25} but its not loading all items also not call the onMore callback function.

Initial Array Size = 101
step = 25
https://codesandbox.io/s/541m963n4n

- I need to update array collection after reach the end of the scroll and all items are rendered through lazy loading.
- Any viewport should work with any size of array collection.

![image](https://user-images.githubusercontent.com/15128569/53226824-5b8bc800-36a2-11e9-9493-ec0392b0d078.png)

* Grommet version: 2.4.0
* Browser Name and version: Google Chrome 72.0.3626.109 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10, 64 bit desktop

**Comment by mrebb** [comment] 2019-02-22 08:09
@2manoj1 I don't see that issue on my side. Here is the screenshot. 

![imageedit_3_8430349819](https://user-images.githubusercontent.com/24405156/53228331-e242a400-36a6-11e9-979c-cbf10bc232fa.gif)

* Grommet version: 2.4.0
* Browser Name and version: Google Chrome 72.0.3626.109 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS High Sierra

**Comment by 2manoj1** [comment] 2019-02-22 08:59
I see that your OS is macOS High Sierra.
I am using Windows 10 Enterprise and Resolution 1920 X 1080. 
I am recorded the issue, please find video in below zip file.

[Video_infiniteScrollissue-Win_10- Google Chrome.zip](https://github.com/grommet/grommet/files/2893122/Video_infiniteScrollissue-Win_10-.Google.Chrome.zip)

**Comment by mrebb** [comment] 2019-02-22 09:44
@2manoj1 Could you please try downloading the code from code sandbox and run on local host.

**Comment by 2manoj1** [comment] 2019-02-22 11:17
@mrebb when change the screen its working fine with step 25. 
My observation was when viewport was small its not called.
Also this issue inconsistent. Different viewport Different result.
In our project onMore called 2 times after its stop.

**Comment by mrebb** [comment] 2019-02-22 12:37
@2manoj1 
How do you mean by 'change the screen'? I tried with different window sizes and haven't seen any issue. Let me know when you have steps to reproduce the exact issue. Otherwise we can close this issue as of now and can be re-opened as needed.

**Comment by palecrow** [comment] 2019-02-22 15:10
So let's reframe the conversation.  Regardless of the number of items or the steps value, the component should always call onMore() once when the user has reached the end of the visual list...because somewhat obviously, there may be more items to add to the list based on onMore()'s results.  @mrebb do you dispute that requirement?

If that is not now InfiniteScroll is meant to work, we will use another component from another library.

I am consistently reproducing the problem, even in https://v2.grommet.io/infinitescroll .

Thank you!

**Comment by oorestisime** [comment] 2019-02-22 15:18
Haven't looked at the code or sandboxes yet, but agreed in any case it makes sense to me as well to call onMore once user reached end of list.

I think there were a few PRs addressing issues on infinite scroll. Wonder whether anyone had the chance to test on latest master to make sure this was not already fixed.

**Comment by mrebb** [comment] 2019-02-22 17:14
> So let's reframe the conversation. Regardless of the number of items or the steps value, the component should always call onMore() once when the user has reached the end of the visual list...because somewhat obviously, there may be more items to add to the list based on onMore()'s results. @mrebb do you dispute that requirement?
> 
> If that is not now InfiniteScroll is meant to work, we will use another component from another library.
> 
> I am consistently reproducing the problem, even in https://v2.grommet.io/infinitescroll .
> 
> Thank you!

@palecrow I totally agree with you. That's how InfiniteScroll is meant to work. However, as per current logic `onMore()` function is triggered with the help of `step` value. So at this point, Either we can update the docs to  make 'step' prop as mandatory for `onMore()` functionality to work OR change the entire scroll logic to handle `onMore()` even when `step` prop is received as undefined or items length is less than 50. Providing `step` is one work around until this is fixed in code.

**Comment by 2manoj1** [comment] 2019-02-25 05:16
> @2manoj1
> How do you mean by 'change the screen'? I tried with different window sizes and haven't seen any issue. Let me know when you have steps to reproduce the exact issue. Otherwise we can close this issue as of now and can be re-opened as needed.
'change the screen' - switching the window and open the window in another desktop window.
- you can see what problem I am getting, given the video in above.

**Comment by RyanCCollins** [comment] 2019-02-25 15:34
I've been asked to take a look at this issue.  Coming into it as an outsider, I can say that the `InfiniteScroll` is clearly broken.  Providing a step is not reliably fixing the problem.

**Comment by ShimiSun** [comment] 2019-02-25 18:05
Thank you all for the collaboration! the fix will be available on the next release.

**Closed by ShimiSun** 2019-02-25 18:05 UTC
Labels: Bug :bug:

**Comment by ericsoderberghp** [comment] 2019-02-25 18:11
The key issue was that InfiniteScroll was basing the available height on the height of the `<body>` element. But, the body element's height was being driven by the InfiniteScroll content.

**Comment by RyanCCollins** [comment] 2019-02-25 18:15
@ericsoderberghp ah okay, sweet! Thanks for looking into that!

**Comment by palecrow** [comment] 2019-02-25 18:20
Thank you!

What is the release cadence?

**Comment by ShimiSun** [comment] 2019-02-25 18:51
I'll try to release by the EOD.
