### ISSUE TITLE
Exception while resizing a window with Table

### ISSUE THREAD

**Issue by reflog** [grommet/grommet#1313] opened 2017-04-17 07:13 UTC
While resizing a responsive Table component, the following exception is thrown:

```
Uncaught TypeError: Cannot read property 'style' of undefined
    at Table._alignMirror (Table.js:464)
    at Table._layout (Table.js:428)
_alignMirror @ Table.js:464
_layout @ Table.js:428
setTimeout (async)
_onResize @ Table.js:423


```

### Your Environment

* Grommet version:  3
* Browser Name and version: Chrome 55
* Operating System and version (desktop or mobile): Windows

**Comment by SuhairZain** [comment] 2017-04-17 09:10
Hi @reflog,
Thanks for the report. Could you provide a minimal reproducible code sample on Codepen or such? You can use this as a starting point: https://codepen.io/pen?template=gaEGPY&editors=0010

**Comment by reflog** [comment] 2017-04-17 13:57
Here you go: https://codepen.io/reflog/pen/BRNMGX
Btw, while preparing the codesample, I've narrowed the problem to the 'scrollable' property of the table. If you remove it - the error disappears.

**Comment by SuhairZain** [comment] 2017-04-17 18:02
Hi @reflog,
I tried the codepen but it seems to be working fine for me on my Linux dev machine with Firefox 52 and Chrome 54. I then created a project locally with the code on codepen, it worked fine. I also used browserling.com to test on a Windows 7 machine with Chrome 55. It went fine without any issues.

What I tried to do were these, let me know if you got the error while doing something else:
1. Load the codepen.
2. Open the in-codepen console as well as the browser console.
3. Drag the codepen result view size adjusters, no output in either consoles.
4. Resize the browser window, no output in either consoles.

Were these the steps you followed?

**Comment by reflog** [comment] 2017-04-18 07:10
Here's how to reproduce. Works in Firefox too:

![as2d](https://cloud.githubusercontent.com/assets/109876/25118485/4072ca42-241f-11e7-8fa1-644ad3d8e9ac.gif)

**Comment by SuhairZain** [comment] 2017-04-18 07:24
@reflog,
Nice screencap. 😄 

The issue happens when going back from the mobile view to desktop, but seems to happen at random. Got to find the source. :)

**Comment by adamroldfield** [comment] 2017-05-26 23:39
The mirror is rebuilding. 

This will fix it:
 if (mirrorCells.length !== cells.length)
        return;

Insert here:

_alignMirror () {
    if (this.mirrorRef) {
      const tableElement = this.tableRef;
      const cells = tableElement.querySelectorAll('thead tr th');
      const mirrorElement = this.mirrorRef;
      const mirrorCells = mirrorElement.querySelectorAll('thead tr th');

      if (mirrorCells.length !== cells.length)
        return;

**Comment by alansouzati** [comment] 2017-07-06 00:49
Fixed in https://github.com/grommet/grommet/commit/fda2c3cff10dd858437e5f9cb80d5c6967334775

**Closed** 2017-07-06 00:49 UTC
