### ISSUE TITLE
Trailing comma in package.json

### ISSUE THREAD

**Issue by stefankeil** [grommet/grommet#637] opened 2016-06-16 13:21 UTC
Hey Guys,

i found an issue in the package.json after creating an sample app using.
```grommet init sample-app```

Failed to parse json
Trailing comma in object at 16:3

cheers,
stefan

**Comment by alansouzati** [comment] 2016-06-16 17:27
Sorry about that, this has been fixed in the main branch. closing as duplicate of https://github.com/grommet/grommet/issues/628

**Closed by alansouzati** 2016-06-16 17:27 UTC
