### ISSUE TITLE
`WorldMap` component goes off after state update.

### ISSUE THREAD

**Issue by Ojas-Sri** [grommet/grommet#6265] opened 2022-08-09 10:26 UTC
- `WorldMap` component's labels misalign after a state update to the `places` props.
- Code style : `<WorldMap places={state? places1 : places2} />`

### Expected Behavior

- The Place labels should be placed at their correct coordinates after state updates.

### Actual Behavior

- The Place labels misalign after state update to the `places` props.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-world-map-issue-zyhtu5?file=/src/App.js

![PR (33)](https://user-images.githubusercontent.com/80472243/183626088-63e325ec-db78-41ae-bc80-2d148e911533.gif)

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: Chromium
- Operating System and version (desktop or mobile): Not tested

**Comment by uldz** [comment] 2022-10-08 11:49
Hi @jcfilben! I'd like to try it! Will it be the correct way to test this issue by adding a button in the local storybook story? Will it be a similar env to reproduce the issue?

**Comment by jcfilben** [comment] 2022-10-10 15:23
Hi @uldz awesome that you are interested in working on this! You're right, I think the best way to test this is to add a state button to a WorldMap storybook story. Make sure your branch is up to date with master and then run `yarn storybook` and test out the issue.

**Comment by jcfilben** [comment] 2022-10-26 21:28
Hey @uldz just checking in on this to see if there were any questions and if it something you are still interested in working on

**Comment by uldz** [comment] 2022-10-26 22:01
Hey, yes I’m in. Just had some hard times with my main project. I will try my best in few days🙂

**Comment by jcfilben** [comment] 2022-10-26 22:10
No worries! Just wanted to check in

**Comment by uldz** [comment] 2022-10-30 16:51
It looks like there are issues with render order - Drops render faster than ref places appear on WorldMap. Trying to figure out how to make render with already rendered dropTargets.

**Comment by uldz** [comment] 2022-10-30 17:32
Sorry, probably don't have much time for this now. If someone will get to this ticket, pls, reassign it. Thank you.

**Comment by jcfilben** [comment] 2022-10-31 22:22
No worries, appreciate the update! I will remove your assignment from this issue

**Comment by hwdsjtu97** [comment] 2023-01-18 22:11
I am interested in this issue. Can I have a try?

**Comment by jcfilben** [comment] 2023-01-19 00:18
Hey @hwdsjtu97 feel free to work on this and reach out if you have any questions!

**Closed** 2023-01-20 02:20 UTC
Labels: help wanted, bug
