### ISSUE TITLE
Error in ./src/App.js Module not found: [CaseSensitivePathsPlugin] 

### ISSUE THREAD

**Issue by isaacsultan** [grommet/grommet#3249] opened 2019-08-05 14:44 UTC
importing Grommet searches for the module (which does not exist) at `/Users/isaacsultan/smallworld/node_modules/grommet/index.js` when it is installed at `/Users/isaacsultan/smallworld/**frontend**/node_modules/grommet/index.js`

### 

```
Failed to compile.

Error in ./src/App.js
Module not found: [CaseSensitivePathsPlugin] `/Users/isaacsultan/smallworld/node_modules/grommet/index.js` does not match the corresponding path on disk - File does not exist.
 @ ./src/App.js 14:15-33
```

#### Filestructure

```
smallworld/
  frontend/
    node_modules/
       grommet/
    src/
      App.js
```

```
//App.js

import { Grommet } from "grommet"

const App = () => {
  return (
    <Grommet> 
       ....
    </Grommet>
  )
}

```

### Your Environment

- Grommet version: "grommet": "^2.7.4",
- Browser Name and version: Chrome  75.0.3770.142
- Operating System and version (desktop or mobile): MacOS 10.14.5

**Comment by oorestisime** [comment] 2019-08-05 15:04
Hm weird, can you post a better reproduction? maybe a repo or on codesandbox?

**Comment by isaacsultan** [comment] 2019-08-05 15:21
> Hm weird, can you post a better reproduction? maybe a repo or on codesandbox?

I tried reproducing with fresh create-react-app but the error does not occur.

Within my own project, the issue is solved by using  a relative import path rather than allowing npm to set the path. 

However, it would still be nice if this bug could be squashed, so keeping issue open.

**Comment by ShimiSun** [comment] 2019-08-05 19:53
I'm not sure how we can tackle this one if we can't reproduce it, thoughts?

**Comment by oorestisime** [comment] 2019-08-05 20:01
Yeah i am having a hard time figuring how to tackle this as well. even a bit of markup code could possibly help.

**Comment by ShimiSun** [comment] 2019-08-06 21:06
I'm waiting to see if any user from the community will face this problem and share an environment we can reproduce the issue with. until then I'm not sure what we can do.

**Comment by oorestisime** [comment] 2019-08-21 22:46
Closing this! feel free to reopen if you manage to reproduce. Don't hesitate to ping us on slack either if you want us to take a closer look at a repo you have!

**Closed by oorestisime** 2019-08-21 22:46 UTC
Labels: waiting
