### ISSUE TITLE
TextInput suggestions should close when page is scrolled down

### ISSUE THREAD

**Issue by Pitasi** [grommet/grommet#4598] opened 2020-10-12 13:13 UTC
I'm using TextInput with some suggestions, not many, as suggested in docs.

### Expected Behavior

I have a main TextInput in the header of the page (search box).

I write something in my TextInput and some suggestions appear.

I decide to not go ahead with any suggestion, instead, I scroll the page down to see more of it.

The suggestions box closes, freeing my view.

### Actual Behavior

The suggestions box doesn't close, it is position:fixed so it remains on top of everything while I scroll the page. I have to click away so the TextInput loses focus and suggestions disappear.

### Steps to Reproduce

1. Create a long page with TextInput on top, with a couple suggestions
2. Scroll the page 

### Your Environment

- Grommet version: 2.14
- Browser Name and version: Chromium 86.0.4240.75
- Operating System and version (desktop or mobile): Desktop, linux

**Comment by Pitasi** [comment] 2020-10-15 10:17
As a general idea (I haven't digged into the code yet), I would suggest a behaviour like that: when the TextInput is rendered, start an [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) for it. When the TextInput is no longer visible in the page, force close the suggestions box.

**Comment by ShimiSun** [comment] 2021-02-09 04:57
Trying to reproduce the issue on the grommet site, the TextInput (search) works as expected.
By design, the drop of the suggestion shouldn't close unless you take away its focus by clicking outside of the component or use the keyboard of `onEsc` to close the drop. 
Regarding the position issue you've mentioned, of describing the drop hanging on the page, it might be an  additional style from your app that causes it, since it is not reproducible on grommet, here is a quick video that demonstrates how the functionality works as expected using grommet v2.16.3.

https://user-images.githubusercontent.com/6320236/107317695-6212d600-6a58-11eb-9db7-a2e13b5a66f2.mov

**Comment by jcfilben** [comment] 2021-09-16 18:42
Closing since we were not able to reproduce the position issue and the Drop should stay open even if you scroll down. Feel free to reopen with a code example or if you want to continue discussion on this topic.

**Closed by jcfilben** 2021-09-16 18:42 UTC
Labels: waiting
