### ISSUE TITLE
How to create customized themes?

### ISSUE THREAD

**Issue by stonecold123** [grommet/grommet#704] opened 2016-07-17 09:00 UTC
I read from https://github.com/grommet/grommet/issues/684 that you can create a customized theme. I cloned **_hpe.defaults.scss**  and modified some of the colors. Can you tell me how to apply it to grommet?

**Comment by sahil28v** [comment] 2016-07-17 09:29
If you are referencing the "get started project"-- replace this line "import '../scss/index.scss' " in src/js/index.js with path to your scss.

I'm using webpack+express+redux : So I'm using importing this in my outermost App component:   import 'grommet/grommet-hpinc.min.css' to import 'path-to-my-sass'.

**Comment by stonecold123** [comment] 2016-07-17 14:22
Thanks for your suggestion. So in order to apply a custom theme, I need to create a new copy of **./node_modules/grommet/scss/hpe/index.scss** as **`/custom_path/index.scss`**, change the path of **@import 'hpe.defaults';**  to my custom hpe.defaults, then imported  **`/custom_path/index.scss`** in my outermost app component, am I right? I will test it later.

**Comment by sahil28v** [comment] 2016-07-17 19:50
Sorry I jumped there , simply that won't work - since index.scss further imports:@import 'vanilla.defaults';  @import  '../grommet-core/index'; @import 'objects.button-vanilla';   

Import both in your outermost component--- 
import 'grommet/grommet.min.css'
import '../../styles/custom.css';       // Override the class properties in this custom file 

Ex: Change neutral-1 color --> 
.grommetux-background-color-index-neutral-1{
	background: #16A765;
}

I'll check into this later & update you incase I find the better solution.

**Comment by alansouzati** [comment] 2016-07-18 17:05
hey @stonecold123 you plan is about right. you need to create the index.scss that uses your `_yourcompany.defaults.scss`.

```scss
@import '_yourcompany.defaults';
@import 'grommet/grommet-core/index';
```

FYI: we are working on the new site and we are planning to add documentation on how to create a custom theme. The variables defined inside HPE defaults are not the only ones that we support for customization. Unfortunately there is not documentation today that will document all the supported variables to customize in a theme.

**Comment by svnlto** [comment] 2016-09-22 12:54
Are you going to ship v1.0.0 without documenting how to create custom themes?

**Comment by alansouzati** [comment] 2016-09-27 22:21
Most likely yes. Keep in mind that v1.0.0 is not meant to be the final release of Grommet, there are a lot of items, including documenting custom themes, that will be executed after 1.0.0.

Our backlog is currently open: https://waffle.io/grommet/grommet

You can see what we are working on, and what is currently planned for the upcoming 1.0.0.

Our reasoning behind prioritizing the items was to fix first the issues/enhancements that will require API changes. 

Documenting custom theme is something we can definitely do short after 1.0.0 without affecting existing users.

Thanks for raising this concern, it also help us prioritize what we will work next.

**Comment by ericsoderberghp** [comment] 2016-11-17 21:41
Here are some details on how the color variables work that would be good to include in any documentation about theme colors:

I would recommend not worrying too much about the '-a’ and '-t’ versions to start with.

The status colors drive the Status icons and the background color for Notification.

The neutral colors are only used when the developer asks for one of them, via `neutral-1`, `neutral-2`, etc.

The brand color is used as the background color for `<Button primary={true} />` and the text color and icon color in `<Anchor primary={true} />`. It is also used whenever a developer specifies `colorIndex='brand'` for a component that accepts the `colorIndex` property.

The graph colors are used by default in Chart, Meter, Distribution, SunBurst to distribute colors among the series values. The developer can always set a custom `colorIndex` on any particular series value to any color. To use a graph color, they would use `colorIndex='graph-1'` for example.

For Distribution, we recommend not trying to express too much detail via color gradations. Instead, I’d go with your basic concept of using `accent-1` for ‘important’ things that the user’s attention should be called to, `neutral-1` and other neutrals for ‘normal’ things, and `unset` for ‘uninteresting’ things that should be subdued.

**Comment by jaitaiwan** [comment] 2016-11-30 10:43
In a search to create rapid applications, we came across grommet and we've been attempting to build a custom bootstrap just to give it a go.

We've found the styling in grommet a bit cumbersome so far, but it's the only WCAG, enterprise level framework we've been able to find.

What I'd like to do is implement a similar styling system to the way react-toolbox works. This means enabling css-modules and allowing component's classnames to be overwritten by either a theme prop or theme context keyed to a namespace depending on the component.

Is this something that would be of interest to the entire project or something that grommet would prefer kept in user-land?

**Comment by alansouzati** [comment] 2016-11-30 16:27
We have tried css-modules solution in the past. We want to try it again, so yes this is something we are interested to add as part of Grommet 2.0.

Here is the blog post I wrote about my experience with CSS in JS sometime ago:

https://blog.grommet.io/post/2016/08/10/css-in-js-may-not-be-the-solution-to-all-your-problems

**Comment by jaitaiwan** [comment] 2016-11-30 20:55
Thanks @alansouzati I did read that. I think you were super close to a solution. We'll fork grommet then and get to work on this and see how easy/hard it is. I think luckily enough it seems that grommet's sass is componentised enough for this to be a pretty easy transition.

**Comment by alansouzati** [comment] 2016-12-01 00:06
Yeah, there are challenges that I'm still curious how to solve with the "modular" way of CSS in JS.

Specially around hot fixes for ie11 😢 

Checkout this file:

https://github.com/grommet/grommet/blob/master/src/scss/grommet-core/_objects.layer.scss#L49

And this issue:

http://stackoverflow.com/questions/40855067/flexbox-div-with-column-direction-and-inner-max-width-breaks-in-ie11

I'm really not sure how to solve these sort of things using a pure modular approach.

**Comment by jaitaiwan** [comment] 2016-12-01 00:17
I understand. The css modules class simply converts class names to ids, so if you define the same class a couple of times, even in a media query it is given the same id and the media query will work only on that class.

```scss
.#{$grommet-namespace}form { // Class becomes .someid
  // Some styles
}

.#{$grommet-namespace}sidebar-form {
  // Some other styles
}

@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    .#{$grommet-namespace}form { // Class becomes the same .someid
      max-width: 100vw;
    }

    .#{$grommet-namespace}sidebar-form {
      max-width: 100%;
    }
  }
}
```

The only issue here is targeting the `.sidebar .form` class couldn't happen because of the unique ids. What I'd suggest then is just documenting that when putting a form in a sidebar, use the `.sidebar-form` class.

That would pretty much solve the issue from my perspective.

**Comment by alansouzati** [comment] 2016-12-01 00:53
Sorry I should have been more clear. The issue I was referring to is the nesting of `.sidebar .form` inside Layer.

I'm not sure how documenting will solve the issue, since we don't expose the css modifiers (and we don't want to as it is an internal representation).

Well, maybe a good exercise would be to start from Layer and make sure the following code works well in IE11:

```javascript
  <Layer>
     <Form>
       <FormFields>
         <FormField label="test">
           <input type="text" />
         </FormField
       </FormFields>
     </Form>
  </Layer>
```

Keep us posted!

**Comment by jaitaiwan** [comment] 2016-12-01 01:06
I think the styling documentation would end up telling people what namespace in the theme context a component would use. So you could tell them that they can override the styles by providing an alternative class name. At the same time you'd then make a note for the form to say if it's inside a layer which itself is inside the sidebar, then use x code to fix a known bug in IE.

React Toolbox's documentation explains for each component what key on context can be used to override stylings:
> [For the AutoComplete component] If you want to provide a theme via context, the component key is RTAutocomplete

I think this could work well in Grommet, although I think we'd need to make more effort to explain exactly how styling with context works.

I don't think this is insurmountable and in fact I feel its a little more explicit and idiomatic to do it that way. What do you reckon?

**Comment by jaitaiwan** [comment] 2016-12-01 03:37
Just took a look through waffle.io. I think that #732 could be closed and future conversation continued here as its fairly all-encompassing. I also believe that #1054 partially blocks the completion of this and #732 as it prevents theme context being provided nicely down the node chain.

**Comment by tracybarmore** [comment] 2017-01-19 21:35
Issues closure dependent on #1142

**Comment by nomadus** [comment] 2017-02-14 13:23
I would like to create a custom theme based on the existing Grommet themes, but I could only find the minified versions of the css files, how could I find the original versions?

**Comment by alansouzati** [comment] 2017-02-14 17:50
I would recommend checking this folder:

https://github.com/grommet/grommet/tree/master/src/scss

For example the Aruba theme is here, and you can see some of the variables we override:

https://github.com/grommet/grommet/blob/master/src/scss/aruba/_aruba.defaults.scss

This is how you would import it:

https://github.com/grommet/grommet/blob/master/src/scss/aruba/index.scss

Also you can see everything is based off the `grommet-core` folder.

Hope it helps!

**Comment by snaemi** [comment] 2017-03-06 14:23
It looks like some of the colors in grommet-core/_settings.color.scss do not have the !default flag, preventing me from overriding (like $colored-text-color, $active-colored-text-color). I've applied the changes to my environment, but am curious as to whether there is any specific reason the flag is missing or if there are plans to update those in the future?

**Comment by alansouzati** [comment] 2017-03-08 19:20
It should be not missing , it is a bug. Would you mind to send a pull request to add the `!default` flag to these variables? thanks for identifying this @snaemi

**Comment by tracybarmore** [comment] 2017-03-14 21:03
Fixed with #1231

**Comment by maxs15** [comment] 2017-03-30 15:57
@alansouzati you should try https://github.com/styled-components/styled-components

**Comment by Serexx** [comment] 2017-08-03 17:46
Referencing this thread I'm attempting to create a custom Theme for Grommet and am encountering an error I am unable to resolve:

>      File to import not found or unreadable: inuit-defaults/settings.defaults
>      
>      // this file doesn't exist!
>      Parent style sheet: C:/Data/Websites/Devel/Website/theme/grommet-core/_settings.scss
>      
>      in C:\Data\Websites\Devel\Website\theme\grommet-core_settings.scss (line 4, column1)
>        

I can see what the issue is, but I'm not sure how to resolve it, whether its possible with the structure I am using.   The file

`C:/Data/Websites/Devel/Website/theme/grommet-core/_settings.scss`

does not exist, I believe it appears because I have referenced 

`'grommet/scss/grommet-core/index.scss'`

in my theme's Index file (see below)  and the Grommet file in turn references the inuit-defaults/_setttings.scss file.

I tried importing the inuit file in my Index, before the Grommet import, but not surprisingly that didn't work, as the imported Grommet file isn't looking for it there.

So far, unless there is an @Import feature I am not aware of (quiet possible!) I can't see a way around the relational problem without copying Grommet Core files directly into my project which seems to defeat the purpose of node-based design.

It's quite possible that I've missed something worthy of a face-palm but I can't see it, so I'll lay out what I have done and ask for some guidance -

**structure**
src
---scss
------themes
--------dark
-----------  _dark.defaults.scss
-----------  _objects.material.dark.scss
-----------  index.scss

**/src/scss/themes/dark/index.scss** then is:

          @import 'inuit-defaults/settings.defaults';  //no help of course
          @import 'grommet/scss/grommet-core/index.scss';
          @import 'dark.defaults';
          @import 'objects.material-dark';

**webpack.config.babel**

```javascript
import path from 'path';
import webpack from 'webpack';
import CopyWebpackPlugin from 'copy-webpack-plugin';

const env = process.env.NODE_ENV || 'production';
......
const loaderOptionsConfig = {
  options: {
    sassLoader: {
      includePaths: [
          './node_modules',
          './node_modules/inuit-defaults'  //hello?
      ]
    }
  }
};
.....
plugins.push(new webpack.LoaderOptionsPlugin(loaderOptionsConfig));
......
export default Object.assign({
  entry: './src/js/index.js',
  output: {
    path: path.resolve('./dist'),
    filename: 'index.js',
    publicPath: '/'
  },
  resolve: {
    extensions: ['.js', '.scss', '.css', '.json']
  },
  plugins,
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  },
  module: {
    rules: [
      {
        test: /\.js/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test: /\.scss$/,
        use: [
          { loader: 'file-loader', options: { name: '[name].css' } },
          { loader: 'sass-loader',
            options: {
              outputStyle: 'compressed',
              includePaths: [
                  './node_modules',
                  './node_modules/inuit-defaults'  //trying to find it
              ]
            }
          }
        ]
      }
    ]
  }
}, devConfig);

```
**package.json**

```javascript
"dependencies": {
"body-parser": "^1.15.2",
"compression": "^1.6.2",
"cookie-parser": "^1.4.3",
"express": "^4.14.0",
"grommet": "^1.3.4",
"grommet-addons": "^0.4.0",
"inuit-defaults": "^0.2.3",   //just in case Grommet is not loading them
"inuit-normalize": "^4.1.1",
"inuit-reset": "^0.1.1",
"inuit-shared": "^0.1.5",
"morgan": "^1.7.0",
"path-to-regexp": "^1.7.0",
"query-string": "^5.0.0",
"react": "^15.4.0",
"react-addons-create-fragment": "^15.6.0",
"react-dom": "^15.4.0",
"react-drag-drop-container": "^4.0.0",
"react-intl": "^2.1.5",
"react-redux": "^4.4.5",
"react-router-dom": "^4.0.0",
"reactjs-mappletooltip": "^1.2.0",
"redux": "^3.6.0",
"redux-devtools-extension": "^2.13.2",
"redux-thunk": "^2.1.0",
"shortid": "^2.2.8",
"ws": "^1.1.1" },

"devDependencies": {
"babel-cli": "^6.22.2",
"babel-core": "^6.5.2",
"babel-eslint": "^7.1.1",
"babel-jest": "^18.0.0",
"babel-loader": "^6.2.10",
"babel-plugin-transform-object-rest-spread": "^6.19.0",
"babel-preset-es2015": "^6.18.0",
"babel-preset-react": "^6.16.0",
"babel-preset-react-hmre": "^1.1.1",
"babel-register": "^6.18.0",
"copy-webpack-plugin": "^4.0.1",
"cross-env": "^3.1.4",
"es6-promise": "^4.0.5",
"eslint": "^3.9.1",
"eslint-config-airbnb": "^13.0.0",
"eslint-parallel": "^0.1.0",
"eslint-plugin-import": "^2.2.0",
"eslint-plugin-jsx-a11y": "^2.2.3",
"eslint-plugin-react": "^6.6.0",
"file-loader": "^0.9.0",
"grommet-cli": "^3.0.0",
"json-loader": "^0.5.4",
"node-sass": "^4.1.1",
"nodemon": "^1.11.0",
"pre-commit": "^1.2.2",
"react-dev-utils": "^0.4.2",
"react-test-renderer": "^15.4.1",
"redux-devtools": "^3.4.0",
"redux-devtools-dock-monitor": "^1.1.2",
"redux-devtools-log-monitor": "^1.3.0",
"sass-lint": "^1.10.2",
"sass-loader": "^6.0.3",
"webpack": "^2.2.1"
```

Not to muddy the waters but I should mention that this project lives as an SPA inside a .Net MVC app, being served by IIS Express. I don't think that should impact anything but just in case....

Any suggestions / pointers would be greatly appreciated

**Comment by alansouzati** [comment] 2017-08-03 17:52
I came across a very interesting project that create a theme on top of Grommet and publishes that to npm. So in their apps they just refer to the compiled css. I think this can help you:

https://github.com/zooniverse/zoo-grommet/blob/master/package.json#L9

I cannot see anything wrong with your configuration 😢

**Comment by Serexx** [comment] 2017-08-03 18:01
Thats a great idea I'll look into it - thanks for the quick response!

**Comment by Serexx** [comment] 2017-08-04 17:45
Hi Alan - FYI - although that is a great idea and I'm planning on doing something similar, I wasn't comfortable just side-stepping the root problem so I re-constructed from the ground up until I hit the issue  - turns out I'd inadvertently upgraded **react-router** to V 4 (now **react-router-dom**  !hooray for 'breaking changes'!) so of course if the router breaks, all kinds of things might be 'not found'. 

Reverting to 3.0 solved it.

Hope this helps anyone else that encounters it.

**Comment by alansouzati** [comment] 2017-08-04 18:02
thanks for being so kind to share your experience with the community.

**Closed** 2018-01-29 20:39 UTC
Labels: help wanted
