### ISSUE TITLE
Grommet Layer onEsc and onClickOutside not working when modal is set false

### ISSUE THREAD

**Issue by karunakarareddyp** [grommet/grommet#3771] opened 2020-02-21 09:45 UTC
Click on a button displaying Layer form at Top Right side corner of the window. And i am trying to close the Layer form by using onEsc and onClickOutside attributes but is not working when modal is set false. 
If i set modal is true then it's working. 

### Expected Behavior
The Layer form should close on by pressing Esc key and Click on outside of the layer form.

 <Layer
        onEsc={this.onCloseLayer}
        onClickOutside={this.onCloseLayer}
        modal={false}
        position='top-right'>
    <div>Content</div>
</Layer>
- Grommet version: 2.11.0
- Browser Name and version: Chrome 80.0.3987.116 
- Operating System and version (desktop or mobile): Mac OS (deesktop

**Comment by IanKBovard** [comment] 2020-02-21 17:51
i can confirm that this is an existing bug, not a regression. Using grommet v2.10 the issue still exists.

https://codesandbox.io/s/grommet-sandbox-cvmyo?fontsize=14&hidenavigation=1&module=%2Fsrc%2FLayer.js&theme=dark

**Comment by karunakarareddyp** [comment] 2020-02-24 11:39
Is there any plan to fix in upcoming releases?

**Comment by ShimiSun** [comment] 2020-02-24 14:08
Ye. does the codesandbox shared above reproduce the exact same thing you are describing?

**Comment by mlonn** [comment] 2020-02-25 19:46
Looks like the onEsc bug came here 
https://github.com/grommet/grommet/commit/595b3a05a47a843f0f22b133f4f5d109ba0f2a8c
when focus was removed for non modals. I changed the keyboard to be on the document instead. and moved the onClickOutside to not rely on the overlay

**Comment by karunakarareddyp** [comment] 2020-02-26 04:19
@ShimiSun Yes it is exactly the same issue.

**Comment by IanKBovard** [comment] 2020-04-23 18:07
working on this now, as well

**Comment by IanKBovard** [comment] 2020-04-24 15:48
It looks like onClickOutside never worked when layer modal was set to false. Was this intentional? Only the overlay when modal was set to true has the onclickoutside event.

**Comment by mlonn** [comment] 2020-05-06 12:58
It was more complicated than I thought..

**Comment by ericsoderberghp** [comment] 2020-08-27 15:04
What is the design scenario driving this? If the non-modal Layer is something like a notification toast, I don't see Esc or clicking outside being a reasonable way to close it. So, what is a scenario where the Layer isn't modal, meaning it doesn't have focus and the user is free to interact with the page underneath, where interacting with the page should make the Layer go away?

**Comment by IanKBovard** [comment] 2020-09-01 18:56
@karunakarareddyp I agree with ericsoderberghp. Is there a specific use case that non-modal layers need to act this way? I'm guessing a different component might better serve your purpose.

**Comment by IanKBovard** [comment] 2020-09-17 14:41
A requirement of a non-modal dialogue is to let users interact with content beneath it(toasts, notifications, alerts). onclickoutside and onesc would break that. @mlonn @karunakarareddyp get back to me and we can close this issue.

**Comment by mlonn** [comment] 2020-09-17 14:42
Sounds good. I was just taking and open issue when I had some free time. Which I don't any more.

**Comment by karunakarareddyp** [comment] 2020-09-17 16:05
@IanKBovard Sounds good to me. You can close this issue.

**Comment by ericsoderberghp** [comment] 2020-11-05 22:48
A design example for needing this is when a navigation sidebar is added when clicking on a Button. Clicking outside the Layer, or typing Esc, should cause the Layer to close.

**Comment by taysea** [comment] 2020-11-17 03:55
@ericsoderberghp Can you elaborate on why this use case would fall outside of the above discussion on modal vs nonmodal layer behavior?

**Comment by ericsoderberghp** [comment] 2020-11-17 16:22
For non-modal cases, I think we should allow Layer to be used similar to Drop, as a means of showing extra content overlaying the the rest of the UI and anchored to a particular target or area of the page. Drop allows `onEsc` and `onClickOutside` and so should Layer. My comment above in August was asking for a design scenario that we could drive the behavior from. I can see one now. My more recent comment above mentions one such example, that of a menu sidebar, but I think the Drop analogy presents a generic way of looking at it.

**Comment by taysea** [comment] 2020-11-30 16:27
@karunakarareddyp Just an update here, we've merged an enhancement for onClickOutside for modal={false} in the latest release. I am still working on incorporating an enhancement for the onEsc when modal={false}.

**Closed** 2021-01-12 17:03 UTC
Labels: Bug :bug:
