### ISSUE TITLE
Why is select dropdown going up?

### ISSUE THREAD

**Issue by cehidi** [grommet/grommet#1005] opened 2016-10-25 05:05 UTC
Here is my code;

```
                        <Form>
                          <FormField>
                            <Select id="item1" name="item-1" options={["one", "two", "three", "four", "five", "six", "seven", "eight"]} value="one" />
                         </FormField>
                       </Form>
```

When I select, the dropdown goes up instead of down, what is causing this and how can I fix it?

**Comment by davidcalhoun** [comment] 2016-10-26 00:39
I created a Codepen from your example, but can't reproduce the issue: http://codepen.io/franksvalli/pen/mAokgk?editors=0010

Could you fork that and add in more code to make it more like yours?

Thanks!

**Comment by alansouzati** [comment] 2016-10-26 23:16
Thanks for the codepen @davidcalhoun
 
It depends on the height of the screen. if there is not enough space for it to render at the bottom, it will be rendered on top of the select.

Here is the forked pen that illustrates a case where it will be rendered at the top.

http://codepen.io/alansouzati/pen/zKXLvB?editors=0010

Currently I'm experiencing a weird problem with scroll position moving up. I will investigate it now and get it fixed.

**Comment by alansouzati** [comment] 2016-10-27 21:27
I've just fixed the jumping issue in this commit:

https://github.com/grommet/grommet/commit/254caef679093ebf1173d4b5b60c0df278cdd3f4

The position of the drop is an expected behavior. I'm closing this issue for now. Feel free to re-open it if you believe this is still an issue.

**Closed by alansouzati** 2016-10-27 21:27 UTC
