### ISSUE TITLE
Can't resolve 'styled-components'

### ISSUE THREAD

**Issue by adriangabardo** [grommet/grommet#3770] opened 2020-02-21 00:28 UTC
### Expected Behavior
`npm i grommet-icons` should work by itself

### Actual Behavior
Need to manually install styled-components after the grommet install

Can you add styled-components to the package.json dependencies? It will install with grommet automatically then.

**Comment by oorestisime** [comment] 2020-02-21 07:12
Hey there,

styled-components is intentionally a peer dependency so we don't lock you in our version of styled-components. Same with react! 
This is not a bug but a feature :)

**Comment by IanKBovard** [comment] 2020-02-21 15:29
@adriangabardo Was oorestisime able to answer your question?

**Comment by IanKBovard** [comment] 2020-02-25 20:40
@adriangabardo anything else you'd like to add before we close this issue?

**Comment by adriangabardo** [comment] 2020-02-25 23:39
Ah, the old feature not a bug trick ;) 
Just wanted to double checked, happy to close the issue guys.

**Closed** 2020-02-26 17:04 UTC
