### ISSUE TITLE
🐛 Select component - Maximum update depth exceeded

### ISSUE THREAD

**Issue by AntoLC** [grommet/grommet#6594] opened 2023-01-23 10:42 UTC
### Actual Behavior

If we scroll too fast in a `Select` component with a big array, the app crash.
The error comes from `InfiniteScroll.js:97`.

> Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### URL, screen shot

![Screenshot (128)](https://user-images.githubusercontent.com/25994652/214015844-6b25b4cc-b9fe-4773-bf90-a2b89768393d.png)

[210548972-11c3aae2-948b-4ddc-8ef0-0eb94b91d818.webm](https://user-images.githubusercontent.com/25994652/214021101-33ac3d81-f659-4754-a2d0-dc4b85c9faa8.webm)

### Steps to Reproduce

`options` has to be quite big ( > 150 rows), then scroll with the mouse wheel up and down during a few seconds.
Bigger your array is (particularly with an array of object ) and more often the bug will occur.

```
const options: string[] = ...
<Select
   options={options}
/>
```

### Your Environment

- Grommet version:  `"grommet": "2.28.0",`
- Browser Name and version: 
> Chrome is up to date
> Version 109.0.5414.75 (Official Build) (64-bit)

- Operating System and version (desktop or mobile): `desktop `

**Comment by MikeKingdom** [comment] 2023-01-23 19:15
I tried to duplicate this in 2.28.0 (and 2.29.1) but was not able to. I used:
```jsx
import { Grommet, Select, Box } from "grommet";

const options = Array(2000)
  .fill()
  .map((_, i) => `item ${i + 1}`);

export default function App() {
  return (
    <Grommet full>
      <Box align="center" justify="center" fill>
        <Box width="small">
          <Select options={options} />
        </Box>
      </Box>
    </Grommet>
  );
}
```

@AntoLC  If you can duplicate in a codesandbox example I'm happy to take another look.

**Comment by jcfilben** [comment] 2023-02-08 23:41
Closing since we were unable to reproduce this issue. Feel free to re-open with a [codesandbox](https://codesandbox.io/s/m7mml8l0zj) example if you are still experiencing this issue.

**Closed by jcfilben** 2023-02-08 23:41 UTC
Labels: waiting
