### ISSUE TITLE
v2 Selection Lags

### ISSUE THREAD

**Issue by jesseolsen** [grommet/grommet#2292] opened 2018-09-17 21:28 UTC
### Expected Behavior

When clicking on a selection field, the selection focus should highlight the field that was just clicked.

### Actual Behavior

When clicking on a selection field, the selection focus highlights the PREVIOUSLY selected field.

### URL, screen shot, or Codepen exhibiting the issue

![dashboard-selections](https://user-images.githubusercontent.com/6043493/45651107-a79c6600-ba8d-11e8-9fcc-b1d533cd5eb1.gif)

### Steps to Reproduce
 1. Click on a field
 2. Click on another field
 3. Notice the delay in the selection (see animated gif)

### Your Environment

* Grommet version: 2.0.0-beta.5
* Browser Name and version: Latest Chrome
* Operating System and version (desktop or mobile): desktop Windows 10 64-bit

**Comment by alansouzati** [comment] 2018-09-17 21:53
Thanks for reporting this. Can you put this in a codesandbox ?

**Comment by RyanCCollins** [comment] 2018-10-09 19:45
@alansouzati I tried to use the playground to create an example, but it kept crashing on me.  I'll ask @jesseolsen to follow up but not sure he's going to be able to anytime soon.  The issue seems to happen any time you use a drop button or a select and we see it all across OneSphere.  Ping me if you need more details.  Thanks!

**Comment by alansouzati** [comment] 2018-10-09 20:42
yeah I'm investigating right now why the playground is crashing. it is doing that for me too.

**Comment by alansouzati** [comment] 2018-11-14 23:21
are you still facing this @RyanCCollins @jesseolsen ?

**Comment by jesseolsen** [comment] 2018-11-19 17:49
Yes, I am still seeing this.

**Comment by ShimiSun** [comment] 2019-02-08 20:49
Can you please reproduce the issue? Either the built-in grommet playground on the site or using `Grommet v2 Template` on https://codesandbox.io/s/m7mml8l0zj. @jesseolsen

**Comment by mrebb** [comment] 2019-02-20 08:15
> Yes, I am still seeing this.

@jesseolsen I created a code sandbox forked from`Grommet v2 Template` with two select fields. I  couldn't reproduce the issue that you are facing. Could you try with `2.4` version of grommet and see if the issue still persists. 

Here is the code sandbox link: https://codesandbox.io/s/8x5798or6l 

Below is dependencies list and their versions: 
```
    "grommet": "2.4.0",
    "grommet-icons": "4.2.0",
    "react": "^16.6.1",
    "react-dom": "^16.6.1",
    "styled-components": "4.1.3"
  ```

**Comment by ShimiSun** [comment] 2019-02-20 19:03
Hi @jesseolsen, please let us know if there is anything else you need help with

**Comment by MikeWalrath** [comment] 2019-03-01 20:08
Hey @jesseolsen Im going to close this issue. Feel free to re-open if you are still seeing the issue.

**Closed by MikeWalrath** 2019-03-01 20:08 UTC
Labels: waiting
