### ISSUE TITLE
`Layer` `position` property not respected on lower resolutions

### ISSUE THREAD

**Issue by versoworks** [grommet/grommet#5226] opened 2021-05-05 23:03 UTC
Using Grommet v2.17.2, when specifying the `position` property on a `Layer` component, the property is respected on high resolutions and not on lower ones. See the [Codesandbox](https://codesandbox.io/s/yabba-dabba-doo-30610-p86yu) example, where the `Layer`s `position` property is set to `right`. If you open the sample in a new window, the content box appears on the right, but on lower resolutions, appears on the left.

**Comment by halocline** [comment] 2021-05-05 23:32
Hi @versoworks, by resolution I am assuming you are speaking to the width of the window dimension. Anyway, Layer has a [property called `responsive`](https://v2.grommet.io/layer#responsive) which default value is `true`. This property says "when at the 'small' breakpoint, fill the screen." 

The behavior you are witnessing at narrower window widths is this responsive behavior. If you'd like to disable this, set `responsive={false}` on the Layer.

Please let us know if this explanation resolves your concern.

**Comment by versoworks** [comment] 2021-05-05 23:42
@halocline yes, that resolves the issue.

Prior to posting here, I did double check the documentation and nothing under the responsive property indicates this behaviour as a side effect. May I suggest the documentation be improved by listing properties affected by the `responsive` property when `true`  (i.e. _when `true`, the `position` property is overridden_, or something to that effect) or the responsive flag be set to `false` by default, as this behaviour is illogical in my opinion.

**Comment by halocline** [comment] 2021-05-06 15:06
The description of `responsive` intends to communicate that at a mobile viewport size, the Layer will fill the height and width of the screen. This was designed to present Layer content in a mobile friendly format. As a point of clarification, the `position` isn't being overwritten, rather the Layer now occupies the entirety of its container. Would you be willing to draft a description for the `responsive` property which would make its behavior more clear?

Regarding defaulting `responsive={false}`, I can see how having callers opt-in to this behavior would be desirable. However, to maintain backwards compatibility, the default can't be changed at this time.

Lastly, try modifying the `width` of your Box to `width={{ min: "small" }}` and see if you like those results better.

I'm going to close this issue since the functionality is behaving as designed and documented. Please feel free to submit a pull request with improved description for the `responsive` property.

**Closed by halocline** 2021-05-06 15:06 UTC
