### ISSUE TITLE
SearchInput does not allow select of suggestions in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#252] opened 2015-11-10 23:45 UTC
Selecting an item in the suggestions dropDown in IE11 results in no change to the display value.

**Comment by ericsoderberghp** [comment] 2016-02-25 05:38
Similar to issue #412. This is caused by IE11 not supporting "new Event".

**Comment by ericsoderberghp** [comment] 2016-02-25 05:47
Fixed in commit 12ef611743605b3bfbbd5540c620e9c9251e34ec.

**Closed by ericsoderberghp** 2016-02-25 05:47 UTC
Labels: in progress
